// GENERATED by gen_stamp.py — do not hand-edit. Regenerate with:
//     python3 gen_stamp.py
// REV is human (CalVer, bumped deliberately); SRC is a digest of the
// geometry sources, so the two cannot silently disagree — gen_stamp.py
// refuses to regenerate if the sources moved and REV did not, and CI
// refuses the commit. See that script's header for what SRC does and
// does not prove (provenance, NOT authenticity).
// Functions, not variables, so nothing here surfaces in the Customizer.
function lcd7_stamp_rev() = "2026.10h";
function lcd7_stamp_src() = "66TSTKW5";
