#!/usr/bin/env python3
"""Regenerate canary_s3_lcd7_qr.scad — the help-QR bit matrix the 7" desk
dock debosses into its base deck.

    python3 gen_qr.py                    # default content
    python3 gen_qr.py "SECURACV.COM/XY"  # different content
    python3 gen_qr.py --check            # CI: exit 1 if the committed file is stale

Rules the default content follows — change it knowingly:
  - UPPERCASE alphanumeric only: that keeps the QR in alphanumeric mode,
    which is what lets 15 characters fit the smallest symbol there is
    (version 1, 21x21) at ECC level Q. Lowercase forces byte mode and
    version 1 can then only hold it at ECC L (7% damage recovery vs 25%).
  - The path is a permanent redirect WE own (securacv.com/qr, served
    case-insensitively) — the printed code never has to change when the
    help content moves; the redirect does.

Deterministic: same content -> byte-identical output, so the generated
file is committed and diffable — and byte-checked in CI (lint.yml runs
`--check`), the same drift gate every other generator in this repo has.
Requires `pip install qrcode` (pure python, no image libs needed for the
matrix). CI pins the qrcode version: the mask pattern a library picks is
part of the bytes, so "same content" is only deterministic per library.
"""
import sys
from pathlib import Path

import qrcode

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "canary_s3_lcd7_qr.scad"
DEFAULT_CONTENT = "SECURACV.COM/QR"


def render(content):
    """The .scad text for `content`, plus (version, module count) for the log."""
    q = qrcode.QRCode(version=None,
                      error_correction=qrcode.constants.ERROR_CORRECT_Q, border=0)
    q.add_data(content)
    q.make(fit=True)
    m = q.modules
    n = len(m)

    rows = ",\n".join(
        "    [" + ",".join("1" if c else "0" for c in row) + "]" for row in m)
    out = f"""\
// GENERATED by gen_qr.py — do not hand-edit. Regenerate with:
//     python3 gen_qr.py "{content}"
// QR version {q.version} ({n}x{n} modules), ECC Q (25% damage recovery).
// Functions, not variables, so nothing here surfaces in the Customizer.
function qr_url()  = "{content}";
function qr_bits() = [
{rows}
];
"""
    return out, q.version, n


def main(argv):
    check = "--check" in argv
    args = [a for a in argv if a != "--check"]
    content = args[0] if args else DEFAULT_CONTENT
    out, version, n = render(content)

    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != out:
            print(
                f"gen_qr.py --check: {OUTPUT.name} is stale — re-run "
                f"python3 docs/hardware/enclosure/gen_qr.py \"{content}\" and "
                f"commit (and attach the 7\" dock's PNG previews, per "
                f"docs/hardware/enclosure/README.md)."
            )
            return 1
        print(f"gen_qr.py --check: OK — \"{content}\" -> version {version}, "
              f"{n}x{n}, ECC Q")
        return 0

    OUTPUT.write_text(out, encoding="utf-8")
    print(f"OK {OUTPUT}: \"{content}\" -> version {version}, {n}x{n}, ECC Q")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
