#!/usr/bin/env python3
"""Regenerate canary_s3_lcd7_qr.scad — the help-QR bit matrix the 7" desk
dock debosses into its base deck.

    python3 gen_qr.py                    # default content
    python3 gen_qr.py "SECURACV.COM/XY"  # different content

Rules the default content follows — change it knowingly:
  - UPPERCASE alphanumeric only: that keeps the QR in alphanumeric mode,
    which is what lets 15 characters fit the smallest symbol there is
    (version 1, 21x21) at ECC level Q. Lowercase forces byte mode and
    version 1 can then only hold it at ECC L (7% damage recovery vs 25%).
  - The path is a permanent redirect WE own (securacv.com/qr, served
    case-insensitively) — the printed code never has to change when the
    help content moves; the redirect does.

Deterministic: same content -> byte-identical output, so the generated
file is committed and diffable. Requires `pip install qrcode` (pure
python, no image libs needed for the matrix).
"""
import sys

import qrcode

content = sys.argv[1] if len(sys.argv) > 1 else "SECURACV.COM/QR"

q = qrcode.QRCode(version=None,
                  error_correction=qrcode.constants.ERROR_CORRECT_Q, border=0)
q.add_data(content)
q.make(fit=True)
m = q.modules
n = len(m)

rows = ",\n".join(
    "    [" + ",".join("1" if c else "0" for c in row) + "]" for row in m)
out = f"""\
// GENERATED by gen_qr.py — do not hand-edit. Regenerate with:
//     python3 gen_qr.py "{content}"
// QR version {q.version} ({n}x{n} modules), ECC Q (25% damage recovery).
// Functions, not variables, so nothing here surfaces in the Customizer.
function qr_url()  = "{content}";
function qr_bits() = [
{rows}
];
"""
path = __file__.rsplit("/", 1)[0] + "/canary_s3_lcd7_qr.scad"
with open(path, "w") as f:
    f.write(out)
print(f"OK {path}: \"{content}\" -> version {q.version}, {n}x{n}, ECC Q")
