// Feedback.swift  (iOS adapter for the shared FeedbackPolicy)
//
// Translates FeedbackEvents into hardware: UIKit haptics graded by event,
// and — for the one moment that earned a voice — the canary's chirp on a
// verified alert path. The chirp plays as a SYSTEM sound on purpose: system
// sounds respect the silent switch, so a muted phone stays mute (calm is a
// setting we honor, not negotiate with). The .wav is generated by
// scripts/make_chirp.py and committed, same contract as the icons; a unit
// test asserts it exists in the bundle so a bundling slip fails CI, not a
// user's first magic moment.

import Foundation

#if canImport(UIKit) && canImport(AudioToolbox)
import UIKit
import AudioToolbox

@MainActor
enum Feedback {
    private static var chirpSoundID: SystemSoundID = {
        guard let url = Bundle.main.url(forResource: "canary-verified", withExtension: "wav") else {
            return 0
        }
        var soundID: SystemSoundID = 0
        AudioServicesCreateSystemSoundID(url as CFURL, &soundID)
        return soundID
    }()

    static func play(_ event: FeedbackEvent?) {
        guard let event else { return }
        switch event {
        case .fleetEscalated(let severity):
            UINotificationFeedbackGenerator().notificationOccurred(
                severity == .tamper ? .error : .warning)
        case .allClear:
            UINotificationFeedbackGenerator().notificationOccurred(.success)
        case .pathVerified:
            UINotificationFeedbackGenerator().notificationOccurred(.success)
            if chirpSoundID != 0 { AudioServicesPlaySystemSound(chirpSoundID) }
        case .pathFailed:
            UINotificationFeedbackGenerator().notificationOccurred(.error)
        }
    }
}

#else

@MainActor
enum Feedback {
    static func play(_ event: FeedbackEvent?) {}
}
#endif
