#!/usr/bin/env python3
"""Pre-compress the large embedded web assets to gzip byte arrays.

The Canary WAP dashboard/settings/companion pages are shipped as PROGMEM raw
string literals and served verbatim over esp_http_server. They are the single
biggest consumer of app-partition flash (~465 KB uncompressed). Browsers all
send `Accept-Encoding: gzip`, so serving pre-compressed bytes with a
`Content-Encoding: gzip` header is transparent and frees ~350 KB of flash.

This script reads each source-of-truth header, extracts the raw-string body,
gzips it, and writes `web_assets_gz.h` containing one byte array + length per
asset. The source headers stay editable; their literals are compiled out via
the CANARY_WEB_ASSETS_GZIPPED guard, so the uncompressed copy never reaches the
binary. Re-run this after editing any of the source HTML files:

    python3 gen_web_assets_gz.py

`--check` regenerates in memory and byte-compares against the committed
web_assets_gz.h, exiting nonzero on drift — the CI gate. The failure mode it
exists for is nasty: because the raw literals are compiled OUT, an edit to
the source HTML that skips the regen ships a repo that shows the new page
while every device keeps serving the old one, and nothing else notices
(an entire wave of dashboard fixes once sailed through review that way).
"""

import gzip
import io
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# (source header, raw-string delimiter, generated symbol prefix)
ASSETS = [
    ("web_ui.h",             "rawliteral",     "CANARY_UI_HTML"),
    ("csi_dashboard_html.h", "DASHBOARD",      "CSI_DASHBOARD_HTML"),
    ("companion_pwa.h",      "COMPANIONHTML",  "COMPANION_HTML"),
]

OUT = HERE / "web_assets_gz.h"


def extract(text: str, delim: str) -> bytes:
    """Return the body of the first R"<delim>( ... )<delim>" literal."""
    open_tok = 'R"' + delim + "("
    close_tok = ")" + delim + '"'
    start = text.find(open_tok)
    if start < 0:
        raise ValueError(f'open token {open_tok!r} not found')
    start += len(open_tok)
    end = text.find(close_tok, start)
    if end < 0:
        raise ValueError(f'close token {close_tok!r} not found')
    return text[start:end].encode("utf-8")


def emit_array(name: str, blob: bytes) -> str:
    lines = [f"static const uint8_t {name}_GZ[] = {{"]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append("  " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"static const size_t {name}_GZ_LEN = sizeof({name}_GZ);")
    return "\n".join(lines)


def main() -> int:
    blocks = []
    summary = []
    for fname, delim, name in ASSETS:
        raw = (HERE / fname).read_text(encoding="utf-8")
        body = extract(raw, delim)
        # mtime=0 keeps the output byte-stable across regenerations.
        # GzipFile (not gzip.compress(mtime=...)) so this runs on Python < 3.8.
        buf = io.BytesIO()
        with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
            gz.write(body)
        comp = buf.getvalue()
        blocks.append(f"// {name}: {len(body)} B raw -> {len(comp)} B gzip "
                      f"(from {fname})\n{emit_array(name, comp)}")
        summary.append((name, len(body), len(comp)))

    header = (
        "// AUTO-GENERATED by gen_web_assets_gz.py — DO NOT EDIT BY HAND.\n"
        "// Source of truth: web_ui.h / csi_dashboard_html.h / companion_pwa.h.\n"
        "// Regenerate with: python3 gen_web_assets_gz.py\n"
        "#ifndef SECURACV_WEB_ASSETS_GZ_H\n"
        "#define SECURACV_WEB_ASSETS_GZ_H\n\n"
        "#include <Arduino.h>\n\n"
        + "\n\n".join(blocks)
        + "\n\n#endif  // SECURACV_WEB_ASSETS_GZ_H\n"
    )
    if "--check" in sys.argv[1:]:
        current = OUT.read_bytes() if OUT.exists() else b""
        if current != header.encode("utf-8"):
            print("STALE: web_assets_gz.h does not match its source HTML")
            print("  (web_ui.h / csi_dashboard_html.h / companion_pwa.h).")
            print("  The raw literals are compiled out via CANARY_WEB_ASSETS_GZIPPED,")
            print("  so devices would serve the OLD page while the repo shows the new one.")
            print("  Fix: python3 gen_web_assets_gz.py  — and commit web_assets_gz.h.")
            return 1
        print("web_assets_gz.h is in sync with its source HTML.")
        return 0

    # newline="\n" forces LF on all platforms (Path.write_text would emit CRLF
    # on Windows, causing spurious diffs).
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)

    total_raw = sum(s[1] for s in summary)
    total_gz = sum(s[2] for s in summary)
    for name, raw_n, gz_n in summary:
        print(f"  {name:<20} {raw_n:>8} B -> {gz_n:>7} B "
              f"({100 * gz_n / raw_n:.0f}%)")
    print(f"  {'TOTAL':<20} {total_raw:>8} B -> {total_gz:>7} B "
          f"(saved {total_raw - total_gz} B)")
    print(f"  wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
