#!/usr/bin/env node
// canary-local/tools/figures/gen_device_glbs.mjs — the figures' 3D tier.
//
// Extrudes every BUILT device figure's massing solids (massing.mjs — the
// same solids the SVG figures, the firmware headers and the Apple
// turntables draw) into a small plain-glTF binary, committed at:
//
//   canary-local/models/<figure-id>.glb        (the browser flasher)
//   desktop/src/models/<figure-id>.glb         (the desktop Flasher)
//
// Two byte-identical copies on purpose: the two flashers share no UI code
// (AGENTS.md rule 7) and the desktop app's CSP is default-src 'self', so
// each frontend ships its own bytes. `--check` regenerates into memory and
// fails on any drift, stray, or missing file in EITHER tree — the same
// generated-and-committed contract as every other catalog.
//
// The confidence ladder is honored at the source: only figures the ledger
// calls prototype-or-better get a solid model — an `idea` renders as a
// dashed ghost everywhere and must never look like a product in 3D either
// (CLAUDE.md, "Which of these is real?"). The ledger (devices/figures.json)
// is generated by gen_figures.mjs, so run that FIRST; this generator reads
// its verdicts rather than re-deriving them.
//
// Geometry notes:
// - One glTF mesh primitive per solid, flat-shaded (per-face normals) — the
//   fleet figures are technical drawings, and the 3D tier keeps the same
//   flat-facet language. Rings come from iso.mjs's prismOf, so a rounded
//   box and a cylinder are the same extrusion path here as in the SVG.
// - Massing space is +X right / +Y toward the viewer / +Z up, min-corner
//   placement in mm. glTF is meters, +Y up, +Z toward the viewer. The axis
//   swap (x, z, y) is a reflection, so every triangle's winding is reversed
//   after mapping — the committed normals test in
//   canary-local/tests/device_models.test.js proves the result.
// - Coplanar discipline is inherited: gen_figures' guardCoplanar refuses
//   massing where two materials share a front plane, so these meshes carry
//   the same no-z-fighting guarantee the website's models do.
// - No textures, no extensions, no Draco/KTX2 — nothing a strict CSP would
//   have to fetch. u16 indices (each primitive is a single small prism).

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FIGURES } from './massing.mjs';
import { prismOf, MATERIALS } from './iso.mjs';
import { stlBounds } from './stlbox.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..', '..');
const ENCLOSURE = join(ROOT, 'docs/hardware/enclosure');
const LEDGER = join(ROOT, 'canary-local/devices/figures.json');
const BOARDS = join(ROOT, 'canary-local/devices/boards.json');
const OUT_DIRS = [
  join(ROOT, 'canary-local/models'),
  join(ROOT, 'desktop/src/models'),
];

/* ── envelope resolution (mirrors gen_figures.mjs envelopeFor — the solids
 *    must be evaluated over the same E or the tiers would disagree) ────── */

const boards = JSON.parse(readFileSync(BOARDS, 'utf8'));
const assembledDims = JSON.parse(
  readFileSync(join(ENCLOSURE, 'assembled_dims.json'), 'utf8'),
);

function toFigureFrame(size, frame) {
  if (frame === 'scad-wall') return { w: size[0], d: size[2], h: size[1] };
  return { w: size[0], d: size[1], h: size[2] };
}

function envelopeFor(fig) {
  if (fig.board) {
    const b = boards.boards[fig.board];
    const [w, d, h] = b.dims_mm;
    return { E: { w, d, h }, parts: {} };
  }
  if (fig.sketch) return { E: { ...fig.sketch }, parts: {} };
  const files = fig.parts || [fig.stl];
  const parts = {};
  for (const file of files) {
    const b = stlBounds(join(ENCLOSURE, file));
    parts[file] = toFigureFrame(b.size, fig.frame);
  }
  if (files.length === 1) return { E: { ...parts[files[0]] }, parts };
  // Multi-part devices use the MEASURED assembled envelope + seams
  // (docs/hardware/enclosure/assembled_dims.json) — never the stacked sum of
  // part boxes, which overstates any nesting assembly. Same contract as
  // gen_figures.mjs, refusal included.
  const asm = assembledDims.devices?.[fig.id];
  if (!asm) {
    throw new Error(`device glbs: ${fig.id} is a multi-part device with no measured `
      + 'assembled envelope — add it to docs/hardware/enclosure/gen_assembled_dims.py.');
  }
  return {
    E: { w: asm.fig.w, d: asm.fig.d, h: asm.fig.h },
    parts,
    assembled: { seams: asm.seams_fig_d },
  };
}

/* ── mesh building ─────────────────────────────────────────────────────── */

// Massing mm → glTF meters, centered in x/depth, grounded in height.
// (x, y, z)mm → (x-cx, z, y-cy)/1000 — a reflection; windings are reversed
// at emission to compensate.
function mapPoint([x, y, z], cx, cy) {
  return [(x - cx) / 1000, z / 1000, (y - cy) / 1000];
}
function mapNormal([nx, ny, nz]) {
  return [nx, nz, ny];
}

const r6 = (v) => Math.round(v * 1e6) / 1e6; // quantize before f32 storage

// One prism → flat-shaded triangles in massing space:
// { pos:[...], nrm:[...], tris:[[a,b,c],...] } with duplicated vertices per
// face (flat shading needs per-face normals).
function meshOfSolid(s) {
  const { A, ring, a0, a1 } = prismOf(s);
  const pos = [];
  const nrm = [];
  const tris = [];
  const push = (p, n) => {
    pos.push(p);
    nrm.push(n);
    return pos.length - 1;
  };
  const n = ring.length;
  // Side walls: one quad per CCW ring edge, outward normal from the edge.
  for (let i = 0; i < n; i++) {
    const a = ring[i];
    const b = ring[(i + 1) % n];
    const eu = b[0] - a[0];
    const ev = b[1] - a[1];
    const len = Math.hypot(eu, ev);
    if (len < 1e-9) continue;
    const N = A.sideN(ev / len, -eu / len);
    const i0 = push(A.to(a[0], a[1], a0), N);
    const i1 = push(A.to(b[0], b[1], a0), N);
    const i2 = push(A.to(b[0], b[1], a1), N);
    const i3 = push(A.to(a[0], a[1], a1), N);
    tris.push([i0, i1, i2], [i0, i2, i3]);
  }
  // Far cap (+capN): the ring is CCW seen from +axis — fan it.
  const capN = A.capN;
  const far = ring.map(([u, v]) => push(A.to(u, v, a1), capN));
  for (let i = 1; i < n - 1; i++) tris.push([far[0], far[i], far[i + 1]]);
  // Near cap (−capN): reversed ring.
  const negN = capN.map((c) => -c);
  const near = ring.map(([u, v]) => push(A.to(u, v, a0), negN));
  for (let i = 1; i < n - 1; i++) tris.push([near[0], near[i + 1], near[i]]);
  return { pos, nrm, tris };
}

/* ── minimal deterministic GLB writer (plain glTF 2.0, u16 indices) ────── */

function buildGlb(fig, solids, E) {
  const cx = E.w / 2;
  const cy = E.d / 2;
  const prims = [];        // { material, pos:Float32Array, nrm, idx }
  const matIndex = new Map();
  const materials = [];
  for (const s of solids) {
    const m = MATERIALS[s.m];
    if (!m) throw new Error(`gen_device_glbs: unknown material "${s.m}" in ${fig.id}`);
    if (!matIndex.has(s.m)) {
      matIndex.set(s.m, materials.length);
      materials.push({
        name: m.name,
        pbrMetallicRoughness: {
          // glTF baseColorFactor is LINEAR by spec; MATERIALS holds sRGB
          // bytes. Dividing by 255 alone stored the sRGB value in the linear
          // field, so every flasher preview rendered lighter than the same
          // nominal color everywhere else — the piecewise EOTF is the same
          // conversion the website's colorway pipeline applies.
          baseColorFactor: [...m.base.map((c) => {
            const s8 = c / 255;
            return r6(s8 <= 0.04045 ? s8 / 12.92 : ((s8 + 0.055) / 1.055) ** 2.4);
          }), 1],
          metallicFactor: s.m === 'metal' ? 0.8 : 0,
          roughnessFactor: s.m === 'glass' || s.m === 'lit' ? 0.35 : 0.85,
        },
      });
    }
    const mesh = meshOfSolid(s);
    const pos = new Float32Array(mesh.pos.length * 3);
    const nrm = new Float32Array(mesh.pos.length * 3);
    mesh.pos.forEach((p, i) => pos.set(mapPoint(p, cx, cy).map(r6), i * 3));
    mesh.nrm.forEach((v, i) => nrm.set(mapNormal(v).map(r6), i * 3));
    // Winding: TWO reflections stack here (iso.mjs's axis-y frame map and
    // our massing→glTF swap are each det −1), so whether a given prism's
    // triangles arrive mirrored depends on its extrusion axis. Rather than
    // carry that bookkeeping, orient each triangle against its own stored
    // normal — exact for these flat-shaded faces, and what the normals test
    // asserts afterward.
    const idx = new Uint16Array(mesh.tris.length * 3);
    mesh.tris.forEach(([a, b, c], i) => {
      const ux = pos[b * 3] - pos[a * 3];
      const uy = pos[b * 3 + 1] - pos[a * 3 + 1];
      const uz = pos[b * 3 + 2] - pos[a * 3 + 2];
      const vx2 = pos[c * 3] - pos[a * 3];
      const vy2 = pos[c * 3 + 1] - pos[a * 3 + 1];
      const vz2 = pos[c * 3 + 2] - pos[a * 3 + 2];
      const gx = uy * vz2 - uz * vy2;
      const gy = uz * vx2 - ux * vz2;
      const gz = ux * vy2 - uy * vx2;
      const dot = gx * nrm[a * 3] + gy * nrm[a * 3 + 1] + gz * nrm[a * 3 + 2];
      idx.set(dot >= 0 ? [a, b, c] : [a, c, b], i * 3);
    });
    prims.push({ material: matIndex.get(s.m), pos, nrm, idx });
  }

  // Pack: BIN chunk = per-primitive [idx (u16, padded to 4)] then [pos, nrm].
  const views = [];
  const accessors = [];
  const chunks = [];
  let off = 0;
  const addView = (bytes, target) => {
    views.push({ buffer: 0, byteOffset: off, byteLength: bytes.byteLength, target });
    chunks.push(bytes);
    off += bytes.byteLength;
    const pad = (4 - (off % 4)) % 4;
    if (pad) {
      chunks.push(new Uint8Array(pad));
      off += pad;
    }
    return views.length - 1;
  };
  const meshes = [];
  const nodes = [];
  for (const p of prims) {
    const iView = addView(new Uint8Array(p.idx.buffer, 0, p.idx.byteLength), 34963);
    const pView = addView(new Uint8Array(p.pos.buffer, 0, p.pos.byteLength), 34962);
    const nView = addView(new Uint8Array(p.nrm.buffer, 0, p.nrm.byteLength), 34962);
    const vcount = p.pos.length / 3;
    const mins = [Infinity, Infinity, Infinity];
    const maxs = [-Infinity, -Infinity, -Infinity];
    for (let i = 0; i < p.pos.length; i += 3) {
      for (let k = 0; k < 3; k++) {
        if (p.pos[i + k] < mins[k]) mins[k] = p.pos[i + k];
        if (p.pos[i + k] > maxs[k]) maxs[k] = p.pos[i + k];
      }
    }
    const iAcc = accessors.push({ bufferView: iView, componentType: 5123, count: p.idx.length, type: 'SCALAR' }) - 1;
    const pAcc = accessors.push({
      bufferView: pView, componentType: 5126, count: vcount, type: 'VEC3',
      min: mins.map(r6), max: maxs.map(r6),
    }) - 1;
    const nAcc = accessors.push({ bufferView: nView, componentType: 5126, count: vcount, type: 'VEC3' }) - 1;
    const mi = meshes.push({
      primitives: [{ attributes: { POSITION: pAcc, NORMAL: nAcc }, indices: iAcc, material: p.material }],
    }) - 1;
    nodes.push({ mesh: mi });
  }

  const json = {
    asset: { version: '2.0', generator: 'securacv-gen-device-glbs' },
    scene: 0,
    scenes: [{ nodes: nodes.map((_, i) => i) }],
    nodes,
    meshes,
    materials,
    accessors,
    bufferViews: views,
    buffers: [{ byteLength: off }],
  };

  const jsonBytes = new TextEncoder().encode(JSON.stringify(json));
  const jsonPad = (4 - (jsonBytes.length % 4)) % 4;
  const binLen = off;
  const total = 12 + 8 + jsonBytes.length + jsonPad + 8 + binLen;
  const out = new Uint8Array(total);
  const dv = new DataView(out.buffer);
  dv.setUint32(0, 0x46546c67, true);           // 'glTF'
  dv.setUint32(4, 2, true);
  dv.setUint32(8, total, true);
  dv.setUint32(12, jsonBytes.length + jsonPad, true);
  dv.setUint32(16, 0x4e4f534a, true);          // 'JSON'
  out.set(jsonBytes, 20);
  for (let i = 0; i < jsonPad; i++) out[20 + jsonBytes.length + i] = 0x20;
  let p = 20 + jsonBytes.length + jsonPad;
  dv.setUint32(p, binLen, true);
  dv.setUint32(p + 4, 0x004e4942, true);       // 'BIN'
  p += 8;
  for (const c of chunks) {
    out.set(c instanceof Uint8Array ? c : new Uint8Array(c), p);
    p += c.byteLength;
  }
  return out;
}

/* ── the run ───────────────────────────────────────────────────────────── */

export function builtDeviceFigures() {
  const ledger = JSON.parse(readFileSync(LEDGER, 'utf8'));
  const verdict = new Map(ledger.figures.map((f) => [f.id, f.confidence]));
  return FIGURES.filter((f) => {
    if (!f.id.startsWith('device.')) return false;
    const c = verdict.get(f.id);
    if (!c) throw new Error(`gen_device_glbs: ${f.id} is not in figures.json — run gen_figures.mjs first`);
    return c !== 'idea'; // a ghost never gets a product-looking 3D body
  });
}

export function buildOne(fig) {
  const { E, parts, assembled } = envelopeFor(fig);
  const solids = fig.build(E, parts, assembled ? { seams: assembled.seams } : undefined);
  return buildGlb(fig, solids, E);
}

const self = fileURLToPath(import.meta.url);
if (process.argv[1] && fileURLToPath(new URL(`file://${process.argv[1]}`)) === self) {
  const check = process.argv.includes('--check');
  const want = new Map(); // filename → bytes
  for (const fig of builtDeviceFigures()) {
    want.set(`${fig.id}.glb`, buildOne(fig));
  }
  let bad = 0;
  for (const dir of OUT_DIRS) {
    if (!check) mkdirSync(dir, { recursive: true });
    const have = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.glb')) : [];
    for (const stray of have) {
      if (!want.has(stray)) {
        if (check) {
          console.error(`stale: ${join(dir, stray)} — no built device figure produces it`);
          bad++;
        }
      }
    }
    for (const [name, bytes] of want) {
      const path = join(dir, name);
      if (check) {
        if (!existsSync(path)) {
          console.error(`missing: ${path} — run gen_device_glbs.mjs`);
          bad++;
          continue;
        }
        const disk = readFileSync(path);
        if (disk.length !== bytes.length || !disk.every((b, i) => b === bytes[i])) {
          console.error(`drift: ${path} — regenerate and commit (gen_device_glbs.mjs)`);
          bad++;
        }
      } else {
        writeFileSync(path, bytes);
      }
    }
  }
  if (check && bad) process.exit(1);
  if (!check) {
    console.log(`device models: ${want.size} figures → ${OUT_DIRS.length} trees`);
    for (const [name, bytes] of want) console.log(`  ${name}  ${bytes.length} bytes`);
  }
}
