#pragma once
// Flavor-dispatching config (GENERATED by setup.sh — do not hand-edit;
// pick the flavor in flavor_select.h). The flavor_<name>.h copies mirror
// firmware/configs/canary-display/<flavor>/config.h.
#include "flavor_select.h"
#if defined(CD_BUILD_DASH) && CD_BUILD_DASH
#include "flavor_dash.h"
#else
#include "flavor_watch.h"
#endif
