#pragma once
// ── PICK YOUR HARDWARE (zip-download builds) ────────────────────────────
// The sketch compiles out of the box for the Canary WATCH (XIAO ESP32-S3 +
// Seeed Round Display). Building the DASH (Waveshare ESP32-S3-Touch-LCD-4.3B)
// takes one line: change the 0 below to 1 — and pick the matching dash /
// dash-core3 build profile in the toolbar.
//
// Working from a git checkout? Run `./setup.sh arduino <watch|dash>` instead:
// it writes the git-ignored flavor_local.h override so this committed file
// never shows as modified.
// (GENERATED by setup.sh — edits here survive until the next regen.)
#if __has_include("flavor_local.h")
#include "flavor_local.h"
#endif
#ifndef CD_BUILD_DASH
#define CD_BUILD_DASH 0
#endif
