#pragma once
// ── FLAVOR SELECTION: follows your BOARD choice ─────────────────────────
// No explicit override present? The flavor is inferred from the selected
// board, so every documented path just works:
//   XIAO_ESP32S3 board / watch(-core3) cli profile      -> WATCH firmware
//   ESP32S3 Dev Module / dash(-core3) cli profile       -> DASH firmware
//   Waveshare ESP32-S3-Touch-LCD-4.3 / 4.3B (vendor     -> DASH firmware
//     entries in arduino-esp32 core 3.x; the 4.3B board    (4.3B gets the
//     also selects the 4.3B pin map with isolated IO)       B pin map)
// This is what makes `arduino-cli compile --profile dash-core3` and the
// IDE's Tools->Board menu safe: you cannot build watch firmware for dash
// hardware by forgetting a define (review catch).
//
// Overrides (for exotic boards): `./setup.sh arduino <watch|dash|playground|modes>`
// writes the git-ignored flavor_local.h, or define CD_BUILD_DASH 0/1 (and
// optionally CD_BOARD_DASH43B 1 / FEATURE_PLAYGROUND 1) there yourself. An
// explicit override always wins over board inference.
// (GENERATED by setup.sh — do not hand-edit; use flavor_local.h.)
#if __has_include("flavor_local.h")
#include "flavor_local.h"
#endif
#ifndef CD_BUILD_DASH
  #if defined(ARDUINO_XIAO_ESP32S3)
    #define CD_BUILD_DASH 0
  #elif defined(ARDUINO_ESP32S3_DEV)
    #define CD_BUILD_DASH 1
  #elif defined(ARDUINO_WAVESHARE_ESP32_S3_TOUCH_LCD_43) || \
        defined(ARDUINO_WAVESHARE_ESP32_S3_TOUCH_LCD_43B)
    /* Waveshare's own board entries (arduino-esp32 core 3.x Boards
     * Manager) are dash hardware by definition. */
    #define CD_BUILD_DASH 1
  #else
    /* Unrecognized board (a vendor board package defines its own board
     * macro we can't know). Guessing here could flash the WRONG FLAVOR
     * silently - fail loud with the fix instead. */
    #error "Board not recognized. Pick Tools->Board 'XIAO_ESP32S3' (watch), 'ESP32S3 Dev Module' or 'Waveshare ESP32-S3-Touch-LCD-4.3/4.3B' (dash) from 'esp32 by Espressif Systems' - or create flavor_local.h next to this sketch with '#define CD_BUILD_DASH 0' (watch) or '#define CD_BUILD_DASH 1' (dash)."
  #endif
#endif
// Board-variant selection inside the dash flavor: the 4.3B pin map adds
// the terminal block (isolated DI/DO, dedicated CAN, RS485-on-console) —
// required by FEATURE_PLAYGROUND, optional otherwise (both SKUs share the
// panel nets).
#ifndef CD_BOARD_DASH43B
  #if defined(ARDUINO_WAVESHARE_ESP32_S3_TOUCH_LCD_43B)
    #define CD_BOARD_DASH43B 1
  #else
    #define CD_BOARD_DASH43B 0
  #endif
#endif
