#pragma once
// ── FLAVOR SELECTION: follows your BOARD choice ─────────────────────────
// No explicit override present? The flavor is inferred from the selected
// board, so every documented path just works:
//   XIAO_ESP32S3 board / watch(-core3) cli profile  -> WATCH firmware
//   ESP32S3 Dev Module / dash(-core3) cli profile   -> DASH firmware
// This is what makes `arduino-cli compile --profile dash-core3` and the
// IDE's Tools->Board menu safe: you cannot build watch firmware for dash
// hardware by forgetting a define (review catch).
//
// Overrides (for exotic boards): `./setup.sh arduino <watch|dash>` writes
// the git-ignored flavor_local.h, or define CD_BUILD_DASH 0/1 there
// yourself. An explicit override always wins over board inference.
// (GENERATED by setup.sh — do not hand-edit; use flavor_local.h.)
#if __has_include("flavor_local.h")
#include "flavor_local.h"
#endif
#ifndef CD_BUILD_DASH
  #if defined(ARDUINO_XIAO_ESP32S3)
    #define CD_BUILD_DASH 0
  #elif defined(ARDUINO_ESP32S3_DEV)
    #define CD_BUILD_DASH 1
  #else
    #define CD_BUILD_DASH 0   /* unknown board: watch, the entry product */
  #endif
#endif
