#pragma once
// GENERATED by canary-local/tools/figures/gen_figures.mjs — do not edit.
// Spec: docs/design/FLEET_FIGURES.md (§10, drawing the fleet on the glass).
//
// The glyph tier of each RESOLVABLE figure (every id the kFigures/kHardware
// rows in fleet_figures.h can return), as painter-ordered faces that are
// already triangulated — the same projector, camera and palette as every
// other surface, so the picture beside a witness on a display is the same
// picture the phone and the catalog draw.
//
// Geometry is quarter-units in the glyph's 64-unit box: multiply a
// coordinate by the pixel size, then divide by kFigureArtScale. Faces are
// solid physical-object colors on purpose — a Canary's case is off-white in
// every theme (the same rule FleetSolids.swift states) — so a renderer tints
// nothing and the night face simply hides the art instead of recoloring it.
//
// Pure C++, no LVGL, no Arduino, no allocation: host-testable like
// fleet_figures.h, renderer-agnostic by design.

#include <stdint.h>
#include <stddef.h>

#include "fleet_figures.h"  // figure ids + figure_streq

namespace canary::figures {

struct ArtFace {
  uint32_t rgb;             // 0xRRGGBB, the face's own physical color
  uint16_t tri_count;       // triangles in tris (tris holds tri_count * 6)
  const int16_t* tris;      // x0,y0,x1,y1,x2,y2 per triangle, quarter-units
};

struct FigureArt {
  const char* figure_id;    // the ledger id, e.g. "device.canary-sense"
  const char* rev;          // matches the figure's rev in fleet_figures.h
  uint16_t face_count;
  const ArtFace* faces;     // painter-ordered: draw first to last
};

// One denominator for every coordinate: px = coord * size_px / kFigureArtScale.
inline constexpr int kFigureArtScale = 256;

inline constexpr int16_t kArt_device_canary_display_amoled241_t0[] = {168,239,193,225,193,78,193,78,168,91,168,239};
inline constexpr int16_t kArt_device_canary_display_amoled241_t1[] = {192,75,168,89,168,91};
inline constexpr int16_t kArt_device_canary_display_amoled241_t2[] = {192,73,167,87,168,89};
inline constexpr int16_t kArt_device_canary_display_amoled241_t3[] = {167,87,192,73,191,71,191,71,166,85,167,87};
inline constexpr int16_t kArt_device_canary_display_amoled241_t4[] = {166,85,191,71,189,69,189,69,165,83,166,85};
inline constexpr int16_t kArt_device_canary_display_amoled241_t5[] = {188,67,163,81,165,83};
inline constexpr int16_t kArt_device_canary_display_amoled241_t6[] = {186,66,162,80,163,81};
inline constexpr int16_t kArt_device_canary_display_amoled241_t7[] = {162,80,186,66,94,13,94,13,70,27,162,80};
inline constexpr int16_t kArt_device_canary_display_amoled241_t8[] = {70,190,168,239,162,80,162,80,63,31,70,190};
inline constexpr int16_t kArt_device_canary_display_amoled241_t9[] = {159,233,164,231,164,95,164,95,159,97,159,233};
inline constexpr int16_t kArt_device_canary_display_amoled241_t10[] = {155,89,159,87,73,37,73,37,68,39,155,89};
inline constexpr int16_t kArt_device_canary_display_amoled241_t11[] = {68,186,159,233,155,89,155,89,63,42,68,186};
inline constexpr int16_t kArt_device_canary_display_amoled241_t12[] = {153,101,152,102,152,223};
inline constexpr int16_t kArt_device_canary_display_amoled241_t13[] = {73,51,72,51,149,96};
inline constexpr int16_t kArt_device_canary_display_amoled241_t14[] = {72,181,152,223,149,96,149,96,69,53,72,181};
inline constexpr ArtFace kArt_device_canary_display_amoled241_faces[] = {
  { 0xA5A39F, 2, kArt_device_canary_display_amoled241_t0 },
  { 0xB2B1AC, 1, kArt_device_canary_display_amoled241_t1 },
  { 0xC8C7C2, 1, kArt_device_canary_display_amoled241_t2 },
  { 0xD8D6D0, 2, kArt_device_canary_display_amoled241_t3 },
  { 0xDFDDD7, 2, kArt_device_canary_display_amoled241_t4 },
  { 0xDEDCD6, 1, kArt_device_canary_display_amoled241_t5 },
  { 0xD4D2CD, 1, kArt_device_canary_display_amoled241_t6 },
  { 0xCCCAC5, 2, kArt_device_canary_display_amoled241_t7 },
  { 0x61615E, 2, kArt_device_canary_display_amoled241_t8 },
  { 0x13161E, 2, kArt_device_canary_display_amoled241_t9 },
  { 0x181B25, 2, kArt_device_canary_display_amoled241_t10 },
  { 0x0B0D12, 2, kArt_device_canary_display_amoled241_t11 },
  { 0x2B4F77, 1, kArt_device_canary_display_amoled241_t12 },
  { 0x366294, 1, kArt_device_canary_display_amoled241_t13 },
  { 0x1A2F47, 2, kArt_device_canary_display_amoled241_t14 },
};

inline constexpr int16_t kArt_device_canary_display_dash_t0[] = {231,217,194,238,194,239};
inline constexpr int16_t kArt_device_canary_display_dash_t1[] = {194,238,231,217,231,107,231,107,194,128,194,238};
inline constexpr int16_t kArt_device_canary_display_dash_t2[] = {230,105,194,126,194,128};
inline constexpr int16_t kArt_device_canary_display_dash_t3[] = {230,103,194,124,194,126};
inline constexpr int16_t kArt_device_canary_display_dash_t4[] = {229,102,193,123,194,124};
inline constexpr int16_t kArt_device_canary_display_dash_t5[] = {228,100,192,121,193,123};
inline constexpr int16_t kArt_device_canary_display_dash_t6[] = {227,99,190,120,192,121};
inline constexpr int16_t kArt_device_canary_display_dash_t7[] = {225,98,189,119,190,120};
inline constexpr int16_t kArt_device_canary_display_dash_t8[] = {189,119,225,98,78,13,78,13,42,34,189,119};
inline constexpr int16_t kArt_device_canary_display_dash_t9[] = {77,12,40,33,42,34};
inline constexpr int16_t kArt_device_canary_display_dash_t10[] = {42,156,194,238,189,119,189,119,36,37,42,156};
inline constexpr int16_t kArt_device_canary_display_dash_t11[] = {175,242,190,233,190,128,190,128,175,137,175,242};
inline constexpr int16_t kArt_device_canary_display_dash_t12[] = {172,131,187,122,44,40,44,40,29,48,172,131};
inline constexpr int16_t kArt_device_canary_display_dash_t13[] = {29,161,175,242,172,131,172,131,25,50,29,161};
inline constexpr int16_t kArt_device_canary_display_dash_t14[] = {32,158,170,235,168,135,168,135,30,57,32,158};
inline constexpr ArtFace kArt_device_canary_display_dash_faces[] = {
  { 0x969591, 1, kArt_device_canary_display_dash_t0 },
  { 0xA5A39F, 2, kArt_device_canary_display_dash_t1 },
  { 0xB2B1AC, 1, kArt_device_canary_display_dash_t2 },
  { 0xC8C7C2, 1, kArt_device_canary_display_dash_t3 },
  { 0xD8D6D0, 1, kArt_device_canary_display_dash_t4 },
  { 0xDFDDD7, 1, kArt_device_canary_display_dash_t5 },
  { 0xDEDCD6, 1, kArt_device_canary_display_dash_t6 },
  { 0xD4D2CD, 1, kArt_device_canary_display_dash_t7 },
  { 0xCCCAC5, 2, kArt_device_canary_display_dash_t8 },
  { 0xC2C1BC, 1, kArt_device_canary_display_dash_t9 },
  { 0x61615E, 2, kArt_device_canary_display_dash_t10 },
  { 0x13161E, 2, kArt_device_canary_display_dash_t11 },
  { 0x181B25, 2, kArt_device_canary_display_dash_t12 },
  { 0x0B0D12, 2, kArt_device_canary_display_dash_t13 },
  { 0x1A2F47, 2, kArt_device_canary_display_dash_t14 },
};

inline constexpr int16_t kArt_device_canary_display_dash7_t0[] = {209,241,225,231,225,118,225,118,209,128,209,241};
inline constexpr int16_t kArt_device_canary_display_dash7_t1[] = {205,120,221,111,51,13,51,13,35,22,205,120};
inline constexpr int16_t kArt_device_canary_display_dash7_t2[] = {35,145,209,241,205,120,205,120,31,25,35,145};
inline constexpr int16_t kArt_device_canary_display_dash7_t3[] = {204,129,201,130,201,235};
inline constexpr int16_t kArt_device_canary_display_dash7_t4[] = {38,30,36,31,199,125};
inline constexpr int16_t kArt_device_canary_display_dash7_t5[] = {36,143,201,235,199,125,199,125,34,33,36,143};
inline constexpr int16_t kArt_device_canary_display_dash7_t6[] = {52,53,51,53,183,129};
inline constexpr int16_t kArt_device_canary_display_dash7_t7[] = {51,140,184,215,183,129,183,129,50,54,51,140};
inline constexpr ArtFace kArt_device_canary_display_dash7_faces[] = {
  { 0xA5A39F, 2, kArt_device_canary_display_dash7_t0 },
  { 0xCCCAC5, 2, kArt_device_canary_display_dash7_t1 },
  { 0x61615E, 2, kArt_device_canary_display_dash7_t2 },
  { 0x13161E, 1, kArt_device_canary_display_dash7_t3 },
  { 0x181B25, 1, kArt_device_canary_display_dash7_t4 },
  { 0x0B0D12, 2, kArt_device_canary_display_dash7_t5 },
  { 0x366294, 1, kArt_device_canary_display_dash7_t6 },
  { 0x1A2F47, 2, kArt_device_canary_display_dash7_t7 },
};

inline constexpr int16_t kArt_device_canary_display_nightstand_t0[] = {141,244,155,236,155,192,155,192,141,200,141,244};
inline constexpr int16_t kArt_device_canary_display_nightstand_t1[] = {141,200,155,192,117,170,117,170,103,178,141,200};
inline constexpr int16_t kArt_device_canary_display_nightstand_t2[] = {103,178,103,222,141,244,141,244,141,200,103,178};
inline constexpr int16_t kArt_device_canary_display_nightstand_t3[] = {180,189,154,204,154,207};
inline constexpr int16_t kArt_device_canary_display_nightstand_t4[] = {154,204,180,189,180,64,180,64,154,79,154,204};
inline constexpr int16_t kArt_device_canary_display_nightstand_t5[] = {154,79,180,64,180,61,180,61,154,76,154,79};
inline constexpr int16_t kArt_device_canary_display_nightstand_t6[] = {154,76,180,61,179,58,179,58,153,72,154,76};
inline constexpr int16_t kArt_device_canary_display_nightstand_t7[] = {153,72,179,58,177,54,177,54,151,69,153,72};
inline constexpr int16_t kArt_device_canary_display_nightstand_t8[] = {151,69,177,54,175,51,175,51,149,66,151,69};
inline constexpr int16_t kArt_device_canary_display_nightstand_t9[] = {149,66,175,51,172,49,172,49,147,64,149,66};
inline constexpr int16_t kArt_device_canary_display_nightstand_t10[] = {147,64,172,49,170,47,170,47,144,62,147,64};
inline constexpr int16_t kArt_device_canary_display_nightstand_t11[] = {144,62,170,47,112,13,112,13,86,28,144,62};
inline constexpr int16_t kArt_device_canary_display_nightstand_t12[] = {109,12,84,27,86,28};
inline constexpr int16_t kArt_device_canary_display_nightstand_t13[] = {84,174,153,209,147,64,147,64,77,29,84,174};
inline constexpr int16_t kArt_device_canary_display_nightstand_t14[] = {143,198,146,197,146,76,146,76,143,78,143,198};
inline constexpr int16_t kArt_device_canary_display_nightstand_t15[] = {138,70,141,68,90,39,90,39,87,40,138,70};
inline constexpr int16_t kArt_device_canary_display_nightstand_t16[] = {87,171,143,198,138,70,138,70,82,43,87,171};
inline constexpr int16_t kArt_device_canary_display_nightstand_t17[] = {141,81,139,82,139,191};
inline constexpr int16_t kArt_device_canary_display_nightstand_t18[] = {89,48,88,48,136,76};
inline constexpr int16_t kArt_device_canary_display_nightstand_t19[] = {88,165,139,191,136,76,136,76,85,50,88,165};
inline constexpr ArtFace kArt_device_canary_display_nightstand_faces[] = {
  { 0x292B30, 2, kArt_device_canary_display_nightstand_t0 },
  { 0x33363C, 2, kArt_device_canary_display_nightstand_t1 },
  { 0x181A1D, 2, kArt_device_canary_display_nightstand_t2 },
  { 0x969591, 1, kArt_device_canary_display_nightstand_t3 },
  { 0xA5A39F, 2, kArt_device_canary_display_nightstand_t4 },
  { 0xB2B1AC, 2, kArt_device_canary_display_nightstand_t5 },
  { 0xC8C7C2, 2, kArt_device_canary_display_nightstand_t6 },
  { 0xD8D6D0, 2, kArt_device_canary_display_nightstand_t7 },
  { 0xDFDDD7, 2, kArt_device_canary_display_nightstand_t8 },
  { 0xDEDCD6, 2, kArt_device_canary_display_nightstand_t9 },
  { 0xD4D2CD, 2, kArt_device_canary_display_nightstand_t10 },
  { 0xCCCAC5, 2, kArt_device_canary_display_nightstand_t11 },
  { 0xC2C1BC, 1, kArt_device_canary_display_nightstand_t12 },
  { 0x61615E, 2, kArt_device_canary_display_nightstand_t13 },
  { 0x13161E, 2, kArt_device_canary_display_nightstand_t14 },
  { 0x181B25, 2, kArt_device_canary_display_nightstand_t15 },
  { 0x0B0D12, 2, kArt_device_canary_display_nightstand_t16 },
  { 0x2B4F77, 1, kArt_device_canary_display_nightstand_t17 },
  { 0x366294, 1, kArt_device_canary_display_nightstand_t18 },
  { 0x1A2F47, 2, kArt_device_canary_display_nightstand_t19 },
};

inline constexpr int16_t kArt_device_canary_display_touch169_t0[] = {220,215,176,240,175,242};
inline constexpr int16_t kArt_device_canary_display_touch169_t1[] = {220,212,176,238,176,240};
inline constexpr int16_t kArt_device_canary_display_touch169_t2[] = {176,238,220,212,220,99,220,99,176,125,176,238};
inline constexpr int16_t kArt_device_canary_display_touch169_t3[] = {176,125,220,99,220,97,220,97,176,122,176,125};
inline constexpr int16_t kArt_device_canary_display_touch169_t4[] = {176,122,220,97,219,93,219,93,175,119,176,122};
inline constexpr int16_t kArt_device_canary_display_touch169_t5[] = {175,119,219,93,217,90,217,90,174,116,175,119};
inline constexpr int16_t kArt_device_canary_display_touch169_t6[] = {174,116,217,90,215,88,215,88,172,113,174,116};
inline constexpr int16_t kArt_device_canary_display_touch169_t7[] = {172,113,215,88,213,85,213,85,169,111,172,113};
inline constexpr int16_t kArt_device_canary_display_touch169_t8[] = {169,111,213,85,211,84,211,84,167,109,169,111};
inline constexpr int16_t kArt_device_canary_display_touch169_t9[] = {167,109,211,84,89,13,89,13,45,38,167,109};
inline constexpr int16_t kArt_device_canary_display_touch169_t10[] = {87,12,43,37,45,38};
inline constexpr int16_t kArt_device_canary_display_touch169_t11[] = {84,12,41,37,43,37};
inline constexpr int16_t kArt_device_canary_display_touch169_t12[] = {45,172,176,240,167,109,167,109,36,41,45,172};
inline constexpr int16_t kArt_device_canary_display_touch169_t13[] = {162,232,169,228,169,126,169,126,162,129,162,232};
inline constexpr int16_t kArt_device_canary_display_touch169_t14[] = {156,119,163,115,50,50,50,50,43,54,156,119};
inline constexpr int16_t kArt_device_canary_display_touch169_t15[] = {43,170,162,232,156,119,156,119,37,57,43,170};
inline constexpr int16_t kArt_device_canary_display_touch169_t16[] = {154,132,153,133,153,221};
inline constexpr int16_t kArt_device_canary_display_touch169_t17[] = {49,66,48,67,149,125};
inline constexpr int16_t kArt_device_canary_display_touch169_t18[] = {48,165,153,221,149,125,149,125,43,69,48,165};
inline constexpr ArtFace kArt_device_canary_display_touch169_faces[] = {
  { 0x777673, 1, kArt_device_canary_display_touch169_t0 },
  { 0x969591, 1, kArt_device_canary_display_touch169_t1 },
  { 0xA5A39F, 2, kArt_device_canary_display_touch169_t2 },
  { 0xB2B1AC, 2, kArt_device_canary_display_touch169_t3 },
  { 0xC8C7C2, 2, kArt_device_canary_display_touch169_t4 },
  { 0xD8D6D0, 2, kArt_device_canary_display_touch169_t5 },
  { 0xDFDDD7, 2, kArt_device_canary_display_touch169_t6 },
  { 0xDEDCD6, 2, kArt_device_canary_display_touch169_t7 },
  { 0xD4D2CD, 2, kArt_device_canary_display_touch169_t8 },
  { 0xCCCAC5, 2, kArt_device_canary_display_touch169_t9 },
  { 0xC2C1BC, 1, kArt_device_canary_display_touch169_t10 },
  { 0xAAA9A4, 1, kArt_device_canary_display_touch169_t11 },
  { 0x61615E, 2, kArt_device_canary_display_touch169_t12 },
  { 0x13161E, 2, kArt_device_canary_display_touch169_t13 },
  { 0x181B25, 2, kArt_device_canary_display_touch169_t14 },
  { 0x0B0D12, 2, kArt_device_canary_display_touch169_t15 },
  { 0x2B4F77, 1, kArt_device_canary_display_touch169_t16 },
  { 0x366294, 1, kArt_device_canary_display_touch169_t17 },
  { 0x1A2F47, 2, kArt_device_canary_display_touch169_t18 },
};

inline constexpr int16_t kArt_device_canary_display_watch_t0[] = {176,189,234,156,232,138,232,138,175,171,176,189};
inline constexpr int16_t kArt_device_canary_display_watch_t1[] = {175,171,232,138,228,118,228,118,171,152,175,171};
inline constexpr int16_t kArt_device_canary_display_watch_t2[] = {171,152,228,118,221,99,221,99,163,132,171,152};
inline constexpr int16_t kArt_device_canary_display_watch_t3[] = {163,132,221,99,211,80,211,80,154,113,163,132};
inline constexpr int16_t kArt_device_canary_display_watch_t4[] = {154,113,211,80,200,62,200,62,142,95,154,113};
inline constexpr int16_t kArt_device_canary_display_watch_t5[] = {142,95,200,62,186,46,186,46,129,79,142,95};
inline constexpr int16_t kArt_device_canary_display_watch_t6[] = {129,79,186,46,172,33,172,33,114,66,129,79};
inline constexpr int16_t kArt_device_canary_display_watch_t7[] = {114,66,172,33,157,22,157,22,99,56,114,66};
inline constexpr int16_t kArt_device_canary_display_watch_t8[] = {99,56,157,22,142,15,142,15,84,49,99,56};
inline constexpr int16_t kArt_device_canary_display_watch_t9[] = {84,49,142,15,127,12,127,12,70,45,84,49};
inline constexpr int16_t kArt_device_canary_display_watch_t10[] = {70,45,127,12,114,13,114,13,56,46,70,45};
inline constexpr int16_t kArt_device_canary_display_watch_t11[] = {114,13,45,50,56,46};
inline constexpr int16_t kArt_device_canary_display_watch_t12[] = {221,198,163,231,154,239};
inline constexpr int16_t kArt_device_canary_display_watch_t13[] = {163,231,221,198,228,187,228,187,171,220,163,231};
inline constexpr int16_t kArt_device_canary_display_watch_t14[] = {171,220,228,187,232,172,232,172,175,206,171,220};
inline constexpr int16_t kArt_device_canary_display_watch_t15[] = {175,206,232,172,234,156,234,156,176,189,175,206};
inline constexpr int16_t kArt_device_canary_display_watch_t16[] = {175,206,175,171,163,132,175,206,163,132,142,95,175,206,142,95,114,66,175,206,114,66,84,49,175,206,84,49,56,46,175,206,56,46,35,58,175,206,35,58,24,84,175,206,24,84,24,118,175,206,24,118,35,157,175,206,35,157,56,194,175,206,56,194,84,223,175,206,84,223,114,241,175,206,114,241,142,243,142,243,163,231,175,206};
inline constexpr int16_t kArt_device_canary_display_watch_t17[] = {160,187,166,183,165,167,165,167,159,171,160,187};
inline constexpr int16_t kArt_device_canary_display_watch_t18[] = {159,171,165,167,161,151,161,151,155,154,159,171};
inline constexpr int16_t kArt_device_canary_display_watch_t19[] = {155,154,161,151,155,134,155,134,149,137,155,154};
inline constexpr int16_t kArt_device_canary_display_watch_t20[] = {149,137,155,134,147,117,147,117,141,121,149,137};
inline constexpr int16_t kArt_device_canary_display_watch_t21[] = {141,121,147,117,136,102,136,102,131,105,141,121};
inline constexpr int16_t kArt_device_canary_display_watch_t22[] = {131,105,136,102,125,88,125,88,119,91,131,105};
inline constexpr int16_t kArt_device_canary_display_watch_t23[] = {119,91,125,88,112,76,112,76,106,80,119,91};
inline constexpr int16_t kArt_device_canary_display_watch_t24[] = {106,80,112,76,99,67,99,67,93,71,106,80};
inline constexpr int16_t kArt_device_canary_display_watch_t25[] = {93,71,99,67,86,61,86,61,80,65,93,71};
inline constexpr int16_t kArt_device_canary_display_watch_t26[] = {80,65,86,61,74,59,74,59,68,62,80,65};
inline constexpr int16_t kArt_device_canary_display_watch_t27[] = {155,213,161,210,165,197,165,197,159,201,155,213};
inline constexpr int16_t kArt_device_canary_display_watch_t28[] = {159,201,165,197,166,183,166,183,160,187,159,201};
inline constexpr int16_t kArt_device_canary_display_watch_t29[] = {159,201,159,171,141,121,159,201,141,121,106,80,159,201,106,80,80,65,159,201,80,65,56,62,159,201,56,62,38,73,159,201,38,73,28,95,159,201,28,95,28,125,159,201,28,125,46,175,159,201,46,175,80,216,159,201,80,216,106,231,159,201,106,231,131,234,131,234,149,223,159,201};
inline constexpr int16_t kArt_device_canary_display_watch_t30[] = {147,193,144,154,123,113,147,193,123,113,92,84,147,193,92,84,71,76,147,193,71,76,52,80,147,193,52,80,40,94,147,193,40,94,37,130,147,193,37,130,52,172,147,193,52,172,81,206,147,193,81,206,114,221,147,193,114,221,132,218,132,218,144,204,147,193};
inline constexpr ArtFace kArt_device_canary_display_watch_faces[] = {
  { 0xAFADA9, 2, kArt_device_canary_display_watch_t0 },
  { 0xC1BFBA, 2, kArt_device_canary_display_watch_t1 },
  { 0xCFCDC8, 2, kArt_device_canary_display_watch_t2 },
  { 0xD9D7D2, 2, kArt_device_canary_display_watch_t3 },
  { 0xDFDDD7, 2, kArt_device_canary_display_watch_t4 },
  { 0xDFDDD7, 2, kArt_device_canary_display_watch_t5 },
  { 0xDBD9D3, 2, kArt_device_canary_display_watch_t6 },
  { 0xD2D0CB, 2, kArt_device_canary_display_watch_t7 },
  { 0xC5C3BE, 2, kArt_device_canary_display_watch_t8 },
  { 0xB4B2AE, 2, kArt_device_canary_display_watch_t9 },
  { 0xA09E9A, 2, kArt_device_canary_display_watch_t10 },
  { 0x898884, 1, kArt_device_canary_display_watch_t11 },
  { 0x61615E, 1, kArt_device_canary_display_watch_t12 },
  { 0x6B6A67, 2, kArt_device_canary_display_watch_t13 },
  { 0x83827F, 2, kArt_device_canary_display_watch_t14 },
  { 0x9A9995, 2, kArt_device_canary_display_watch_t15 },
  { 0x61615E, 14, kArt_device_canary_display_watch_t16 },
  { 0x141720, 2, kArt_device_canary_display_watch_t17 },
  { 0x161A23, 2, kArt_device_canary_display_watch_t18 },
  { 0x181C25, 2, kArt_device_canary_display_watch_t19 },
  { 0x191D27, 2, kArt_device_canary_display_watch_t20 },
  { 0x1A1E28, 2, kArt_device_canary_display_watch_t21 },
  { 0x1A1E28, 2, kArt_device_canary_display_watch_t22 },
  { 0x191D28, 2, kArt_device_canary_display_watch_t23 },
  { 0x181C26, 2, kArt_device_canary_display_watch_t24 },
  { 0x171A24, 2, kArt_device_canary_display_watch_t25 },
  { 0x151821, 2, kArt_device_canary_display_watch_t26 },
  { 0x0F1218, 2, kArt_device_canary_display_watch_t27 },
  { 0x12151C, 2, kArt_device_canary_display_watch_t28 },
  { 0x0B0D12, 12, kArt_device_canary_display_watch_t29 },
  { 0x1A2F47, 11, kArt_device_canary_display_watch_t30 },
};

inline constexpr int16_t kArt_device_canary_nightlight_t0[] = {64,186,73,180,73,27,73,27,64,33,64,186};
inline constexpr int16_t kArt_device_canary_nightlight_t1[] = {64,186,64,33,62,32};
inline constexpr int16_t kArt_device_canary_nightlight_t2[] = {194,214,149,240,148,242};
inline constexpr int16_t kArt_device_canary_nightlight_t3[] = {194,211,150,237,149,240};
inline constexpr int16_t kArt_device_canary_nightlight_t4[] = {150,237,194,211,194,70,194,70,150,96,150,237};
inline constexpr int16_t kArt_device_canary_nightlight_t5[] = {150,96,194,70,194,66,194,66,149,92,150,96};
inline constexpr int16_t kArt_device_canary_nightlight_t6[] = {149,92,194,66,193,63,193,63,148,89,149,92};
inline constexpr int16_t kArt_device_canary_nightlight_t7[] = {148,89,193,63,191,59,191,59,146,85,148,89};
inline constexpr int16_t kArt_device_canary_nightlight_t8[] = {146,85,191,59,189,56,189,56,144,82,146,85};
inline constexpr int16_t kArt_device_canary_nightlight_t9[] = {144,82,189,56,187,54,187,54,142,80,144,82};
inline constexpr int16_t kArt_device_canary_nightlight_t10[] = {142,80,187,54,184,52,184,52,139,78,142,80};
inline constexpr int16_t kArt_device_canary_nightlight_t11[] = {139,78,184,52,118,13,118,13,73,39,139,78};
inline constexpr int16_t kArt_device_canary_nightlight_t12[] = {118,13,70,38,73,39};
inline constexpr int16_t kArt_device_canary_nightlight_t13[] = {113,12,68,38,70,38};
inline constexpr int16_t kArt_device_canary_nightlight_t14[] = {68,200,148,242,144,82,144,82,64,40,68,200};
inline constexpr int16_t kArt_device_canary_nightlight_t15[] = {137,224,140,222,140,96,140,96,137,98,137,224};
inline constexpr int16_t kArt_device_canary_nightlight_t16[] = {131,89,134,87,78,54,78,54,74,56,131,89};
inline constexpr int16_t kArt_device_canary_nightlight_t17[] = {74,194,137,224,131,89,131,89,69,59,74,194};
inline constexpr int16_t kArt_device_canary_nightlight_t18[] = {133,98,132,99,132,220};
inline constexpr int16_t kArt_device_canary_nightlight_t19[] = {76,61,75,62,128,93};
inline constexpr int16_t kArt_device_canary_nightlight_t20[] = {75,192,132,220,128,93,128,93,71,64,75,192};
inline constexpr int16_t kArt_device_canary_nightlight_t21[] = {152,237,162,231,162,79,162,79,152,84,152,237};
inline constexpr int16_t kArt_device_canary_nightlight_t22[] = {152,237,152,84,150,83};
inline constexpr int16_t kArt_device_canary_nightlight_t23[] = {152,82,162,76,71,24,71,24,62,29,152,82};
inline constexpr int16_t kArt_device_canary_nightlight_t24[] = {152,84,152,82,62,29};
inline constexpr ArtFace kArt_device_canary_nightlight_faces[] = {
  { 0xA5A39F, 2, kArt_device_canary_nightlight_t0 },
  { 0x61615E, 1, kArt_device_canary_nightlight_t1 },
  { 0x7B5C00, 1, kArt_device_canary_nightlight_t2 },
  { 0x9C7500, 1, kArt_device_canary_nightlight_t3 },
  { 0xAB8000, 2, kArt_device_canary_nightlight_t4 },
  { 0xB88A00, 2, kArt_device_canary_nightlight_t5 },
  { 0xCF9C00, 2, kArt_device_canary_nightlight_t6 },
  { 0xDFA700, 2, kArt_device_canary_nightlight_t7 },
  { 0xE7AD00, 2, kArt_device_canary_nightlight_t8 },
  { 0xE5AC00, 2, kArt_device_canary_nightlight_t9 },
  { 0xDBA400, 2, kArt_device_canary_nightlight_t10 },
  { 0xD39E00, 2, kArt_device_canary_nightlight_t11 },
  { 0xC99700, 1, kArt_device_canary_nightlight_t12 },
  { 0xB08400, 1, kArt_device_canary_nightlight_t13 },
  { 0x654C00, 2, kArt_device_canary_nightlight_t14 },
  { 0x13161E, 2, kArt_device_canary_nightlight_t15 },
  { 0x181B25, 2, kArt_device_canary_nightlight_t16 },
  { 0x0B0D12, 2, kArt_device_canary_nightlight_t17 },
  { 0x2B4F77, 1, kArt_device_canary_nightlight_t18 },
  { 0x366294, 1, kArt_device_canary_nightlight_t19 },
  { 0x1A2F47, 2, kArt_device_canary_nightlight_t20 },
  { 0xA5A39F, 2, kArt_device_canary_nightlight_t21 },
  { 0x61615E, 1, kArt_device_canary_nightlight_t22 },
  { 0xCCCAC5, 2, kArt_device_canary_nightlight_t23 },
  { 0x61615E, 1, kArt_device_canary_nightlight_t24 },
};

inline constexpr int16_t kArt_device_canary_sense_t0[] = {165,242,201,221,201,72,201,72,165,93,165,242};
inline constexpr int16_t kArt_device_canary_sense_t1[] = {201,70,165,91,165,92};
inline constexpr int16_t kArt_device_canary_sense_t2[] = {200,69,164,90,165,91};
inline constexpr int16_t kArt_device_canary_sense_t3[] = {200,68,164,89,164,90};
inline constexpr int16_t kArt_device_canary_sense_t4[] = {199,67,163,88,164,89};
inline constexpr int16_t kArt_device_canary_sense_t5[] = {162,87,198,66,105,12,105,12,69,33,162,87};
inline constexpr int16_t kArt_device_canary_sense_t6[] = {69,190,165,242,162,87,162,87,65,35,69,190};
inline constexpr int16_t kArt_device_canary_sense_t7[] = {155,204,166,198,166,95,166,95,155,101,155,204};
inline constexpr int16_t kArt_device_canary_sense_t8[] = {150,92,160,86,70,34,70,34,60,40,150,92};
inline constexpr int16_t kArt_device_canary_sense_t9[] = {60,155,155,204,150,92,150,92,55,43,60,155};
inline constexpr int16_t kArt_device_canary_sense_t10[] = {126,115,124,115,124,158};
inline constexpr int16_t kArt_device_canary_sense_t11[] = {86,89,85,90,122,111};
inline constexpr int16_t kArt_device_canary_sense_t12[] = {85,138,124,158,122,111,122,111,82,91,85,138};
inline constexpr ArtFace kArt_device_canary_sense_faces[] = {
  { 0x6D7075, 2, kArt_device_canary_sense_t0 },
  { 0x85888E, 1, kArt_device_canary_sense_t1 },
  { 0x8F9298, 1, kArt_device_canary_sense_t2 },
  { 0x94979E, 1, kArt_device_canary_sense_t3 },
  { 0x93969D, 1, kArt_device_canary_sense_t4 },
  { 0x878A90, 2, kArt_device_canary_sense_t5 },
  { 0x414245, 2, kArt_device_canary_sense_t6 },
  { 0xA5A39F, 2, kArt_device_canary_sense_t7 },
  { 0xCCCAC5, 2, kArt_device_canary_sense_t8 },
  { 0x61615E, 2, kArt_device_canary_sense_t9 },
  { 0x99978E, 1, kArt_device_canary_sense_t10 },
  { 0xBEBAB0, 1, kArt_device_canary_sense_t11 },
  { 0x5B5954, 2, kArt_device_canary_sense_t12 },
};

inline constexpr int16_t kArt_device_canary_vision_t0[] = {150,242,185,221,185,54,185,54,150,75,150,242};
inline constexpr int16_t kArt_device_canary_vision_t1[] = {147,69,182,49,119,12,119,12,84,33,147,69};
inline constexpr int16_t kArt_device_canary_vision_t2[] = {84,207,150,242,147,69,147,69,80,35,84,207};
inline constexpr int16_t kArt_device_canary_vision_t3[] = {140,207,150,202,150,77,150,77,140,82,140,207};
inline constexpr int16_t kArt_device_canary_vision_t4[] = {135,74,145,68,85,34,85,34,76,39,135,74};
inline constexpr int16_t kArt_device_canary_vision_t5[] = {76,176,140,207,135,74,135,74,71,42,76,176};
inline constexpr ArtFace kArt_device_canary_vision_faces[] = {
  { 0x6D7075, 2, kArt_device_canary_vision_t0 },
  { 0x878A90, 2, kArt_device_canary_vision_t1 },
  { 0x414245, 2, kArt_device_canary_vision_t2 },
  { 0xA5A39F, 2, kArt_device_canary_vision_t3 },
  { 0xCCCAC5, 2, kArt_device_canary_vision_t4 },
  { 0x61615E, 2, kArt_device_canary_vision_t5 },
};

inline constexpr int16_t kArt_device_canary_vision_devkit_t0[] = {174,242,197,229,197,76,197,76,174,89,174,242};
inline constexpr int16_t kArt_device_canary_vision_devkit_t1[] = {172,84,194,71,93,12,93,12,70,26,172,84};
inline constexpr int16_t kArt_device_canary_vision_devkit_t2[] = {70,185,174,242,172,84,172,84,67,27,70,185};
inline constexpr int16_t kArt_device_canary_vision_devkit_t3[] = {166,211,174,206,174,91,174,91,166,96,166,211};
inline constexpr int16_t kArt_device_canary_vision_devkit_t4[] = {161,88,170,83,72,26,72,26,63,31,161,88};
inline constexpr int16_t kArt_device_canary_vision_devkit_t5[] = {63,157,166,211,161,88,161,88,59,34,63,157};
inline constexpr ArtFace kArt_device_canary_vision_devkit_faces[] = {
  { 0x6D7075, 2, kArt_device_canary_vision_devkit_t0 },
  { 0x878A90, 2, kArt_device_canary_vision_devkit_t1 },
  { 0x414245, 2, kArt_device_canary_vision_devkit_t2 },
  { 0xA5A39F, 2, kArt_device_canary_vision_devkit_t3 },
  { 0xCCCAC5, 2, kArt_device_canary_vision_devkit_t4 },
  { 0x61615E, 2, kArt_device_canary_vision_devkit_t5 },
};

inline constexpr int16_t kArt_device_canary_wap_t0[] = {214,205,175,228,174,230};
inline constexpr int16_t kArt_device_canary_wap_t1[] = {214,203,175,225,175,228};
inline constexpr int16_t kArt_device_canary_wap_t2[] = {175,225,214,203,214,84,214,84,175,107,175,225};
inline constexpr int16_t kArt_device_canary_wap_t3[] = {175,107,214,84,214,81,214,81,175,104,175,107};
inline constexpr int16_t kArt_device_canary_wap_t4[] = {175,104,214,81,213,78,213,78,174,100,175,104};
inline constexpr int16_t kArt_device_canary_wap_t5[] = {174,100,213,78,211,74,211,74,172,97,174,100};
inline constexpr int16_t kArt_device_canary_wap_t6[] = {172,97,211,74,209,71,209,71,170,94,172,97};
inline constexpr int16_t kArt_device_canary_wap_t7[] = {170,94,209,71,207,69,207,69,167,91,170,94};
inline constexpr int16_t kArt_device_canary_wap_t8[] = {167,91,207,69,204,67,204,67,165,90,167,91};
inline constexpr int16_t kArt_device_canary_wap_t9[] = {165,90,204,67,111,13,111,13,72,36,165,90};
inline constexpr int16_t kArt_device_canary_wap_t10[] = {109,12,69,35,72,36};
inline constexpr int16_t kArt_device_canary_wap_t11[] = {106,12,67,35,69,35};
inline constexpr int16_t kArt_device_canary_wap_t12[] = {69,176,174,230,167,91,167,91,63,37,69,176};
inline constexpr int16_t kArt_device_canary_wap_t13[] = {175,225,155,237,154,240};
inline constexpr int16_t kArt_device_canary_wap_t14[] = {155,237,175,225,175,107,175,107,155,119,155,237};
inline constexpr int16_t kArt_device_canary_wap_t15[] = {155,119,175,107,175,104,175,104,154,115,155,119};
inline constexpr int16_t kArt_device_canary_wap_t16[] = {154,115,175,104,174,100,174,100,153,112,154,115};
inline constexpr int16_t kArt_device_canary_wap_t17[] = {153,112,174,100,172,97,172,97,152,109,153,112};
inline constexpr int16_t kArt_device_canary_wap_t18[] = {152,109,172,97,170,94,170,94,150,106,152,109};
inline constexpr int16_t kArt_device_canary_wap_t19[] = {150,106,170,94,168,91,168,91,147,103,150,106};
inline constexpr int16_t kArt_device_canary_wap_t20[] = {147,103,168,91,165,89,165,89,145,101,147,103};
inline constexpr int16_t kArt_device_canary_wap_t21[] = {145,101,165,89,72,36,72,36,52,48,145,101};
inline constexpr int16_t kArt_device_canary_wap_t22[] = {72,36,49,46,52,48};
inline constexpr int16_t kArt_device_canary_wap_t23[] = {49,187,153,242,147,103,147,103,43,48,49,187};
inline constexpr ArtFace kArt_device_canary_wap_faces[] = {
  { 0x4F5054, 1, kArt_device_canary_wap_t0 },
  { 0x64666A, 1, kArt_device_canary_wap_t1 },
  { 0x6D7075, 2, kArt_device_canary_wap_t2 },
  { 0x76797E, 2, kArt_device_canary_wap_t3 },
  { 0x85888E, 2, kArt_device_canary_wap_t4 },
  { 0x8F9298, 2, kArt_device_canary_wap_t5 },
  { 0x94979E, 2, kArt_device_canary_wap_t6 },
  { 0x93969D, 2, kArt_device_canary_wap_t7 },
  { 0x8D8F96, 2, kArt_device_canary_wap_t8 },
  { 0x878A90, 2, kArt_device_canary_wap_t9 },
  { 0x818389, 1, kArt_device_canary_wap_t10 },
  { 0x717378, 1, kArt_device_canary_wap_t11 },
  { 0x414245, 2, kArt_device_canary_wap_t12 },
  { 0x969591, 1, kArt_device_canary_wap_t13 },
  { 0xA5A39F, 2, kArt_device_canary_wap_t14 },
  { 0xB2B1AC, 2, kArt_device_canary_wap_t15 },
  { 0xC8C7C2, 2, kArt_device_canary_wap_t16 },
  { 0xD8D6D0, 2, kArt_device_canary_wap_t17 },
  { 0xDFDDD7, 2, kArt_device_canary_wap_t18 },
  { 0xDEDCD6, 2, kArt_device_canary_wap_t19 },
  { 0xD4D2CD, 2, kArt_device_canary_wap_t20 },
  { 0xCCCAC5, 2, kArt_device_canary_wap_t21 },
  { 0xC2C1BC, 1, kArt_device_canary_wap_t22 },
  { 0x61615E, 2, kArt_device_canary_wap_t23 },
};

inline constexpr FigureArt kFigureArt[] = {
  { "device.canary-display-amoled241", "8c939c25", 15, kArt_device_canary_display_amoled241_faces },
  { "device.canary-display-dash", "9bb5e13f", 15, kArt_device_canary_display_dash_faces },
  { "device.canary-display-dash7", "cdff74a9", 8, kArt_device_canary_display_dash7_faces },
  { "device.canary-display-nightstand", "c361481b", 20, kArt_device_canary_display_nightstand_faces },
  { "device.canary-display-touch169", "72fa8cf1", 19, kArt_device_canary_display_touch169_faces },
  { "device.canary-display-watch", "64d11931", 31, kArt_device_canary_display_watch_faces },
  { "device.canary-nightlight", "27f621f7", 25, kArt_device_canary_nightlight_faces },
  { "device.canary-sense", "112abb6d", 13, kArt_device_canary_sense_faces },
  { "device.canary-vision", "421d34f1", 6, kArt_device_canary_vision_faces },
  { "device.canary-vision-devkit", "996e322d", 6, kArt_device_canary_vision_devkit_faces },
  { "device.canary-wap", "5fab1e20", 24, kArt_device_canary_wap_faces },
};
inline constexpr size_t kFigureArtCount =
    sizeof(kFigureArt) / sizeof(kFigureArt[0]);

// The art for a ledger figure id, or nullptr — the same honest fallback the
// lookups in fleet_figures.h keep (draw nothing rather than a guess).
inline const FigureArt* figure_art(const char* figure_id) {
  if (!figure_id || !figure_id[0]) return nullptr;
  for (size_t i = 0; i < kFigureArtCount; i++) {
    if (figure_streq(kFigureArt[i].figure_id, figure_id)) return &kFigureArt[i];
  }
  return nullptr;
}

}  // namespace canary::figures
