#pragma once
// GENERATED by canary-local/tools/figures/gen_figures.mjs — do not edit.
// Spec: docs/design/FLEET_FIGURES.md (§10, drawing the fleet on the glass).
//
// The glyph tier of each RESOLVABLE figure (every id the kFigures/kHardware
// rows in fleet_figures.h can return), as painter-ordered faces that are
// already triangulated — the same projector, camera and palette as every
// other surface, so the picture beside a witness on a display is the same
// picture the phone and the catalog draw.
//
// Geometry is quarter-units in the glyph's 64-unit box: multiply a
// coordinate by the pixel size, then divide by kFigureArtScale. Faces are
// solid physical-object colors on purpose — a Canary's case is off-white in
// every theme (the same rule FleetSolids.swift states) — so a renderer tints
// nothing and the night face simply hides the art instead of recoloring it.
//
// Pure C++, no LVGL, no Arduino, no allocation: host-testable like
// fleet_figures.h, renderer-agnostic by design.

#include <stdint.h>
#include <stddef.h>

#include "fleet_figures.h"  // figure ids + figure_streq

namespace canary::figures {

struct ArtFace {
  uint32_t rgb;             // 0xRRGGBB, the face's own physical color
  uint16_t tri_count;       // triangles in tris (tris holds tri_count * 6)
  const int16_t* tris;      // x0,y0,x1,y1,x2,y2 per triangle, quarter-units
};

struct FigureArt {
  const char* figure_id;    // the ledger id, e.g. "device.canary-sense"
  const char* rev;          // matches the figure's rev in fleet_figures.h
  uint16_t face_count;
  const ArtFace* faces;     // painter-ordered: draw first to last
};

// One denominator for every coordinate: px = coord * size_px / kFigureArtScale.
inline constexpr int kFigureArtScale = 256;

inline constexpr int16_t kArt_device_canary_display_amoled241_t0[] = {168,239,193,225,193,78,193,78,168,91,168,239};
inline constexpr int16_t kArt_device_canary_display_amoled241_t1[] = {192,75,168,89,168,91};
inline constexpr int16_t kArt_device_canary_display_amoled241_t2[] = {192,73,167,87,168,89};
inline constexpr int16_t kArt_device_canary_display_amoled241_t3[] = {167,87,192,73,191,71,191,71,166,85,167,87};
inline constexpr int16_t kArt_device_canary_display_amoled241_t4[] = {166,85,191,71,189,69,189,69,165,83,166,85};
inline constexpr int16_t kArt_device_canary_display_amoled241_t5[] = {188,67,163,81,165,83};
inline constexpr int16_t kArt_device_canary_display_amoled241_t6[] = {186,66,162,80,163,81};
inline constexpr int16_t kArt_device_canary_display_amoled241_t7[] = {162,80,186,66,94,13,94,13,70,27,162,80};
inline constexpr int16_t kArt_device_canary_display_amoled241_t8[] = {70,190,168,239,162,80,162,80,63,31,70,190};
inline constexpr int16_t kArt_device_canary_display_amoled241_t9[] = {159,233,164,231,164,95,164,95,159,97,159,233};
inline constexpr int16_t kArt_device_canary_display_amoled241_t10[] = {155,89,159,87,73,37,73,37,68,39,155,89};
inline constexpr int16_t kArt_device_canary_display_amoled241_t11[] = {68,186,159,233,155,89,155,89,63,42,68,186};
inline constexpr int16_t kArt_device_canary_display_amoled241_t12[] = {153,101,152,102,152,223};
inline constexpr int16_t kArt_device_canary_display_amoled241_t13[] = {73,51,72,51,149,96};
inline constexpr int16_t kArt_device_canary_display_amoled241_t14[] = {72,181,152,223,149,96,149,96,69,53,72,181};
inline constexpr ArtFace kArt_device_canary_display_amoled241_faces[] = {
  { 0xA5A39F, 2, kArt_device_canary_display_amoled241_t0 },
  { 0xB2B1AC, 1, kArt_device_canary_display_amoled241_t1 },
  { 0xC8C7C2, 1, kArt_device_canary_display_amoled241_t2 },
  { 0xD8D6D0, 2, kArt_device_canary_display_amoled241_t3 },
  { 0xDFDDD7, 2, kArt_device_canary_display_amoled241_t4 },
  { 0xDEDCD6, 1, kArt_device_canary_display_amoled241_t5 },
  { 0xD4D2CD, 1, kArt_device_canary_display_amoled241_t6 },
  { 0xCCCAC5, 2, kArt_device_canary_display_amoled241_t7 },
  { 0x61615E, 2, kArt_device_canary_display_amoled241_t8 },
  { 0x13161E, 2, kArt_device_canary_display_amoled241_t9 },
  { 0x181B25, 2, kArt_device_canary_display_amoled241_t10 },
  { 0x0B0D12, 2, kArt_device_canary_display_amoled241_t11 },
  { 0x2B4F77, 1, kArt_device_canary_display_amoled241_t12 },
  { 0x366294, 1, kArt_device_canary_display_amoled241_t13 },
  { 0x1A2F47, 2, kArt_device_canary_display_amoled241_t14 },
};

inline constexpr int16_t kArt_device_canary_display_dash_t0[] = {195,181,203,176,203,115,203,115,195,120,195,181};
inline constexpr int16_t kArt_device_canary_display_dash_t1[] = {191,113,199,108,101,52,101,52,93,56,191,113};
inline constexpr int16_t kArt_device_canary_display_dash_t2[] = {93,127,195,181,191,113,191,113,89,59,93,127};
inline constexpr int16_t kArt_device_canary_display_dash_t3[] = {220,226,225,223,225,113,225,113,220,115,220,226};
inline constexpr int16_t kArt_device_canary_display_dash_t4[] = {213,103,218,101,66,13,66,13,62,15,213,103};
inline constexpr int16_t kArt_device_canary_display_dash_t5[] = {62,142,220,226,213,103,213,103,55,19,62,142};
inline constexpr int16_t kArt_device_canary_display_dash_t6[] = {197,239,221,226,221,115,221,115,197,129,197,239};
inline constexpr int16_t kArt_device_canary_display_dash_t7[] = {220,113,197,126,197,129};
inline constexpr int16_t kArt_device_canary_display_dash_t8[] = {220,111,196,124,197,126};
inline constexpr int16_t kArt_device_canary_display_dash_t9[] = {196,124,220,111,218,108,218,108,195,122,196,124};
inline constexpr int16_t kArt_device_canary_display_dash_t10[] = {195,122,218,108,217,106,217,106,194,120,195,122};
inline constexpr int16_t kArt_device_canary_display_dash_t11[] = {217,106,192,118,194,120};
inline constexpr int16_t kArt_device_canary_display_dash_t12[] = {213,103,190,117,192,118};
inline constexpr int16_t kArt_device_canary_display_dash_t13[] = {190,117,213,103,62,15,62,15,38,29,190,117};
inline constexpr int16_t kArt_device_canary_display_dash_t14[] = {38,155,197,239,190,117,190,117,31,33,38,155};
inline constexpr int16_t kArt_device_canary_display_dash_t15[] = {46,47,45,47,182,126};
inline constexpr int16_t kArt_device_canary_display_dash_t16[] = {45,146,185,224,182,126,182,126,43,49,45,146};
inline constexpr int16_t kArt_device_canary_display_dash_t17[] = {49,54,48,54,178,129};
inline constexpr int16_t kArt_device_canary_display_dash_t18[] = {48,144,180,218,178,129,178,129,46,56,48,144};
inline constexpr ArtFace kArt_device_canary_display_dash_faces[] = {
  { 0x292B30, 2, kArt_device_canary_display_dash_t0 },
  { 0x33363C, 2, kArt_device_canary_display_dash_t1 },
  { 0x181A1D, 2, kArt_device_canary_display_dash_t2 },
  { 0x6D7075, 2, kArt_device_canary_display_dash_t3 },
  { 0x878A90, 2, kArt_device_canary_display_dash_t4 },
  { 0x414245, 2, kArt_device_canary_display_dash_t5 },
  { 0xA5A39F, 2, kArt_device_canary_display_dash_t6 },
  { 0xB2B1AC, 1, kArt_device_canary_display_dash_t7 },
  { 0xC8C7C2, 1, kArt_device_canary_display_dash_t8 },
  { 0xD8D6D0, 2, kArt_device_canary_display_dash_t9 },
  { 0xDFDDD7, 2, kArt_device_canary_display_dash_t10 },
  { 0xDEDCD6, 1, kArt_device_canary_display_dash_t11 },
  { 0xD4D2CD, 1, kArt_device_canary_display_dash_t12 },
  { 0xCCCAC5, 2, kArt_device_canary_display_dash_t13 },
  { 0x61615E, 2, kArt_device_canary_display_dash_t14 },
  { 0x181B25, 1, kArt_device_canary_display_dash_t15 },
  { 0x0B0D12, 2, kArt_device_canary_display_dash_t16 },
  { 0x366294, 1, kArt_device_canary_display_dash_t17 },
  { 0x1A2F47, 2, kArt_device_canary_display_dash_t18 },
};

inline constexpr int16_t kArt_device_canary_display_dash7_t0[] = {209,241,225,231,225,118,225,118,209,128,209,241};
inline constexpr int16_t kArt_device_canary_display_dash7_t1[] = {205,120,221,111,51,13,51,13,35,22,205,120};
inline constexpr int16_t kArt_device_canary_display_dash7_t2[] = {35,145,209,241,205,120,205,120,31,25,35,145};
inline constexpr int16_t kArt_device_canary_display_dash7_t3[] = {204,129,201,130,201,235};
inline constexpr int16_t kArt_device_canary_display_dash7_t4[] = {38,30,36,31,199,125};
inline constexpr int16_t kArt_device_canary_display_dash7_t5[] = {36,143,201,235,199,125,199,125,34,33,36,143};
inline constexpr int16_t kArt_device_canary_display_dash7_t6[] = {52,53,51,53,183,129};
inline constexpr int16_t kArt_device_canary_display_dash7_t7[] = {51,140,184,215,183,129,183,129,50,54,51,140};
inline constexpr ArtFace kArt_device_canary_display_dash7_faces[] = {
  { 0xA5A39F, 2, kArt_device_canary_display_dash7_t0 },
  { 0xCCCAC5, 2, kArt_device_canary_display_dash7_t1 },
  { 0x61615E, 2, kArt_device_canary_display_dash7_t2 },
  { 0x13161E, 1, kArt_device_canary_display_dash7_t3 },
  { 0x181B25, 1, kArt_device_canary_display_dash7_t4 },
  { 0x0B0D12, 2, kArt_device_canary_display_dash7_t5 },
  { 0x366294, 1, kArt_device_canary_display_dash7_t6 },
  { 0x1A2F47, 2, kArt_device_canary_display_dash7_t7 },
};

inline constexpr int16_t kArt_device_canary_display_nightstand_t0[] = {141,244,155,236,155,192,155,192,141,200,141,244};
inline constexpr int16_t kArt_device_canary_display_nightstand_t1[] = {141,200,155,192,117,170,117,170,103,178,141,200};
inline constexpr int16_t kArt_device_canary_display_nightstand_t2[] = {103,178,103,222,141,244,141,244,141,200,103,178};
inline constexpr int16_t kArt_device_canary_display_nightstand_t3[] = {180,189,154,204,154,207};
inline constexpr int16_t kArt_device_canary_display_nightstand_t4[] = {154,204,180,189,180,64,180,64,154,79,154,204};
inline constexpr int16_t kArt_device_canary_display_nightstand_t5[] = {154,79,180,64,180,61,180,61,154,76,154,79};
inline constexpr int16_t kArt_device_canary_display_nightstand_t6[] = {154,76,180,61,179,58,179,58,153,72,154,76};
inline constexpr int16_t kArt_device_canary_display_nightstand_t7[] = {153,72,179,58,177,54,177,54,151,69,153,72};
inline constexpr int16_t kArt_device_canary_display_nightstand_t8[] = {151,69,177,54,175,51,175,51,149,66,151,69};
inline constexpr int16_t kArt_device_canary_display_nightstand_t9[] = {149,66,175,51,172,49,172,49,147,64,149,66};
inline constexpr int16_t kArt_device_canary_display_nightstand_t10[] = {147,64,172,49,170,47,170,47,144,62,147,64};
inline constexpr int16_t kArt_device_canary_display_nightstand_t11[] = {144,62,170,47,112,13,112,13,86,28,144,62};
inline constexpr int16_t kArt_device_canary_display_nightstand_t12[] = {109,12,84,27,86,28};
inline constexpr int16_t kArt_device_canary_display_nightstand_t13[] = {84,174,153,209,147,64,147,64,77,29,84,174};
inline constexpr int16_t kArt_device_canary_display_nightstand_t14[] = {143,198,146,197,146,76,146,76,143,78,143,198};
inline constexpr int16_t kArt_device_canary_display_nightstand_t15[] = {138,70,141,68,90,39,90,39,87,40,138,70};
inline constexpr int16_t kArt_device_canary_display_nightstand_t16[] = {87,171,143,198,138,70,138,70,82,43,87,171};
inline constexpr int16_t kArt_device_canary_display_nightstand_t17[] = {141,81,139,82,139,191};
inline constexpr int16_t kArt_device_canary_display_nightstand_t18[] = {89,48,88,48,136,76};
inline constexpr int16_t kArt_device_canary_display_nightstand_t19[] = {88,165,139,191,136,76,136,76,85,50,88,165};
inline constexpr ArtFace kArt_device_canary_display_nightstand_faces[] = {
  { 0x292B30, 2, kArt_device_canary_display_nightstand_t0 },
  { 0x33363C, 2, kArt_device_canary_display_nightstand_t1 },
  { 0x181A1D, 2, kArt_device_canary_display_nightstand_t2 },
  { 0x969591, 1, kArt_device_canary_display_nightstand_t3 },
  { 0xA5A39F, 2, kArt_device_canary_display_nightstand_t4 },
  { 0xB2B1AC, 2, kArt_device_canary_display_nightstand_t5 },
  { 0xC8C7C2, 2, kArt_device_canary_display_nightstand_t6 },
  { 0xD8D6D0, 2, kArt_device_canary_display_nightstand_t7 },
  { 0xDFDDD7, 2, kArt_device_canary_display_nightstand_t8 },
  { 0xDEDCD6, 2, kArt_device_canary_display_nightstand_t9 },
  { 0xD4D2CD, 2, kArt_device_canary_display_nightstand_t10 },
  { 0xCCCAC5, 2, kArt_device_canary_display_nightstand_t11 },
  { 0xC2C1BC, 1, kArt_device_canary_display_nightstand_t12 },
  { 0x61615E, 2, kArt_device_canary_display_nightstand_t13 },
  { 0x13161E, 2, kArt_device_canary_display_nightstand_t14 },
  { 0x181B25, 2, kArt_device_canary_display_nightstand_t15 },
  { 0x0B0D12, 2, kArt_device_canary_display_nightstand_t16 },
  { 0x2B4F77, 1, kArt_device_canary_display_nightstand_t17 },
  { 0x366294, 1, kArt_device_canary_display_nightstand_t18 },
  { 0x1A2F47, 2, kArt_device_canary_display_nightstand_t19 },
};

inline constexpr int16_t kArt_device_canary_display_touch169_t0[] = {220,215,176,240,175,242};
inline constexpr int16_t kArt_device_canary_display_touch169_t1[] = {220,212,176,238,176,240};
inline constexpr int16_t kArt_device_canary_display_touch169_t2[] = {176,238,220,212,220,99,220,99,176,125,176,238};
inline constexpr int16_t kArt_device_canary_display_touch169_t3[] = {176,125,220,99,220,97,220,97,176,122,176,125};
inline constexpr int16_t kArt_device_canary_display_touch169_t4[] = {176,122,220,97,219,93,219,93,175,119,176,122};
inline constexpr int16_t kArt_device_canary_display_touch169_t5[] = {175,119,219,93,217,90,217,90,174,116,175,119};
inline constexpr int16_t kArt_device_canary_display_touch169_t6[] = {174,116,217,90,215,88,215,88,172,113,174,116};
inline constexpr int16_t kArt_device_canary_display_touch169_t7[] = {172,113,215,88,213,85,213,85,169,111,172,113};
inline constexpr int16_t kArt_device_canary_display_touch169_t8[] = {169,111,213,85,211,84,211,84,167,109,169,111};
inline constexpr int16_t kArt_device_canary_display_touch169_t9[] = {167,109,211,84,89,13,89,13,45,38,167,109};
inline constexpr int16_t kArt_device_canary_display_touch169_t10[] = {87,12,43,37,45,38};
inline constexpr int16_t kArt_device_canary_display_touch169_t11[] = {84,12,41,37,43,37};
inline constexpr int16_t kArt_device_canary_display_touch169_t12[] = {45,172,176,240,167,109,167,109,36,41,45,172};
inline constexpr int16_t kArt_device_canary_display_touch169_t13[] = {162,232,169,228,169,126,169,126,162,129,162,232};
inline constexpr int16_t kArt_device_canary_display_touch169_t14[] = {156,119,163,115,50,50,50,50,43,54,156,119};
inline constexpr int16_t kArt_device_canary_display_touch169_t15[] = {43,170,162,232,156,119,156,119,37,57,43,170};
inline constexpr int16_t kArt_device_canary_display_touch169_t16[] = {154,132,153,133,153,221};
inline constexpr int16_t kArt_device_canary_display_touch169_t17[] = {49,66,48,67,149,125};
inline constexpr int16_t kArt_device_canary_display_touch169_t18[] = {48,165,153,221,149,125,149,125,43,69,48,165};
inline constexpr ArtFace kArt_device_canary_display_touch169_faces[] = {
  { 0x777673, 1, kArt_device_canary_display_touch169_t0 },
  { 0x969591, 1, kArt_device_canary_display_touch169_t1 },
  { 0xA5A39F, 2, kArt_device_canary_display_touch169_t2 },
  { 0xB2B1AC, 2, kArt_device_canary_display_touch169_t3 },
  { 0xC8C7C2, 2, kArt_device_canary_display_touch169_t4 },
  { 0xD8D6D0, 2, kArt_device_canary_display_touch169_t5 },
  { 0xDFDDD7, 2, kArt_device_canary_display_touch169_t6 },
  { 0xDEDCD6, 2, kArt_device_canary_display_touch169_t7 },
  { 0xD4D2CD, 2, kArt_device_canary_display_touch169_t8 },
  { 0xCCCAC5, 2, kArt_device_canary_display_touch169_t9 },
  { 0xC2C1BC, 1, kArt_device_canary_display_touch169_t10 },
  { 0xAAA9A4, 1, kArt_device_canary_display_touch169_t11 },
  { 0x61615E, 2, kArt_device_canary_display_touch169_t12 },
  { 0x13161E, 2, kArt_device_canary_display_touch169_t13 },
  { 0x181B25, 2, kArt_device_canary_display_touch169_t14 },
  { 0x0B0D12, 2, kArt_device_canary_display_touch169_t15 },
  { 0x2B4F77, 1, kArt_device_canary_display_touch169_t16 },
  { 0x366294, 1, kArt_device_canary_display_touch169_t17 },
  { 0x1A2F47, 2, kArt_device_canary_display_touch169_t18 },
};

inline constexpr int16_t kArt_device_canary_display_watch_t0[] = {174,187,237,151,236,133,236,133,172,170,174,187};
inline constexpr int16_t kArt_device_canary_display_watch_t1[] = {172,170,236,133,232,114,232,114,168,151,172,170};
inline constexpr int16_t kArt_device_canary_display_watch_t2[] = {168,151,232,114,225,96,225,96,161,132,168,151};
inline constexpr int16_t kArt_device_canary_display_watch_t3[] = {161,132,225,96,216,77,216,77,152,114,161,132};
inline constexpr int16_t kArt_device_canary_display_watch_t4[] = {152,114,216,77,204,60,204,60,141,97,152,114};
inline constexpr int16_t kArt_device_canary_display_watch_t5[] = {141,97,204,60,192,45,192,45,128,82,141,97};
inline constexpr int16_t kArt_device_canary_display_watch_t6[] = {128,82,192,45,178,32,178,32,114,69,128,82};
inline constexpr int16_t kArt_device_canary_display_watch_t7[] = {114,69,178,32,163,22,163,22,99,59,114,69};
inline constexpr int16_t kArt_device_canary_display_watch_t8[] = {99,59,163,22,149,15,149,15,85,52,99,59};
inline constexpr int16_t kArt_device_canary_display_watch_t9[] = {85,52,149,15,135,12,135,12,71,49,85,52};
inline constexpr int16_t kArt_device_canary_display_watch_t10[] = {71,49,135,12,122,13,122,13,58,49,71,49};
inline constexpr int16_t kArt_device_canary_display_watch_t11[] = {122,13,47,53,58,49};
inline constexpr int16_t kArt_device_canary_display_watch_t12[] = {225,191,161,228,152,235};
inline constexpr int16_t kArt_device_canary_display_watch_t13[] = {161,228,225,191,232,180,232,180,168,217,161,228};
inline constexpr int16_t kArt_device_canary_display_watch_t14[] = {168,217,232,180,236,167,236,167,172,203,168,217};
inline constexpr int16_t kArt_device_canary_display_watch_t15[] = {172,203,236,167,237,151,237,151,174,187,172,203};
inline constexpr int16_t kArt_device_canary_display_watch_t16[] = {172,203,172,170,152,114,172,203,152,114,114,69,172,203,114,69,85,52,172,203,85,52,58,49,172,203,58,49,38,61,172,203,38,61,27,86,172,203,27,86,27,119,172,203,27,119,47,175,172,203,47,175,85,220,172,203,85,220,114,237,172,203,114,237,141,240,141,240,161,228,172,203};
inline constexpr int16_t kArt_device_canary_display_watch_t17[] = {167,191,174,187,173,170,173,170,166,174,167,191};
inline constexpr int16_t kArt_device_canary_display_watch_t18[] = {166,174,173,170,168,151,168,151,161,155,166,174};
inline constexpr int16_t kArt_device_canary_display_watch_t19[] = {161,155,168,151,161,132,161,132,155,136,161,155};
inline constexpr int16_t kArt_device_canary_display_watch_t20[] = {155,136,161,132,152,114,152,114,145,118,155,136};
inline constexpr int16_t kArt_device_canary_display_watch_t21[] = {145,118,152,114,141,97,141,97,134,101,145,118};
inline constexpr int16_t kArt_device_canary_display_watch_t22[] = {134,101,141,97,128,82,128,82,121,85,134,101};
inline constexpr int16_t kArt_device_canary_display_watch_t23[] = {121,85,128,82,114,69,114,69,107,73,121,85};
inline constexpr int16_t kArt_device_canary_display_watch_t24[] = {107,73,114,69,100,59,100,59,93,62,107,73};
inline constexpr int16_t kArt_device_canary_display_watch_t25[] = {93,62,100,59,85,52,85,52,78,56,93,62};
inline constexpr int16_t kArt_device_canary_display_watch_t26[] = {78,56,85,52,71,49,71,49,64,53,78,56};
inline constexpr int16_t kArt_device_canary_display_watch_t27[] = {161,221,168,217,173,203,173,203,166,207,161,221};
inline constexpr int16_t kArt_device_canary_display_watch_t28[] = {166,207,173,203,174,187,174,187,167,191,166,207};
inline constexpr int16_t kArt_device_canary_display_watch_t29[] = {166,207,166,174,145,118,166,207,145,118,107,73,166,207,107,73,78,56,166,207,78,56,52,53,166,207,52,53,31,65,166,207,31,65,20,89,166,207,20,89,20,123,166,207,20,123,40,179,166,207,40,179,78,224,166,207,78,224,107,241,166,207,107,241,134,243,134,243,155,232,166,207};
inline constexpr int16_t kArt_device_canary_display_watch_t30[] = {150,196,147,154,125,111,150,196,125,111,92,80,150,196,92,80,69,72,150,196,69,72,50,76,150,196,50,76,37,91,150,196,37,91,32,114,150,196,32,114,42,159,150,196,42,159,69,199,150,196,69,199,103,223,150,196,103,223,125,225,125,225,141,216,150,196};
inline constexpr int16_t kArt_device_canary_display_watch_t31[] = {143,192,140,154,120,116,143,192,120,116,91,88,143,192,91,88,61,82,143,192,61,82,46,90,143,192,46,90,37,119,143,192,37,119,46,158,143,192,46,158,70,195,143,192,70,195,101,216,143,192,101,216,120,218,120,218,135,209,143,192};
inline constexpr ArtFace kArt_device_canary_display_watch_faces[] = {
  { 0x74767C, 2, kArt_device_canary_display_watch_t0 },
  { 0x808388, 2, kArt_device_canary_display_watch_t1 },
  { 0x898C92, 2, kArt_device_canary_display_watch_t2 },
  { 0x909399, 2, kArt_device_canary_display_watch_t3 },
  { 0x94979D, 2, kArt_device_canary_display_watch_t4 },
  { 0x94979E, 2, kArt_device_canary_display_watch_t5 },
  { 0x91949B, 2, kArt_device_canary_display_watch_t6 },
  { 0x8B8E94, 2, kArt_device_canary_display_watch_t7 },
  { 0x83858B, 2, kArt_device_canary_display_watch_t8 },
  { 0x777A7F, 2, kArt_device_canary_display_watch_t9 },
  { 0x6A6C71, 2, kArt_device_canary_display_watch_t10 },
  { 0x5B5D61, 1, kArt_device_canary_display_watch_t11 },
  { 0x414245, 1, kArt_device_canary_display_watch_t12 },
  { 0x47484B, 2, kArt_device_canary_display_watch_t13 },
  { 0x57595D, 2, kArt_device_canary_display_watch_t14 },
  { 0x66686D, 2, kArt_device_canary_display_watch_t15 },
  { 0x414245, 12, kArt_device_canary_display_watch_t16 },
  { 0xAFADA9, 2, kArt_device_canary_display_watch_t17 },
  { 0xC1BFBA, 2, kArt_device_canary_display_watch_t18 },
  { 0xCFCDC8, 2, kArt_device_canary_display_watch_t19 },
  { 0xD9D7D2, 2, kArt_device_canary_display_watch_t20 },
  { 0xDFDDD7, 2, kArt_device_canary_display_watch_t21 },
  { 0xDFDDD7, 2, kArt_device_canary_display_watch_t22 },
  { 0xDBD9D3, 2, kArt_device_canary_display_watch_t23 },
  { 0xD2D0CB, 2, kArt_device_canary_display_watch_t24 },
  { 0xC5C3BE, 2, kArt_device_canary_display_watch_t25 },
  { 0xB4B2AE, 2, kArt_device_canary_display_watch_t26 },
  { 0x83827F, 2, kArt_device_canary_display_watch_t27 },
  { 0x9A9995, 2, kArt_device_canary_display_watch_t28 },
  { 0x61615E, 12, kArt_device_canary_display_watch_t29 },
  { 0x0B0D12, 11, kArt_device_canary_display_watch_t30 },
  { 0x1A2F47, 10, kArt_device_canary_display_watch_t31 },
};

inline constexpr int16_t kArt_device_canary_nightlight_t0[] = {64,186,73,180,73,27,73,27,64,33,64,186};
inline constexpr int16_t kArt_device_canary_nightlight_t1[] = {64,186,64,33,62,32};
inline constexpr int16_t kArt_device_canary_nightlight_t2[] = {194,214,149,240,148,242};
inline constexpr int16_t kArt_device_canary_nightlight_t3[] = {194,211,150,237,149,240};
inline constexpr int16_t kArt_device_canary_nightlight_t4[] = {150,237,194,211,194,70,194,70,150,96,150,237};
inline constexpr int16_t kArt_device_canary_nightlight_t5[] = {150,96,194,70,194,66,194,66,149,92,150,96};
inline constexpr int16_t kArt_device_canary_nightlight_t6[] = {149,92,194,66,193,63,193,63,148,89,149,92};
inline constexpr int16_t kArt_device_canary_nightlight_t7[] = {148,89,193,63,191,59,191,59,146,85,148,89};
inline constexpr int16_t kArt_device_canary_nightlight_t8[] = {146,85,191,59,189,56,189,56,144,82,146,85};
inline constexpr int16_t kArt_device_canary_nightlight_t9[] = {144,82,189,56,187,54,187,54,142,80,144,82};
inline constexpr int16_t kArt_device_canary_nightlight_t10[] = {142,80,187,54,184,52,184,52,139,78,142,80};
inline constexpr int16_t kArt_device_canary_nightlight_t11[] = {139,78,184,52,118,13,118,13,73,39,139,78};
inline constexpr int16_t kArt_device_canary_nightlight_t12[] = {118,13,70,38,73,39};
inline constexpr int16_t kArt_device_canary_nightlight_t13[] = {113,12,68,38,70,38};
inline constexpr int16_t kArt_device_canary_nightlight_t14[] = {68,200,148,242,144,82,144,82,64,40,68,200};
inline constexpr int16_t kArt_device_canary_nightlight_t15[] = {137,224,140,222,140,96,140,96,137,98,137,224};
inline constexpr int16_t kArt_device_canary_nightlight_t16[] = {131,89,134,87,78,54,78,54,74,56,131,89};
inline constexpr int16_t kArt_device_canary_nightlight_t17[] = {74,194,137,224,131,89,131,89,69,59,74,194};
inline constexpr int16_t kArt_device_canary_nightlight_t18[] = {133,98,132,99,132,220};
inline constexpr int16_t kArt_device_canary_nightlight_t19[] = {76,61,75,62,128,93};
inline constexpr int16_t kArt_device_canary_nightlight_t20[] = {75,192,132,220,128,93,128,93,71,64,75,192};
inline constexpr int16_t kArt_device_canary_nightlight_t21[] = {152,237,162,231,162,79,162,79,152,84,152,237};
inline constexpr int16_t kArt_device_canary_nightlight_t22[] = {152,237,152,84,150,83};
inline constexpr int16_t kArt_device_canary_nightlight_t23[] = {152,82,162,76,71,24,71,24,62,29,152,82};
inline constexpr int16_t kArt_device_canary_nightlight_t24[] = {152,84,152,82,62,29};
inline constexpr ArtFace kArt_device_canary_nightlight_faces[] = {
  { 0xA5A39F, 2, kArt_device_canary_nightlight_t0 },
  { 0x61615E, 1, kArt_device_canary_nightlight_t1 },
  { 0x7B5C00, 1, kArt_device_canary_nightlight_t2 },
  { 0x9C7500, 1, kArt_device_canary_nightlight_t3 },
  { 0xAB8000, 2, kArt_device_canary_nightlight_t4 },
  { 0xB88A00, 2, kArt_device_canary_nightlight_t5 },
  { 0xCF9C00, 2, kArt_device_canary_nightlight_t6 },
  { 0xDFA700, 2, kArt_device_canary_nightlight_t7 },
  { 0xE7AD00, 2, kArt_device_canary_nightlight_t8 },
  { 0xE5AC00, 2, kArt_device_canary_nightlight_t9 },
  { 0xDBA400, 2, kArt_device_canary_nightlight_t10 },
  { 0xD39E00, 2, kArt_device_canary_nightlight_t11 },
  { 0xC99700, 1, kArt_device_canary_nightlight_t12 },
  { 0xB08400, 1, kArt_device_canary_nightlight_t13 },
  { 0x654C00, 2, kArt_device_canary_nightlight_t14 },
  { 0x13161E, 2, kArt_device_canary_nightlight_t15 },
  { 0x181B25, 2, kArt_device_canary_nightlight_t16 },
  { 0x0B0D12, 2, kArt_device_canary_nightlight_t17 },
  { 0x2B4F77, 1, kArt_device_canary_nightlight_t18 },
  { 0x366294, 1, kArt_device_canary_nightlight_t19 },
  { 0x1A2F47, 2, kArt_device_canary_nightlight_t20 },
  { 0xA5A39F, 2, kArt_device_canary_nightlight_t21 },
  { 0x61615E, 1, kArt_device_canary_nightlight_t22 },
  { 0xCCCAC5, 2, kArt_device_canary_nightlight_t23 },
  { 0x61615E, 1, kArt_device_canary_nightlight_t24 },
};

inline constexpr int16_t kArt_device_canary_sense_t0[] = {163,242,196,222,196,72,196,72,163,91,163,242};
inline constexpr int16_t kArt_device_canary_sense_t1[] = {195,68,162,88,162,89};
inline constexpr int16_t kArt_device_canary_sense_t2[] = {195,67,161,87,162,88};
inline constexpr int16_t kArt_device_canary_sense_t3[] = {159,85,193,66,100,12,100,12,67,32,159,85};
inline constexpr int16_t kArt_device_canary_sense_t4[] = {67,190,163,242,159,85,159,85,63,34,67,190};
inline constexpr int16_t kArt_device_canary_sense_t5[] = {159,200,163,198,163,93,163,93,159,96,159,200};
inline constexpr int16_t kArt_device_canary_sense_t6[] = {154,86,157,84,68,33,68,33,65,35,154,86};
inline constexpr int16_t kArt_device_canary_sense_t7[] = {65,152,159,200,154,86,154,86,60,38,65,152};
inline constexpr int16_t kArt_device_canary_sense_t8[] = {130,110,129,111,129,153};
inline constexpr int16_t kArt_device_canary_sense_t9[] = {91,85,90,85,126,107};
inline constexpr int16_t kArt_device_canary_sense_t10[] = {90,134,129,153,126,107,126,107,87,87,90,134};
inline constexpr ArtFace kArt_device_canary_sense_faces[] = {
  { 0x6D7075, 2, kArt_device_canary_sense_t0 },
  { 0x8F9298, 1, kArt_device_canary_sense_t1 },
  { 0x94979E, 1, kArt_device_canary_sense_t2 },
  { 0x878A90, 2, kArt_device_canary_sense_t3 },
  { 0x414245, 2, kArt_device_canary_sense_t4 },
  { 0xA5A39F, 2, kArt_device_canary_sense_t5 },
  { 0xCCCAC5, 2, kArt_device_canary_sense_t6 },
  { 0x61615E, 2, kArt_device_canary_sense_t7 },
  { 0x99978E, 1, kArt_device_canary_sense_t8 },
  { 0xBEBAB0, 1, kArt_device_canary_sense_t9 },
  { 0x5B5954, 2, kArt_device_canary_sense_t10 },
};

inline constexpr int16_t kArt_device_canary_vision_t0[] = {147,242,181,222,181,54,181,54,147,74,147,242};
inline constexpr int16_t kArt_device_canary_vision_t1[] = {144,68,178,49,115,12,115,12,81,32,144,68};
inline constexpr int16_t kArt_device_canary_vision_t2[] = {81,207,147,242,144,68,144,68,78,34,81,207};
inline constexpr int16_t kArt_device_canary_vision_t3[] = {144,204,147,202,147,76,147,76,144,77,144,204};
inline constexpr int16_t kArt_device_canary_vision_t4[] = {139,69,142,67,83,33,83,33,80,35,139,69};
inline constexpr int16_t kArt_device_canary_vision_t5[] = {80,172,144,204,139,69,139,69,75,38,80,172};
inline constexpr ArtFace kArt_device_canary_vision_faces[] = {
  { 0x6D7075, 2, kArt_device_canary_vision_t0 },
  { 0x878A90, 2, kArt_device_canary_vision_t1 },
  { 0x414245, 2, kArt_device_canary_vision_t2 },
  { 0xA5A39F, 2, kArt_device_canary_vision_t3 },
  { 0xCCCAC5, 2, kArt_device_canary_vision_t4 },
  { 0x61615E, 2, kArt_device_canary_vision_t5 },
};

inline constexpr int16_t kArt_device_canary_vision_devkit_t0[] = {171,242,195,228,195,76,195,76,171,89,171,242};
inline constexpr int16_t kArt_device_canary_vision_devkit_t1[] = {168,84,192,71,91,12,91,12,67,26,168,84};
inline constexpr int16_t kArt_device_canary_vision_devkit_t2[] = {67,185,171,242,168,84,168,84,64,28,67,185};
inline constexpr int16_t kArt_device_canary_vision_devkit_t3[] = {168,208,171,206,171,91,171,91,168,93,168,208};
inline constexpr int16_t kArt_device_canary_vision_devkit_t4[] = {164,85,167,84,69,27,69,27,66,28,164,85};
inline constexpr int16_t kArt_device_canary_vision_devkit_t5[] = {66,154,168,208,164,85,164,85,61,31,66,154};
inline constexpr ArtFace kArt_device_canary_vision_devkit_faces[] = {
  { 0x6D7075, 2, kArt_device_canary_vision_devkit_t0 },
  { 0x878A90, 2, kArt_device_canary_vision_devkit_t1 },
  { 0x414245, 2, kArt_device_canary_vision_devkit_t2 },
  { 0xA5A39F, 2, kArt_device_canary_vision_devkit_t3 },
  { 0xCCCAC5, 2, kArt_device_canary_vision_devkit_t4 },
  { 0x61615E, 2, kArt_device_canary_vision_devkit_t5 },
};

inline constexpr int16_t kArt_device_canary_wap_t0[] = {211,210,166,236,165,238};
inline constexpr int16_t kArt_device_canary_wap_t1[] = {211,207,167,233,166,236};
inline constexpr int16_t kArt_device_canary_wap_t2[] = {167,233,211,207,211,86,211,86,167,112,167,233};
inline constexpr int16_t kArt_device_canary_wap_t3[] = {167,112,211,86,211,83,211,83,166,108,167,112};
inline constexpr int16_t kArt_device_canary_wap_t4[] = {166,108,211,83,210,79,210,79,165,105,166,108};
inline constexpr int16_t kArt_device_canary_wap_t5[] = {165,105,210,79,208,76,208,76,164,102,165,105};
inline constexpr int16_t kArt_device_canary_wap_t6[] = {164,102,208,76,206,73,206,73,162,98,164,102};
inline constexpr int16_t kArt_device_canary_wap_t7[] = {162,98,206,73,204,70,204,70,159,96,162,98};
inline constexpr int16_t kArt_device_canary_wap_t8[] = {159,96,204,70,201,68,201,68,157,94,159,96};
inline constexpr int16_t kArt_device_canary_wap_t9[] = {157,94,201,68,106,13,106,13,62,39,157,94};
inline constexpr int16_t kArt_device_canary_wap_t10[] = {104,12,59,38,62,39};
inline constexpr int16_t kArt_device_canary_wap_t11[] = {101,12,57,38,59,38};
inline constexpr int16_t kArt_device_canary_wap_t12[] = {59,182,165,238,159,96,159,96,53,40,59,182};
inline constexpr int16_t kArt_device_canary_wap_t13[] = {160,237,167,233,167,112,167,112,160,116,160,237};
inline constexpr int16_t kArt_device_canary_wap_t14[] = {160,116,167,112,167,108,167,108,160,112,160,116};
inline constexpr int16_t kArt_device_canary_wap_t15[] = {160,112,167,108,166,105,166,105,159,109,160,112};
inline constexpr int16_t kArt_device_canary_wap_t16[] = {159,109,166,105,164,102,164,102,157,106,159,109};
inline constexpr int16_t kArt_device_canary_wap_t17[] = {157,106,164,102,162,98,162,98,155,102,157,106};
inline constexpr int16_t kArt_device_canary_wap_t18[] = {155,102,162,98,159,96,159,96,152,100,155,102};
inline constexpr int16_t kArt_device_canary_wap_t19[] = {152,100,159,96,157,94,157,94,150,98,152,100};
inline constexpr int16_t kArt_device_canary_wap_t20[] = {150,98,157,94,62,39,62,39,55,43,150,98};
inline constexpr int16_t kArt_device_canary_wap_t21[] = {52,186,159,242,152,100,152,100,46,44,52,186};
inline constexpr ArtFace kArt_device_canary_wap_faces[] = {
  { 0x4F5054, 1, kArt_device_canary_wap_t0 },
  { 0x64666A, 1, kArt_device_canary_wap_t1 },
  { 0x6D7075, 2, kArt_device_canary_wap_t2 },
  { 0x76797E, 2, kArt_device_canary_wap_t3 },
  { 0x85888E, 2, kArt_device_canary_wap_t4 },
  { 0x8F9298, 2, kArt_device_canary_wap_t5 },
  { 0x94979E, 2, kArt_device_canary_wap_t6 },
  { 0x93969D, 2, kArt_device_canary_wap_t7 },
  { 0x8D8F96, 2, kArt_device_canary_wap_t8 },
  { 0x878A90, 2, kArt_device_canary_wap_t9 },
  { 0x818389, 1, kArt_device_canary_wap_t10 },
  { 0x717378, 1, kArt_device_canary_wap_t11 },
  { 0x414245, 2, kArt_device_canary_wap_t12 },
  { 0xA5A39F, 2, kArt_device_canary_wap_t13 },
  { 0xB2B1AC, 2, kArt_device_canary_wap_t14 },
  { 0xC8C7C2, 2, kArt_device_canary_wap_t15 },
  { 0xD8D6D0, 2, kArt_device_canary_wap_t16 },
  { 0xDFDDD7, 2, kArt_device_canary_wap_t17 },
  { 0xDEDCD6, 2, kArt_device_canary_wap_t18 },
  { 0xD4D2CD, 2, kArt_device_canary_wap_t19 },
  { 0xCCCAC5, 2, kArt_device_canary_wap_t20 },
  { 0x61615E, 2, kArt_device_canary_wap_t21 },
};

inline constexpr FigureArt kFigureArt[] = {
  { "device.canary-display-amoled241", "8c939c25", 15, kArt_device_canary_display_amoled241_faces },
  { "device.canary-display-dash", "f344cfc8", 19, kArt_device_canary_display_dash_faces },
  { "device.canary-display-dash7", "cdff74a9", 8, kArt_device_canary_display_dash7_faces },
  { "device.canary-display-nightstand", "c361481b", 20, kArt_device_canary_display_nightstand_faces },
  { "device.canary-display-touch169", "72fa8cf1", 19, kArt_device_canary_display_touch169_faces },
  { "device.canary-display-watch", "c673b27b", 32, kArt_device_canary_display_watch_faces },
  { "device.canary-nightlight", "27f621f7", 25, kArt_device_canary_nightlight_faces },
  { "device.canary-sense", "423b3305", 11, kArt_device_canary_sense_faces },
  { "device.canary-vision", "0d4ba02d", 6, kArt_device_canary_vision_faces },
  { "device.canary-vision-devkit", "36ad7de9", 6, kArt_device_canary_vision_devkit_faces },
  { "device.canary-wap", "85a6140a", 22, kArt_device_canary_wap_faces },
};
inline constexpr size_t kFigureArtCount =
    sizeof(kFigureArt) / sizeof(kFigureArt[0]);

// The art for a ledger figure id, or nullptr — the same honest fallback the
// lookups in fleet_figures.h keep (draw nothing rather than a guess).
inline const FigureArt* figure_art(const char* figure_id) {
  if (!figure_id || !figure_id[0]) return nullptr;
  for (size_t i = 0; i < kFigureArtCount; i++) {
    if (figure_streq(kFigureArt[i].figure_id, figure_id)) return &kFigureArt[i];
  }
  return nullptr;
}

}  // namespace canary::figures
