#pragma once
// Flavor-dispatching pin map (GENERATED by setup.sh — do not hand-edit;
// pick the flavor in flavor_select.h). Pin numbers live ONLY in the
// pins_<flavor>.h copies, which mirror firmware/boards/<board>/pins/pins.h.
#include "flavor_select.h"
#if defined(CD_BUILD_DASH) && CD_BUILD_DASH
#include "pins_dash.h"
#else
#include "pins_watch.h"
#endif
