#pragma once
// GENERATED by canary-local/tools/figures/gen_figures.mjs — do not edit.
// Spec: docs/design/FLEET_FIGURES.md
//
// A device's own answer to "what am I?", in the fleet's shared vocabulary.
// Every witness already publishes its DEVICE_TYPE in its status row; this
// table pairs that type with the id of the FIGURE of the thing it runs on
// and that figure's content revision, so a display, a phone or a watch can
// draw the correct picture of a witness it has never met — and can tell
// when the copy it cached was drawn from older CAD.
//
// Pure C++, no Arduino/JSON dependencies, no allocation: the same rules
// fleet_model.h follows, so this is host-testable and safe in an ISR-free
// hot path. Lookup is a linear scan of 8 rows.

#include <stddef.h>

namespace canary::figures {

struct FigureRef {
  const char* device_type;  // what the firmware publishes
  const char* figure_id;    // the ledger id, e.g. "device.canary-sense"
  const char* rev;          // 8 hex chars; changes when the drawing changes
  const char* confidence;   // shipping | confirmed | prototype | idea
};

inline constexpr FigureRef kFigures[] = {
  { "canary-dash", "device.canary-display-dash", "9b7ce5f7", "prototype" },
  { "canary-nightstand", "device.canary-display-watch", "64d11931", "prototype" },
  { "canary-nightstand7", "device.canary-display-watch", "64d11931", "prototype" },
  { "canary-sense", "device.canary-sense", "112abb6d", "shipping" },
  { "canary-vision", "device.canary-vision", "421d34f1", "shipping" },
  { "canary-watch", "device.canary-display-watch", "64d11931", "prototype" },
  { "canary_wap", "device.canary-wap", "5fab1e20", "shipping" },
  { "canary_wap_mobile", "device.canary-wap", "5fab1e20", "shipping" },
};
inline constexpr size_t kFigureCount = sizeof(kFigures) / sizeof(kFigures[0]);

// Exact match on the published device type; nullptr when we have no figure
// for it (an unknown witness is drawn with the generic marker, never with a
// guessed picture of the wrong product).
inline const FigureRef* figure_for(const char* device_type) {
  if (!device_type || !device_type[0]) return nullptr;
  for (size_t i = 0; i < kFigureCount; i++) {
    const char* a = kFigures[i].device_type;
    const char* b = device_type;
    while (*a && *a == *b) { a++; b++; }
    if (*a == *b) return &kFigures[i];
  }
  return nullptr;
}

}  // namespace canary::figures
