#pragma once
// GENERATED by canary-local/tools/figures/gen_figures.mjs — do not edit.
// Spec: docs/design/FLEET_FIGURES.md
//
// A device's own answer to "what am I?", in the fleet's shared vocabulary, so
// a display, a phone or a watch can draw the correct picture of a witness and
// can tell when the copy it cached was drawn from older CAD.
//
// This table is COARSE and deliberately INCOMPLETE. A device type appears
// here only when every firmware config that publishes it agrees on one
// figure; types shared by more than one board are ABSENT and figure_for()
// returns nullptr, so the caller draws its generic marker. An earlier cut
// guessed with a string match and handed the rectangular nightstand boards
// the round Watch Station drum — a wrong picture is worse than no picture.
// The unresolved types, with reasons, are in
// canary-local/devices/figures.json under device_types.unmapped.
//
// There is no exact per-build lookup, on purpose: the firmware does not
// record which physical product a build is for, and a config directory and a
// build env are each shared across different boards, so nothing on disk can
// recover it. Adding one means a build DECLARING its product id. See
// docs/design/FLEET_FIGURES.md §7.
//
// Pure C++, no Arduino/JSON dependencies, no allocation: the same rules
// fleet_model.h follows, so this is host-testable and safe in a hot path.

#include <stddef.h>

namespace canary::figures {

struct FigureRef {
  const char* device_type;  // what the firmware publishes
  const char* figure_id;    // the ledger id, e.g. "device.canary-sense"
  const char* rev;          // 8 hex chars; changes when the drawing changes
  const char* confidence;   // shipping | confirmed | prototype | idea
};

inline constexpr FigureRef kFigures[] = {
  { "canary-sense", "device.canary-sense", "112abb6d", "shipping" },
  { "canary-vision", "device.canary-vision", "421d34f1", "shipping" },
  { "canary-watch", "device.canary-display-watch", "64d11931", "prototype" },
  { "canary_wap", "device.canary-wap", "5fab1e20", "shipping" },
  { "canary_wap_mobile", "device.canary-wap", "5fab1e20", "shipping" },
};
inline constexpr size_t kFigureCount = sizeof(kFigures) / sizeof(kFigures[0]);

// Exact match on the published device type; nullptr when the type cannot be
// pinned to one board, or we have no figure for it. Draw the generic marker
// then — never a guessed picture of the wrong product.
inline const FigureRef* figure_for(const char* device_type) {
  if (!device_type || !device_type[0]) return nullptr;
  for (size_t i = 0; i < kFigureCount; i++) {
    const char* a = kFigures[i].device_type;
    const char* b = device_type;
    while (*a && *a == *b) { a++; b++; }
    if (*a == *b) return &kFigures[i];
  }
  return nullptr;
}

}  // namespace canary::figures
