#pragma once
// GENERATED by canary-local/tools/figures/gen_figures.mjs — do not edit.
// Spec: docs/design/FLEET_FIGURES.md
//
// A device's own answer to "what am I?", in the fleet's shared vocabulary, so
// a display, a phone or a watch can draw the correct picture of a witness and
// can tell when the copy it cached was drawn from older CAD.
//
// Two lookups, at two HONEST precisions — the distinction matters, because
// getting it wrong once already showed a user the wrong product:
//
//   figure_for_hardware(id)     Exact about the BOARD, and therefore about
//     the SHAPE. Keyed on the boards/<id>/pins header the build compiles
//     against, which is load-bearing (wrong pins, dead device) and therefore a
//     true statement of which physical board this is. A device asking what it
//     LOOKS LIKE should use this; pass CANARY_FIGURE_HARDWARE, which each
//     board's pins header defines.
//
//     It is NOT a product name. One board can carry several products — the 7"
//     glass is both the Dash 7 and the Nightstand 7 — and a figure's title
//     names only one of them. Rows where that happens set shared_across_products;
//     to NAME the product, ask the device type, not the board.
//
//   figure_for(device_type)     COARSE, and deliberately INCOMPLETE. This is
//     what a PEER publishes on the wire, and several types are shared by more
//     than one board — canary-dash by the 4.3" and the 7" panel, canary-
//     nightstand by the 1.47" stick and the 1.69" touch. Those are ABSENT and
//     the lookup returns nullptr, so the caller draws its generic marker.
//     A wrong picture is worse than no picture.
//
// Unresolved entries, with reasons, are in canary-local/devices/figures.json
// under device_types.unmapped and hardware.unmapped.
//
// Pure C++, no Arduino/JSON dependencies, no allocation: the same rules
// fleet_model.h follows, so this is host-testable and safe in a hot path.

#include <stddef.h>

namespace canary::figures {

struct FigureRef {
  const char* device_type;  // what the firmware publishes
  const char* figure_id;    // the ledger id, e.g. "device.canary-sense"
  const char* rev;          // 8 hex chars; changes when the drawing changes
  const char* confidence;   // shipping | confirmed | prototype | idea
};

struct HardwareRef {
  const char* hardware;     // the boards/<id>/pins header this build compiles
  const char* figure_id;
  const char* rev;
  const char* confidence;
  // true when this board carries more than one product. The drawing is right
  // for all of them; the figure's TITLE is right for one. Do not print the
  // title as this device's product name when this is set.
  bool shared_across_products;
};

// Device types that resolve to exactly one figure. Types published by more
// than one board are absent ON PURPOSE — see the note above.
inline constexpr FigureRef kFigures[] = {
  { "canary-nightlight", "device.canary-nightlight", "27f621f7", "prototype" },
  { "canary-sense", "device.canary-sense", "112abb6d", "shipping" },
  { "canary-vision", "device.canary-vision", "421d34f1", "shipping" },
  { "canary-watch", "device.canary-display-watch", "17e158d1", "prototype" },
  { "canary_wap", "device.canary-wap", "5fab1e20", "shipping" },
  { "canary_wap_mobile", "device.canary-wap", "5fab1e20", "shipping" },
};
inline constexpr size_t kFigureCount = sizeof(kFigures) / sizeof(kFigures[0]);

// One row per piece of hardware we can draw. The board is exact; see
// shared_across_products for when the product name is not.
inline constexpr HardwareRef kHardware[] = {
  { "board:seeed_xiao_esp32s3", "device.canary-wap", "5fab1e20", "shipping", false },  // 4 builds
  { "esp32-c3", "device.canary-vision-devkit", "996e322d", "shipping", false },  // 2 builds
  { "waveshare-esp32c3-lcd147", "device.canary-nightlight", "27f621f7", "prototype", false },  // 1 build
  { "waveshare-esp32s3-lcd147", "device.canary-display-nightstand", "c361481b", "prototype", false },  // 1 build
  { "waveshare-esp32s3-lcd43", "device.canary-display-dash", "9bb5e13f", "prototype", false },  // 2 builds
  { "waveshare-esp32s3-lcd7", "device.canary-display-dash7", "cdff74a9", "prototype", true },  // 2 builds — shared by canary-dash + canary-nightstand7
  { "waveshare-esp32s3-touch-lcd169", "device.canary-display-touch169", "72fa8cf1", "prototype", false },  // 1 build
  { "xiao-esp32c3", "device.canary-vision", "421d34f1", "shipping", false },  // 1 build
  { "xiao-esp32c6-mr60", "device.canary-sense", "112abb6d", "shipping", false },  // 3 builds
  { "xiao-esp32s3", "device.canary-vision", "421d34f1", "shipping", false },  // 1 build
  { "xiao-esp32s3-round", "device.canary-display-watch", "17e158d1", "prototype", false },  // 3 builds
};
inline constexpr size_t kHardwareCount = sizeof(kHardware) / sizeof(kHardware[0]);

inline bool figure_streq(const char* a, const char* b) {
  if (!a || !b) return false;
  while (*a && *a == *b) { a++; b++; }
  return *a == *b;
}

// What a PEER is, from the device type it published. nullptr when that type
// cannot be pinned to one board, or we have no figure for it.
inline const FigureRef* figure_for(const char* device_type) {
  if (!device_type || !device_type[0]) return nullptr;
  for (size_t i = 0; i < kFigureCount; i++) {
    if (figure_streq(kFigures[i].device_type, device_type)) return &kFigures[i];
  }
  return nullptr;
}

// What THIS build LOOKS LIKE. The pins header is compile-time truth, so the
// board — and the shape — are exact. Check shared_across_products before
// using the figure's title as this device's product name.
inline const HardwareRef* figure_for_hardware(const char* hardware) {
  if (!hardware || !hardware[0]) return nullptr;
  for (size_t i = 0; i < kHardwareCount; i++) {
    if (figure_streq(kHardware[i].hardware, hardware)) return &kHardware[i];
  }
  return nullptr;
}

// Sugar for the common case: the figure of the board this firmware is being
// compiled for. Boards whose pins header does not define
// CANARY_FIGURE_HARDWARE get nullptr, the same honest fallback as everywhere
// else in this header.
inline const HardwareRef* my_figure() {
#ifdef CANARY_FIGURE_HARDWARE
  return figure_for_hardware(CANARY_FIGURE_HARDWARE);
#else
  return nullptr;
#endif
}

}  // namespace canary::figures
