// gen_hatch_swift.mjs — emit the Hatchery spec (and cross-language proof
// vectors) as Swift, so the iPhone app derives exactly the name the browser
// Lab and the desktop Flasher derive.
//
// Same contract as canary-local/tools/figures/gen_figures.mjs: the output is
// GENERATED AND COMMITTED, and `--check` fails CI if the committed bytes
// drift from what this would emit today. Edit canary-local/devices/hatch.json,
// re-run this, commit both.
//
// The vectors are the point. A word list can be copied by hand and stay
// right; an ALGORITHM copied by hand goes wrong quietly, and the failure is a
// bird with two names. So this file also emits fixed fingerprint → certificate
// pairs computed by the JavaScript, and the Swift test asserts its own
// implementation reproduces them. Two languages, one answer, proven at build
// time instead of hoped for.
//
// Usage:
//   node canary-local/tools/hatchery/gen_hatch_swift.mjs          # write
//   node canary-local/tools/hatchery/gen_hatch_swift.mjs --check  # verify

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { deriveCertificate } from "./derive.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..", "..");
const specPath = join(repo, "canary-local", "devices", "hatch.json");
const outPath = join(repo, "ios", "Shared", "HatchSpec.swift");

const hatch = JSON.parse(readFileSync(specPath, "utf8"));

/** Fixed inputs — arbitrary, stable, and varied enough to exercise the
 *  title coin-flip and every list. Never regenerate these at random. */
const VECTOR_FINGERPRINTS = [
  "0000000000000000",
  "a3f7c1d2e4b58690",
  "ffffffffffffffff",
  "1234567890abcdef",
  "deadbeefcafef00d",
  "0f1e2d3c4b5a6978",
];

const swiftString = (s) =>
  '"' + String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
const swiftArray = (a, indent) =>
  a.length
    ? "[\n" + a.map((v) => `${indent}    ${swiftString(v)},`).join("\n") + `\n${indent}]`
    : "[]";

const vectors = VECTOR_FINGERPRINTS.map((fp) => {
  const cert = deriveCertificate(hatch, { fingerprint: fp });
  return { fp, name: cert.name, lineage: cert.lineage, motto: cert.motto };
});

const out = `// GENERATED by canary-local/tools/hatchery/gen_hatch_swift.mjs — do not edit.
// Source of truth: canary-local/devices/hatch.json
//
// The Hatchery's word lists, as Swift, plus proof vectors that pin this app's
// derivation to the JavaScript one the browser Lab and the desktop Flasher
// run. A Canary has ONE name on every surface because all three compute it
// from the same key with the same algorithm — see BirthCertificate.swift and
// canary-local/tools/hatchery/derive.mjs.

import Foundation

public enum HatchSpec {
    public static let ringPrefix = ${swiftString(hatch.ring_prefix || "CNRY")}
    public static let titleChance = ${typeof hatch.title_chance === "number" ? hatch.title_chance : 0.6}

    public static let titles: [String] = ${swiftArray(hatch.titles || [], "    ")}

    public static let first: [String] = ${swiftArray(hatch.first || [], "    ")}

    public static let house: [String] = ${swiftArray(hatch.house || [], "    ")}

    public static let mottoes: [String] = ${swiftArray(hatch.mottoes || [], "    ")}

    public static let ordinals: [String] = ${swiftArray(hatch.ordinals || [], "    ")}

    /// The certificate's fixed words — the kicker, the vow, the craft line.
    public static let kicker = ${swiftString((hatch.certificate || {}).kicker || "")}
    public static let intro = ${swiftString((hatch.certificate || {}).intro || "")}
    public static let craft = ${swiftString((hatch.certificate || {}).craft || "")}
    public static let foot = ${swiftString((hatch.certificate || {}).foot || "")}

    /// Fingerprint → what the JavaScript derives from it. If a Swift change
    /// breaks one of these, the same Canary would answer to two names
    /// depending on which app you asked, which is the one thing a certificate
    /// may not do.
    public struct Vector: Sendable {
        public let fingerprint: String
        public let name: String
        public let lineage: String
        public let motto: String
    }

    public static let vectors: [Vector] = [
${vectors
  .map(
    (v) =>
      `        Vector(fingerprint: ${swiftString(v.fp)},\n` +
      `               name: ${swiftString(v.name)},\n` +
      `               lineage: ${swiftString(v.lineage)},\n` +
      `               motto: ${swiftString(v.motto)}),`
  )
  .join("\n")}
    ]
}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(outPath, "utf8");
  } catch {
    console.error(`gen_hatch_swift: ${outPath} is missing — run without --check.`);
    process.exit(1);
  }
  if (current !== out) {
    console.error(
      "gen_hatch_swift: ios/Shared/HatchSpec.swift is stale.\n" +
        "  Run: node canary-local/tools/hatchery/gen_hatch_swift.mjs\n" +
        "  and commit the result alongside your hatch.json change."
    );
    process.exit(1);
  }
  console.log("gen_hatch_swift: HatchSpec.swift matches hatch.json.");
} else {
  writeFileSync(outPath, out);
  console.log(`gen_hatch_swift: wrote ${outPath} (${vectors.length} vectors).`);
}
