#!/bin/bash
#
# build_arduino.sh - Assemble firmware into Arduino-compatible sketch
#
# Usage:
#   ./build_arduino.sh canary-wap default
#   ./build_arduino.sh canary-wap mobile
#   ./build_arduino.sh canary-vision default
#
# Output:
#   build/arduino/<app-id>_<config-id>/  - Ready to open in Arduino IDE
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIRMWARE_DIR="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

usage() {
    echo "Usage: $0 <app-id> <config-id>"
    echo ""
    echo "Available configurations:"
    echo "  canary-wap default   - Full-featured WAP witness device"
    echo "  canary-wap mobile    - Power-optimized portable device"
    echo "  canary-vision default - Vision AI presence detection"
    echo ""
    echo "Example:"
    echo "  $0 canary-wap default"
    exit 1
}

# Check arguments
if [ $# -lt 2 ]; then
    usage
fi

APP_ID="$1"
CONFIG_ID="$2"

# Determine board based on app
case "$APP_ID" in
    canary-wap)
        BOARD_ID="xiao-esp32s3-sense"
        ARDUINO_BOARD="XIAO_ESP32S3"
        ;;
    canary-vision)
        BOARD_ID="esp32-c3"
        ARDUINO_BOARD="ESP32C3_DEV"
        ;;
    *)
        echo -e "${RED}Error: Unknown app-id '$APP_ID'${NC}"
        usage
        ;;
esac

# Validate paths exist
CONFIG_DIR="$FIRMWARE_DIR/configs/$APP_ID/$CONFIG_ID"
BOARD_DIR="$FIRMWARE_DIR/boards/$BOARD_ID"
COMMON_DIR="$FIRMWARE_DIR/common"
PROJECT_DIR="$FIRMWARE_DIR/projects/$APP_ID"

if [ ! -d "$CONFIG_DIR" ]; then
    echo -e "${RED}Error: Configuration not found: $CONFIG_DIR${NC}"
    exit 1
fi

if [ ! -d "$BOARD_DIR" ]; then
    echo -e "${RED}Error: Board not found: $BOARD_DIR${NC}"
    exit 1
fi

# Output directory
SKETCH_NAME="${APP_ID}_${CONFIG_ID}"
SKETCH_NAME="${SKETCH_NAME//-/_}"  # Replace hyphens with underscores
OUTPUT_DIR="$FIRMWARE_DIR/build/arduino/$SKETCH_NAME"

echo -e "${GREEN}Building Arduino sketch: $SKETCH_NAME${NC}"
echo "  App:    $APP_ID"
echo "  Config: $CONFIG_ID"
echo "  Board:  $BOARD_ID"
echo "  Output: $OUTPUT_DIR"
echo ""

# Clean and create output directory
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR/src"

# Copy board pin definitions
echo "Copying board definitions..."
mkdir -p "$OUTPUT_DIR/src/boards"
cp -r "$BOARD_DIR/pins/"* "$OUTPUT_DIR/src/boards/"

# Copy configuration
echo "Copying configuration..."
mkdir -p "$OUTPUT_DIR/src/config"
cp "$CONFIG_DIR/config.h" "$OUTPUT_DIR/src/config/"

# Copy common modules
echo "Copying common modules..."
for module in core hal witness gnss storage network bluetooth rf_presence web; do
    if [ -d "$COMMON_DIR/$module" ]; then
        mkdir -p "$OUTPUT_DIR/src/$module"
        cp "$COMMON_DIR/$module/"*.h "$OUTPUT_DIR/src/$module/" 2>/dev/null || true
        cp "$COMMON_DIR/$module/"*.cpp "$OUTPUT_DIR/src/$module/" 2>/dev/null || true
    fi
done

# Copy project source if exists
if [ -d "$PROJECT_DIR/src" ]; then
    echo "Copying project source..."
    cp "$PROJECT_DIR/src/"*.cpp "$OUTPUT_DIR/src/" 2>/dev/null || true
    cp "$PROJECT_DIR/src/"*.h "$OUTPUT_DIR/src/" 2>/dev/null || true
fi

if [ -d "$PROJECT_DIR/include" ]; then
    cp "$PROJECT_DIR/include/"*.h "$OUTPUT_DIR/src/" 2>/dev/null || true
fi

# Create the main .ino file
echo "Creating Arduino sketch..."
cat > "$OUTPUT_DIR/$SKETCH_NAME.ino" << 'SKETCH_EOF'
/**
 * @file ${SKETCH_NAME}.ino
 * @brief SecuraCV Firmware - Arduino IDE Entry Point
 *
 * This sketch was auto-generated by build_arduino.sh
 *
 * Build Configuration:
 *   App:    ${APP_ID}
 *   Config: ${CONFIG_ID}
 *   Board:  ${BOARD_ID}
 *
 * Arduino IDE Setup:
 *   1. Install ESP32 board support (espressif/arduino-esp32)
 *   2. Select board: ${ARDUINO_BOARD}
 *   3. Configure partition scheme: Default 4MB with spiffs
 *   4. Upload speed: 921600
 *
 * Required Libraries (install via Library Manager):
 *   - ArduinoJson by Benoit Blanchon
 *   - NimBLE-Arduino by h2zero (for BLE features)
 *   - TinyGPSPlus by Mikal Hart (for GPS features)
 */

// ============================================================================
// INCLUDES
// ============================================================================

// Board pin definitions
#include "src/boards/pins.h"

// Configuration
#include "src/config/config.h"

// Core modules
#include "src/core/types.h"
#include "src/core/log.h"
#include "src/core/version.h"

// HAL interfaces
#include "src/hal/hal.h"

// Feature modules (conditional compilation based on config)
#if FEATURE_SD_STORAGE
#include "src/storage/storage.h"
#endif

#if FEATURE_MESH_NETWORK
#include "src/network/mesh_network.h"
#endif

#if FEATURE_BLUETOOTH
#include "src/bluetooth/bluetooth_mgr.h"
#endif

#if FEATURE_RF_PRESENCE
#include "src/rf_presence/rf_presence.h"
#endif

#if FEATURE_HTTP_SERVER
#include "src/web/http_server.h"
#include "src/web/web_ui.h"
#endif

#if FEATURE_GNSS
#include "src/gnss/gnss_parser.h"
#endif

#include "src/witness/witness_chain.h"

// ============================================================================
// FORWARD DECLARATIONS
// ============================================================================

void app_init(void);
void app_loop(void);

// ============================================================================
// ARDUINO ENTRY POINTS
// ============================================================================

void setup() {
    // Initialize serial for debugging
    Serial.begin(115200);
    while (!Serial && millis() < 3000) {
        delay(10);
    }

    Serial.println();
    Serial.println("========================================");
    Serial.println("  SecuraCV Canary Firmware");
    Serial.printf("  Version: %s\n", FW_VERSION_STRING);
    Serial.printf("  Build: %s %s\n", __DATE__, __TIME__);
    Serial.println("========================================");
    Serial.println();

    // Initialize application
    app_init();
}

void loop() {
    app_loop();
}
SKETCH_EOF

# Substitute variables in the sketch
sed -i "s/\${SKETCH_NAME}/$SKETCH_NAME/g" "$OUTPUT_DIR/$SKETCH_NAME.ino"
sed -i "s/\${APP_ID}/$APP_ID/g" "$OUTPUT_DIR/$SKETCH_NAME.ino"
sed -i "s/\${CONFIG_ID}/$CONFIG_ID/g" "$OUTPUT_DIR/$SKETCH_NAME.ino"
sed -i "s/\${BOARD_ID}/$BOARD_ID/g" "$OUTPUT_DIR/$SKETCH_NAME.ino"
sed -i "s/\${ARDUINO_BOARD}/$ARDUINO_BOARD/g" "$OUTPUT_DIR/$SKETCH_NAME.ino"

# Create secrets template
cat > "$OUTPUT_DIR/secrets.h" << 'SECRETS_EOF'
/**
 * @file secrets.h
 * @brief WiFi and credential configuration
 *
 * IMPORTANT: Never commit this file to version control!
 *
 * Copy this file and fill in your credentials.
 */

#pragma once

// WiFi Access Point credentials (for STA mode)
#define WIFI_SSID       "your_wifi_ssid"
#define WIFI_PASSWORD   "your_wifi_password"

// MQTT Broker (if using MQTT features)
#define MQTT_HOST       "192.168.1.10"
#define MQTT_PORT       1883
#define MQTT_USER       "securacv"
#define MQTT_PASSWORD   "your_mqtt_password"

// Device identity (optional override)
// #define DEVICE_ID_OVERRIDE "my-custom-device-id"
SECRETS_EOF

# Create README for the sketch
cat > "$OUTPUT_DIR/README.md" << README_EOF
# $SKETCH_NAME

Auto-generated Arduino sketch for SecuraCV firmware.

## Configuration

- **App**: $APP_ID
- **Config**: $CONFIG_ID
- **Board**: $BOARD_ID

## Arduino IDE Setup

### 1. Install Board Support

1. Open Arduino IDE Preferences
2. Add to "Additional Board Manager URLs":
   \`\`\`
   https://espressif.github.io/arduino-esp32/package_esp32_index.json
   \`\`\`
3. Open Tools > Board > Boards Manager
4. Search for "esp32" and install "esp32 by Espressif Systems"

### 2. Select Board

- **Canary WAP**: Tools > Board > ESP32 Arduino > XIAO_ESP32S3
- **Canary Vision**: Tools > Board > ESP32 Arduino > ESP32C3 Dev Module

### 3. Configure Board Settings

For XIAO ESP32S3:
- USB CDC On Boot: Enabled
- USB Mode: Hardware CDC and JTAG
- Partition Scheme: Default 4MB with spiffs
- PSRAM: OPI PSRAM

For ESP32C3:
- USB CDC On Boot: Enabled
- Partition Scheme: Default 4MB with spiffs

### 4. Install Required Libraries

Open Tools > Manage Libraries and install:

- **ArduinoJson** by Benoit Blanchon (v6.x)
- **NimBLE-Arduino** by h2zero (for BLE features)
- **TinyGPSPlus** by Mikal Hart (for GPS features)

### 5. Configure Secrets

1. Copy \`secrets.h\` to your Arduino libraries folder, OR
2. Edit \`secrets.h\` in this sketch folder with your credentials

### 6. Build and Upload

1. Connect your device via USB
2. Select the correct port in Tools > Port
3. Click Upload

## File Structure

\`\`\`
$SKETCH_NAME/
├── $SKETCH_NAME.ino    # Main Arduino sketch
├── secrets.h           # Your credentials (edit this!)
├── README.md           # This file
└── src/
    ├── boards/         # Board pin definitions
    ├── config/         # Build configuration
    ├── core/           # Core types and utilities
    ├── hal/            # Hardware abstraction
    ├── witness/        # Witness chain
    ├── gnss/           # GPS parsing
    ├── storage/        # SD/NVS storage
    ├── network/        # Mesh networking
    ├── bluetooth/      # BLE management
    ├── rf_presence/    # RF presence detection
    └── web/            # HTTP server and UI
\`\`\`

## Troubleshooting

### Upload fails
- Check USB cable (use data cable, not charge-only)
- Hold BOOT button while clicking Upload
- Try lower upload speed (Tools > Upload Speed > 115200)

### Serial output garbled
- Set Serial Monitor to 115200 baud
- Enable "DTR/RTS" in Serial Monitor

### Module not found errors
- Ensure all required libraries are installed
- Check that board is correctly selected

## Regenerating

To regenerate this sketch with different options:

\`\`\`bash
cd firmware/scripts
./build_arduino.sh $APP_ID $CONFIG_ID
\`\`\`
README_EOF

echo ""
echo -e "${GREEN}✓ Arduino sketch created successfully!${NC}"
echo ""
echo "Next steps:"
echo "  1. Open Arduino IDE"
echo "  2. File > Open > $OUTPUT_DIR/$SKETCH_NAME.ino"
echo "  3. Edit secrets.h with your credentials"
echo "  4. Select your board and port"
echo "  5. Click Upload"
echo ""
