// canary-local/tests/catalog.test.js — the catalog manifest's contract, pinned.
//
// catalog.json is the Phase-2 stub of docs/hardware/enclosure/
// CATALOG_ARCHITECTURE.md: the 3-tier Product → Variant → Option model,
// GENERATED by canary-local/tools/gen_enclosures.py from the same sources the
// other emitters parse. These tests hold the manifest to the promises the doc
// makes so a future edit can't quietly break them:
//   · every product's scad exists in the enclosures.json scad inventory
//   · every variant is a real enclosures.json set (same id, parts on disk)
//   · the six-axis legend is present and the axes are kept distinct: `part`
//     (render selector) and mount_style (option enum) are NOT variant axes
//   · env ratings are honest — `verified` is a boolean and never true (no
//     printed case has passed field_ratings.md), matching the doc's fix
//   · options' requires/excludes reference real options on the SAME product;
//     requires_parts reference real render parts
//   · alternatives resolve to real product ids (the sideways "see also")
const { test } = require("node:test");
const assert = require("node:assert");
const { readFileSync, existsSync } = require("node:fs");
const { join } = require("node:path");

const ROOT = join(__dirname, "..");
const ENC = join(ROOT, "../docs/hardware/enclosure");

const cat = JSON.parse(readFileSync(join(ROOT, "devices/catalog.json"), "utf8"));
const enc = JSON.parse(readFileSync(join(ROOT, "devices/enclosures.json"), "utf8"));

const productIds = new Set(cat.products.map((p) => p.id));
const setsById = new Map(enc.sets.map((s) => [s.id, s]));
const scadNames = new Set(Object.keys(enc.scads));

test("manifest is the documented shape (3 tiers + six-axis legend + fit)", () => {
  assert.ok(Array.isArray(cat.products) && cat.products.length > 0, "has products");
  assert.strictEqual(cat.axes.length, 6, "six-axis legend present");
  assert.ok(cat.fit && Array.isArray(cat.fit.tiers) && cat.fit.tiers.length >= 1,
    "a shared fit tier exists");
  assert.strictEqual(cat.fit.coupon_scad, "canary_fit_coupon.scad",
    "fit is bound to the coupon");
});

test("every product's scad is real and its title/family are populated", () => {
  for (const p of cat.products) {
    assert.ok(scadNames.has(p.scad), `${p.id}: scad ${p.scad} in inventory`);
    assert.ok(p.title, `${p.id}: has a title`);
    assert.ok(p.family, `${p.id}: has a family`);
    assert.ok(["primary", "accessory"].includes(p.class), `${p.id}: class tag`);
  }
});

test("every variant is a real set with its parts on disk", () => {
  for (const p of cat.products) {
    for (const v of p.variants) {
      const s = setsById.get(v.id);
      assert.ok(s, `${p.id}: variant ${v.id} is a real set`);
      for (const part of v.parts) {
        if (part.preview_mesh) continue; // in-dev preview meshes, not committed STLs
        assert.ok(existsSync(join(ENC, part.file)),
          `${p.id}/${v.id}: ${part.file} exists`);
      }
      // A variant may override the product scad; when it does, it must be real.
      if (v.scad) assert.ok(scadNames.has(v.scad), `${p.id}/${v.id}: override scad real`);
    }
  }
});

test("the axes stay distinct: `part` and mount_style are never variant axes", () => {
  for (const p of cat.products) {
    for (const ax of p.variant_axes) {
      assert.notStrictEqual(ax.param, "part",
        `${p.id}: 'part' is the render selector, not a variant axis`);
      assert.notStrictEqual(ax.param, "mount_style",
        `${p.id}: mount_style is an option enum, not a variant axis`);
      assert.ok(Array.isArray(ax.values) && ax.values.length > 0,
        `${p.id}/${ax.param}: has enum values`);
    }
  }
});

test("env ratings are honest: verified is boolean and never true (untested)", () => {
  for (const p of cat.products) {
    if (!p.env) continue;
    assert.strictEqual(typeof p.env.verified, "boolean",
      `${p.id}: env.verified is a boolean`);
    assert.strictEqual(p.env.verified, false,
      `${p.id}: no printed case is verified — must not badge a target as achieved`);
  }
});

test("option requires/excludes/requires_parts reference real things on the product", () => {
  for (const p of cat.products) {
    const optIds = new Set(p.options.map((o) => o.id));
    const parts = new Set(p.render_parts);
    for (const o of p.options) {
      for (const r of o.requires || [])
        assert.ok(optIds.has(r), `${p.id}/${o.id}: requires ${r} is a real option`);
      for (const x of o.excludes || [])
        assert.ok(optIds.has(x), `${p.id}/${o.id}: excludes ${x} is a real option`);
      for (const rp of o.requires_parts || [])
        assert.ok(parts.has(rp), `${p.id}/${o.id}: requires_parts ${rp} is a real part`);
    }
  }
});

test("alternatives resolve to real product ids (sideways links)", () => {
  for (const p of cat.products) {
    for (const a of p.alternatives) {
      assert.ok(productIds.has(a), `${p.id}: alternative ${a} is a real product`);
      assert.notStrictEqual(a, p.id, `${p.id}: not its own alternative`);
    }
  }
});
