// canary-local/tests/figures.test.js — the figure ledger's contract, pinned.
//
// figures.json and everything beside it (the .svg pair per figure, the
// firmware header, the Swift) are GENERATED by
// canary-local/tools/figures/gen_figures.mjs from the committed CAD. These
// tests hold the system to the promises docs/design/FLEET_FIGURES.md makes,
// so a future edit can't quietly break them:
//   · one camera — every figure is projected the same way, or they stop
//     reading as one family
//   · the confidence ladder is DERIVED from evidence on disk, and the
//     evidence recorded next to each verdict actually supports it
//   · an idea can never render as a product (the honesty invariant)
//   · a figure never claims dimensions its CAD doesn't have
//   · every surface's copy is present and refers to figures that exist
//   · the whole thing is byte-reproducible, which is what makes the CI
//     drift gate meaningful
const { test } = require("node:test");
const assert = require("node:assert");
const { readFileSync, existsSync, readdirSync } = require("node:fs");
const { join } = require("node:path");

const ROOT = join(__dirname, "..");
const REPO = join(ROOT, "..");
const FIGDIR = join(ROOT, "figures");

const led = JSON.parse(readFileSync(join(ROOT, "devices/figures.json"), "utf8"));
const registry = JSON.parse(readFileSync(join(ROOT, "devices/registry.json"), "utf8"));
const byId = new Map(led.figures.map((f) => [f.id, f]));

test("the ledger is the documented shape", () => {
  assert.ok(Array.isArray(led.figures) && led.figures.length > 0, "has figures");
  assert.match(led.generated_by, /gen_figures\.mjs$/, "names its generator");
  assert.strictEqual(led.spec, "docs/design/FLEET_FIGURES.md", "points at the spec");
  assert.deepStrictEqual(led.ladder.order, ["idea", "prototype", "confirmed", "shipping"],
    "the ladder runs worst-first, and is the only status vocabulary here");
  assert.ok(led.projector.rev >= 1, "the projector carries a revision");
});

test("one camera: every figure is drawn at the same scale and viewBox", () => {
  // The whole promise of the system is that a part and the device it goes
  // into are the same picture from the same viewpoint. Different viewBoxes
  // would silently reintroduce the per-drawing drift this replaces.
  for (const f of led.figures) {
    const svg = readFileSync(join(REPO, f.svg), "utf8");
    assert.match(svg, /viewBox="0 0 256 256"/, `${f.id} full figure is 256`);
    const glyph = readFileSync(join(REPO, f.glyph), "utf8");
    assert.match(glyph, /viewBox="0 0 64 64"/, `${f.id} glyph is 64`);
  }
});

test("ids are unique, and every figure names a real device or _universal", () => {
  assert.strictEqual(byId.size, led.figures.length, "no duplicate figure ids");
  const devices = new Set(registry.devices.map((d) => d.id));
  devices.add("_universal");
  devices.add("canary-display"); // the family, for boards shared across flavors
  for (const f of led.figures) {
    assert.ok(devices.has(f.device), `${f.id} -> unknown device "${f.device}"`);
    assert.match(f.id, /^(device|part|board|tool)\./, `${f.id} has a role-prefixed id`);
    assert.strictEqual(f.id.split(".")[0], f.role === "device" ? "device" : f.role,
      `${f.id}'s prefix matches its role`);
  }
});

test("the confidence ladder is derived, and its evidence supports the verdict", () => {
  for (const f of led.figures) {
    const e = f.evidence;
    assert.ok(led.ladder.order.includes(f.confidence), `${f.id} has a ladder rung`);
    if (f.role === "board") continue; // bought modules sit outside our ladder
    if (f.confidence === "shipping") {
      assert.ok(e.committed_stls.length > 0, `${f.id} claims shipping — needs a committed STL`);
      assert.ok(e.firmware_configs.length > 0, `${f.id} claims shipping — needs a firmware config`);
      assert.ok(e.catalog_variants.some((v) => v.status === "released"),
        `${f.id} claims shipping — needs a released catalog variant`);
    }
    if (f.confidence === "idea") {
      assert.strictEqual(e.registry_kind, "concept",
        `${f.id} is an idea, so the registry must call it a concept`);
      assert.strictEqual(e.committed_stls.length, 0,
        `${f.id} is an idea but has committed CAD — it has outgrown the rung`);
    }
  }
});

test("an idea can never render as a product", () => {
  // The honesty invariant. A ghost is a dashed wireframe: no fills, no
  // shading, no contact shadow. If an idea ever picks up a fill it starts
  // looking like something you can buy, which is the exact confusion the
  // ladder exists to prevent.
  for (const f of led.figures) {
    const svg = readFileSync(join(REPO, f.svg), "utf8");
    if (f.confidence === "idea") {
      assert.ok(!/fill="#/.test(svg), `${f.id} is an idea but has solid fills`);
      assert.match(svg, /stroke-dasharray/, `${f.id} is an idea but isn't drawn dashed`);
      assert.ok(!/figure-shadow/.test(svg), `${f.id} is an idea but casts a shadow`);
    } else {
      assert.match(svg, /fill="#/, `${f.id} is built but renders as a ghost`);
    }
  }
});

test("a figure never claims dimensions its CAD doesn't have", () => {
  for (const f of led.figures) {
    assert.ok(["stl", "sketch"].includes(f.dims_source), `${f.id} declares where its mm came from`);
    if (f.dims_source === "stl") {
      assert.ok(f.traced_to.length > 0, `${f.id} traces to at least one STL`);
      for (const t of f.traced_to) {
        assert.ok(existsSync(join(REPO, "docs/hardware/enclosure", t.file)),
          `${f.id} traces to ${t.file}, which must be committed`);
      }
    } else {
      assert.deepStrictEqual(f.traced_to, [], `${f.id} is sketched, so it traces to nothing`);
    }
    for (const k of ["w", "d", "h"]) {
      assert.ok(f.envelope_mm[k] > 0, `${f.id} has a real ${k}`);
    }
  }
});

test("a single-part figure fills its part's bounding box", () => {
  // The drift guard, asserted from the outside: the generator refuses to
  // emit a figure whose massing has parted company with the STL, and this
  // proves the committed output actually went through that check.
  for (const f of led.figures) {
    if (f.dims_source !== "stl" || f.traced_to.length !== 1) continue;
    assert.ok(f.drift_guard, `${f.id} records the tolerance it was checked against`);
    const [w, , h] = f.traced_to[0].mm; // SCAD frame: x, z-depth, y-height
    const stlH = f.traced_to[0].mm[1];
    assert.ok(Math.abs(f.envelope_mm.w - w) <= f.drift_guard.plan_tol_mm,
      `${f.id} width ${f.envelope_mm.w} vs part ${w}`);
    assert.ok(Math.abs(f.envelope_mm.h - stlH) <= f.drift_guard.plan_tol_mm,
      `${f.id} height ${f.envelope_mm.h} vs part ${stlH}`);
    assert.ok(h >= 0);
  }
});

test("every figure's two SVGs exist, and no orphans are left behind", () => {
  const want = new Set();
  for (const f of led.figures) {
    want.add(`${f.id}.svg`);
    want.add(`${f.id}.glyph.svg`);
    assert.ok(existsSync(join(REPO, f.svg)), `${f.svg} exists`);
    assert.ok(existsSync(join(REPO, f.glyph)), `${f.glyph} exists`);
  }
  for (const file of readdirSync(FIGDIR)) {
    assert.ok(want.has(file), `canary-local/figures/${file} is an orphan — regenerate`);
  }
  assert.strictEqual(readdirSync(FIGDIR).length, want.size, "one pair per figure, no more");
});

test("the firmware header lets a device name its own figure", () => {
  const h = readFileSync(join(REPO, "firmware/common/core/fleet_figures.h"), "utf8");
  assert.match(h, /GENERATED by/, "says it is generated");
  assert.match(h, /namespace canary::figures/, "lands in the fleet's namespace");
  const rows = [...h.matchAll(/\{ "([^"]+)", "([^"]+)", "([0-9a-f]{8})", "([a-z]+)" \}/g)];
  assert.ok(rows.length > 0, "has at least one device type");
  for (const [, deviceType, figureId, rev, confidence] of rows) {
    const f = byId.get(figureId);
    assert.ok(f, `${deviceType} points at unknown figure ${figureId}`);
    assert.strictEqual(f.rev, rev, `${deviceType}'s rev matches the ledger`);
    assert.strictEqual(f.confidence, confidence, `${deviceType}'s confidence matches the ledger`);
    assert.strictEqual(f.role, "device",
      `${deviceType} must point at a whole device, not a ${f.role}`);
  }
  // No Arduino, no JSON, no allocation — same rules fleet_model.h follows,
  // so this stays host-testable.
  assert.ok(!/#include <Arduino|ArduinoJson|malloc|new /.test(h),
    "the header stays dependency-free");
});

test("the Swift copy carries the same figures, from the same plan", () => {
  const sw = readFileSync(join(REPO, "ios/Shared/FleetFigures.swift"), "utf8");
  assert.match(sw, /GENERATED by/, "says it is generated");
  const ids = [...sw.matchAll(/^ {2}"([^"]+)": FleetFigure\($/gm)].map((m) => m[1]);
  assert.deepStrictEqual(new Set(ids), new Set(led.figures.map((f) => f.id)),
    "the phone and the wrist know exactly the figures the ledger does");
  for (const f of led.figures) {
    assert.ok(sw.includes(`rev: "${f.rev}"`), `${f.id}'s rev crossed over`);
  }
  // The ghost rule has to hold on the wrist too, or an idea would render
  // solid on one surface and dashed on another.
  const ideas = led.figures.filter((f) => f.confidence === "idea");
  assert.ok(ideas.length > 0, "there are ideas to check");
  for (const f of ideas) {
    const block = sw.slice(sw.indexOf(`"${f.id}": FleetFigure(`));
    const end = block.indexOf("]),");
    assert.ok(!/kind: \.face/.test(block.slice(0, end)),
      `${f.id} is an idea but ships filled faces to SwiftUI`);
  }
});

test("the ledger counts what it says it counts", () => {
  for (const rung of led.ladder.order) {
    const n = led.figures.filter((f) => f.confidence === rung).length;
    assert.strictEqual(led.counts[rung], n, `counts.${rung} is right`);
  }
});

test("every concept in the registry has a figure — ideas are visible, not hidden", () => {
  // The point of the ladder is that an idea sits in the same catalog as the
  // shipping devices, drawn from the same camera, honestly marked. A concept
  // with no figure is one that quietly fell off the roadmap.
  const concepts = registry.devices.filter((d) => d.kind === "concept");
  for (const d of concepts) {
    const f = byId.get(`device.${d.id}`);
    assert.ok(f, `${d.id} is a concept with no figure — add it to CONCEPT_MASSING`);
    assert.strictEqual(f.confidence, "idea", `${d.id} renders on the idea rung`);
    assert.ok(f.sketch_note, `${d.id}'s sketch says what shape it is guessing at`);
  }
});
