// canary-local/tests/figures.test.js — the figure ledger's contract, pinned.
//
// figures.json and everything beside it (the .svg pair per figure, the
// firmware header, the Swift) are GENERATED by
// canary-local/tools/figures/gen_figures.mjs from the committed CAD. These
// tests hold the system to the promises docs/design/FLEET_FIGURES.md makes,
// so a future edit can't quietly break them:
//   · one camera — every figure is projected the same way, or they stop
//     reading as one family
//   · the confidence ladder is DERIVED from evidence on disk, and the
//     evidence recorded next to each verdict actually supports it
//   · an idea can never render as a product (the honesty invariant)
//   · a figure never claims dimensions its CAD doesn't have
//   · every surface's copy is present and refers to figures that exist
//   · the whole thing is byte-reproducible, which is what makes the CI
//     drift gate meaningful
const { test } = require("node:test");
const assert = require("node:assert");
const { readFileSync, existsSync, readdirSync } = require("node:fs");
const { join } = require("node:path");

const ROOT = join(__dirname, "..");
const REPO = join(ROOT, "..");
const FIGDIR = join(ROOT, "figures");

const led = JSON.parse(readFileSync(join(ROOT, "devices/figures.json"), "utf8"));
const registry = JSON.parse(readFileSync(join(ROOT, "devices/registry.json"), "utf8"));
const byId = new Map(led.figures.map((f) => [f.id, f]));
const led2hw = new Map(led.hardware.mapped.map((m) => [m.hardware, m]));

test("the ledger is the documented shape", () => {
  assert.ok(Array.isArray(led.figures) && led.figures.length > 0, "has figures");
  assert.match(led.generated_by, /gen_figures\.mjs$/, "names its generator");
  assert.strictEqual(led.spec, "docs/design/FLEET_FIGURES.md", "points at the spec");
  assert.deepStrictEqual(led.ladder.order, ["idea", "prototype", "confirmed", "shipping"],
    "the ladder runs worst-first, and is the only status vocabulary here");
  assert.ok(led.projector.rev >= 1, "the projector carries a revision");
});

test("one camera: every figure is drawn at the same scale and viewBox", () => {
  // The whole promise of the system is that a part and the device it goes
  // into are the same picture from the same viewpoint. Different viewBoxes
  // would silently reintroduce the per-drawing drift this replaces.
  for (const f of led.figures) {
    const svg = readFileSync(join(REPO, f.svg), "utf8");
    assert.match(svg, /viewBox="0 0 256 256"/, `${f.id} full figure is 256`);
    const glyph = readFileSync(join(REPO, f.glyph), "utf8");
    assert.match(glyph, /viewBox="0 0 64 64"/, `${f.id} glyph is 64`);
  }
});

test("ids are unique, and every figure names a real device or _universal", () => {
  assert.strictEqual(byId.size, led.figures.length, "no duplicate figure ids");
  const devices = new Set(registry.devices.map((d) => d.id));
  devices.add("_universal");
  devices.add("canary-display"); // the family, for boards shared across flavors
  for (const f of led.figures) {
    assert.ok(devices.has(f.device), `${f.id} -> unknown device "${f.device}"`);
    assert.match(f.id, /^(device|part|board|tool)\./, `${f.id} has a role-prefixed id`);
    assert.strictEqual(f.id.split(".")[0], f.role === "device" ? "device" : f.role,
      `${f.id}'s prefix matches its role`);
  }
});

test("the confidence ladder is derived, and its evidence supports the verdict", () => {
  for (const f of led.figures) {
    const e = f.evidence;
    assert.ok(led.ladder.order.includes(f.confidence), `${f.id} has a ladder rung`);
    if (f.role === "board") {
      // A board is somebody else's product, so our three proofs cannot apply.
      // What must hold is that its rung is still EARNED: only a board whose
      // exact orderable part is pinned (an MPN) and whose vendor CAD is
      // committed may claim the top rung. An earlier cut forced every board
      // to `shipping` from its role alone, asserting availability the ledger
      // could not substantiate.
      const vb = e.vendor_board;
      assert.ok(vb, `${f.id} is a board and must record what we know about the part`);
      if (f.confidence === "shipping") {
        assert.ok(vb.mpn, `${f.id} claims shipping — needs a manufacturer part number`);
        assert.ok(vb.mesh_committed, `${f.id} claims shipping — needs a committed board mesh`);
      } else {
        assert.strictEqual(f.confidence, "confirmed",
          `${f.id} is a board without full evidence, so it sits at confirmed`);
      }
      continue;
    }
    if (f.confidence === "shipping") {
      assert.ok(e.committed_stls.length > 0, `${f.id} claims shipping — needs a committed STL`);
      assert.ok(e.firmware_configs.length > 0, `${f.id} claims shipping — needs a firmware config`);
      assert.ok(e.catalog_variants.some((v) => v.status === "released"),
        `${f.id} claims shipping — needs a released catalog variant`);
    }
    if (f.confidence === "idea") {
      assert.strictEqual(e.registry_kind, "concept",
        `${f.id} is an idea, so the registry must call it a concept`);
      assert.strictEqual(e.committed_stls.length, 0,
        `${f.id} is an idea but has committed CAD — it has outgrown the rung`);
    }
  }
});

test("an idea can never render as a product", () => {
  // The honesty invariant. A ghost is a dashed wireframe: no fills, no
  // shading, no contact shadow. If an idea ever picks up a fill it starts
  // looking like something you can buy, which is the exact confusion the
  // ladder exists to prevent.
  for (const f of led.figures) {
    const svg = readFileSync(join(REPO, f.svg), "utf8");
    if (f.confidence === "idea") {
      assert.ok(!/fill="#/.test(svg), `${f.id} is an idea but has solid fills`);
      assert.match(svg, /stroke-dasharray/, `${f.id} is an idea but isn't drawn dashed`);
      assert.ok(!/figure-shadow/.test(svg), `${f.id} is an idea but casts a shadow`);
    } else {
      assert.match(svg, /fill="#/, `${f.id} is built but renders as a ghost`);
    }
  }
});

test("a figure never claims dimensions its CAD doesn't have", () => {
  for (const f of led.figures) {
    assert.ok(["stl", "board-cad", "sketch"].includes(f.dims_source),
      `${f.id} declares where its mm came from`);
    if (f.dims_source === "board-cad") {
      // Read from the committed board mesh, never retyped — same contract as
      // an STL, so a re-tessellation moves the figure with it.
      const vb = f.evidence.vendor_board;
      assert.ok(vb && vb.key, `${f.id} came from a board mesh, so it must name the board`);
      assert.ok(vb.mesh_committed, `${f.id} came from a board mesh, so that mesh must be committed`);
      continue;
    }
    if (f.dims_source === "stl") {
      assert.ok(f.traced_to.length > 0, `${f.id} traces to at least one STL`);
      for (const t of f.traced_to) {
        assert.ok(existsSync(join(REPO, "docs/hardware/enclosure", t.file)),
          `${f.id} traces to ${t.file}, which must be committed`);
      }
    } else {
      assert.deepStrictEqual(f.traced_to, [], `${f.id} is sketched, so it traces to nothing`);
    }
    for (const k of ["w", "d", "h"]) {
      assert.ok(f.envelope_mm[k] > 0, `${f.id} has a real ${k}`);
    }
  }
});

test("a board figure fills the CAD box it says it came from", () => {
  // The drift guard used to skip this path entirely, so `board.xiao` shipped
  // 22.64 x 3.66 x 19.38 while its dims_source claimed CAD measuring
  // 22.64 x 4.42 x 17.78 — short in depth, over in height. A figure that
  // names its source must match it.
  const boards = JSON.parse(readFileSync(join(ROOT, "devices/boards.json"), "utf8")).boards;
  let checked = 0;
  for (const f of led.figures) {
    if (f.dims_source !== "board-cad") continue;
    const src = boards[f.evidence.vendor_board.key];
    assert.ok(src, `${f.id} names a board that is in boards.json`);
    assert.ok(f.drift_guard, `${f.id} records the tolerance it was checked against`);
    const [w, d, h] = src.dims_mm;
    assert.ok(Math.abs(f.envelope_mm.w - w) <= f.drift_guard.plan_tol_mm,
      `${f.id} width ${f.envelope_mm.w} vs CAD ${w}`);
    assert.ok(Math.abs(f.envelope_mm.h - h) <= f.drift_guard.plan_tol_mm,
      `${f.id} height ${f.envelope_mm.h} vs CAD ${h}`);
    assert.ok(f.envelope_mm.d >= d - f.drift_guard.plan_tol_mm
      && f.envelope_mm.d - d <= f.drift_guard.depth_tol_mm,
      `${f.id} depth ${f.envelope_mm.d} vs CAD ${d}`);
    checked++;
  }
  assert.ok(checked > 0, "there are board-backed figures to check");
});

test("a single-part figure fills its part's bounding box", () => {
  // The drift guard, asserted from the outside: the generator refuses to
  // emit a figure whose massing has parted company with the STL, and this
  // proves the committed output actually went through that check.
  for (const f of led.figures) {
    if (f.dims_source !== "stl" || f.traced_to.length !== 1) continue;
    assert.ok(f.drift_guard, `${f.id} records the tolerance it was checked against`);
    const [w, , h] = f.traced_to[0].mm; // SCAD frame: x, z-depth, y-height
    const stlH = f.traced_to[0].mm[1];
    assert.ok(Math.abs(f.envelope_mm.w - w) <= f.drift_guard.plan_tol_mm,
      `${f.id} width ${f.envelope_mm.w} vs part ${w}`);
    assert.ok(Math.abs(f.envelope_mm.h - stlH) <= f.drift_guard.plan_tol_mm,
      `${f.id} height ${f.envelope_mm.h} vs part ${stlH}`);
    assert.ok(h >= 0);
  }
});

test("every figure's two SVGs exist, and no orphans are left behind", () => {
  const want = new Set();
  for (const f of led.figures) {
    want.add(`${f.id}.svg`);
    want.add(`${f.id}.glyph.svg`);
    assert.ok(existsSync(join(REPO, f.svg)), `${f.svg} exists`);
    assert.ok(existsSync(join(REPO, f.glyph)), `${f.glyph} exists`);
  }
  for (const file of readdirSync(FIGDIR)) {
    assert.ok(want.has(file), `canary-local/figures/${file} is an orphan — regenerate`);
  }
  assert.strictEqual(readdirSync(FIGDIR).length, want.size, "one pair per figure, no more");
});

test("a device type is never guessed onto the wrong hardware", () => {
  // The bug this pins: `canary-nightstand` (rectangular 1.47"/1.69" boards)
  // and `canary-nightstand7` (a 7" panel) were both matched by a regex onto
  // the round 52 mm Watch Station figure. Showing someone the wrong physical
  // device is the exact failure the figures exist to prevent, so a type that
  // cannot be pinned to ONE board is omitted and recorded, never resolved by
  // a coin flip.
  const dt = led.device_types;
  assert.ok(dt, "the ledger records how running devices resolve to figures");

  const mappedTypes = new Set(dt.mapped.map((m) => m.device_type));
  for (const u of dt.unmapped) {
    assert.ok(!mappedTypes.has(u.device_type),
      `${u.device_type} cannot be both mapped and unmapped`);
    assert.ok(u.why && u.why.length > 10, `${u.device_type} says WHY it is unresolved`);
  }
  for (const t of ["canary-nightstand", "canary-nightstand7"]) {
    assert.ok(!mappedTypes.has(t),
      `${t} must not resolve to a figure while no figure matches that hardware`);
  }
  // Every mapped type points at a real, whole-device figure.
  for (const m of dt.mapped) {
    const f = byId.get(m.figure);
    assert.ok(f, `${m.device_type} -> unknown figure ${m.figure}`);
    assert.strictEqual(f.role, "device", `${m.device_type} points at a whole device`);
  }
  // The config-level mapping is kept for auditing only, and each entry must
  // still point at a real config and a real figure.
  const seen = new Set();
  for (const fl of dt.configs_audit) {
    const key = `${fl.family}/${fl.flavor}`;
    assert.ok(!seen.has(key), `${key} appears once`);
    seen.add(key);
    assert.ok(byId.get(fl.figure), `${key} -> unknown figure ${fl.figure}`);
    assert.ok(existsSync(join(REPO, "firmware/configs", fl.family, fl.flavor, "config.h")),
      `${key} is a real firmware config`);
  }
  // A type is mappable only when every config publishing it agrees.
  const byType = new Map();
  for (const fl of dt.configs_audit) {
    if (!byType.has(fl.device_type)) byType.set(fl.device_type, new Set());
    byType.get(fl.device_type).add(fl.figure);
  }
  for (const m of dt.mapped) {
    assert.strictEqual(byType.get(m.device_type).size, 1,
      `${m.device_type} is only mapped because its configs agree`);
  }
});

test("the exact lookup is keyed on something the build already depends on", () => {
  // A config directory is not one piece of hardware: 12 build envs resolve to
  // canary-display/dash, and dash / dash-b / dash-mic compile the 4.3, 4.3B
  // and 4.3C panels between them. The boards/<id>/pins header each env
  // compiles against IS one piece of hardware, and it is load-bearing — wrong
  // pins, dead device — so it cannot quietly drift the way a decorative
  // product tag could. That is why the exact table is keyed on it.
  const hw = led.hardware;
  assert.ok(hw && Array.isArray(hw.mapped), "the ledger carries a hardware table");
  assert.match(hw.key, /pins/, "the table says what it is keyed on");

  const seen = new Set();
  for (const m of hw.mapped) {
    assert.ok(!seen.has(m.hardware), `${m.hardware} appears once`);
    seen.add(m.hardware);
    const f = byId.get(m.figure);
    assert.ok(f, `${m.hardware} -> unknown figure ${m.figure}`);
    assert.strictEqual(f.role, "device", `${m.hardware} points at a whole device`);
    assert.ok(m.builds.length > 0, `${m.hardware} is compiled by at least one build`);
    if (m.hardware.startsWith("board:")) continue;
    // The board must name itself in the header the build compiles, or
    // my_figure() returns nullptr on a device that has a figure.
    const pins = join(REPO, "firmware/boards", m.hardware, "pins/pins.h");
    assert.ok(existsSync(pins), `${m.hardware} has a pins header`);
    assert.ok(readFileSync(pins, "utf8")
      .includes(`#define CANARY_FIGURE_HARDWARE "${m.hardware}"`),
    `${m.hardware}'s pins header declares its own figure hardware id`);
  }

  // Hardware we cannot draw is listed, not silently dropped.
  for (const u of hw.unmapped) {
    assert.ok(!seen.has(u.hardware), `${u.hardware} cannot be both mapped and unmapped`);
    assert.ok(u.builds.length > 0, `${u.hardware} names the builds it covers`);
  }
  // The 4.3B panel is the case that started all this: it must never borrow
  // the plain 4.3's figure.
  const b = hw.mapped.find((m) => m.hardware === "waveshare-esp32s3-lcd43b");
  assert.strictEqual(b, undefined,
    "the 4.3B panel has no figure of its own yet, so it must not borrow the 4.3's");
});

test("a board carrying two products says so", () => {
  // Exact about the BOARD is not the same as exact about the PRODUCT. The 7"
  // glass is compiled by both canary-display-dash7 and -nightstand7, so a
  // Nightstand 7 asking my_figure() gets a figure titled "Canary Dash 7" —
  // the right shape, the wrong name. The row has to admit that, or a caller
  // printing the title would relabel the device.
  for (const m of led.hardware.mapped) {
    assert.ok(Array.isArray(m.serves), `${m.hardware} records what it serves`);
    assert.strictEqual(m.shared, m.serves.length > 1,
      `${m.hardware}'s shared flag must follow the device types it carries`);
  }
  const seven = led.hardware.mapped.find((m) => m.hardware === "waveshare-esp32s3-lcd7");
  assert.ok(seven, "the 7-inch board resolves to a figure");
  assert.ok(seven.shared, "the 7-inch board carries two products and must be flagged");
  assert.ok(seven.serves.length > 1, `expected several device types, got ${seven.serves}`);

  // And the flag has to reach the firmware, or the C++ caller can't check it.
  const h = readFileSync(join(REPO, "firmware/common/core/fleet_figures.h"), "utf8");
  assert.match(h, /bool shared_across_products/, "the header carries the flag");
  assert.ok(!/figure_for_hardware\(id\) *EXACT/.test(h),
    "the header must not claim exactness it does not have about the product");
  const row = h.split("\n").find((l) => l.includes('"waveshare-esp32s3-lcd7"'));
  assert.ok(row && /, true \}/.test(row), `the 7-inch row must set the flag: ${row}`);
});

test("nothing a figure draws falls outside the frame it declares", () => {
  // The contact shadow used to be laid out AFTER the fit, so it could land
  // outside the viewBox and be clipped — a round display shadow reached
  // y = 293.8 in a 256 box. Everything drawn has to be inside the frame.
  for (const f of led.figures) {
    for (const [path, box] of [[f.svg, 256], [f.glyph, 64]]) {
      const svg = readFileSync(join(REPO, path), "utf8");
      const nums = [...svg.matchAll(/d="([^"]+)"/g)]
        .flatMap((m) => m[1].match(/-?\d+(?:\.\d+)?/g) || [])
        .map(Number);
      assert.ok(nums.length > 0, `${path} draws something`);
      assert.ok(Math.min(...nums) >= -1, `${path} draws left/above its viewBox`);
      assert.ok(Math.max(...nums) <= box + 1, `${path} draws past its ${box} viewBox`);
    }
  }
});

test("the firmware header lets a device name its own figure", () => {
  const h = readFileSync(join(REPO, "firmware/common/core/fleet_figures.h"), "utf8");
  assert.match(h, /GENERATED by/, "says it is generated");
  assert.match(h, /namespace canary::figures/, "lands in the fleet's namespace");
  const table = (name) => {
    const body = h.slice(h.indexOf(`${name}[] = {`));
    // Hardware rows carry a trailing bool (shared_across_products); device-type
    // rows do not. Tolerate either so one helper reads both tables.
    return [...body.slice(0, body.indexOf("};"))
      .matchAll(/\{ "([^"]+)", "(device\.[^"]+)", "([0-9a-f]{8})", "([a-z]+)"(?:, (true|false))? \}/g)];
  };
  const rows = table("kFigures");
  const hwRows = table("kHardware");
  assert.ok(rows.length > 0, "has at least one device type");
  assert.strictEqual(rows.length, led.device_types.mapped.length,
    "the header carries exactly the ledger's resolvable device types");
  assert.strictEqual(hwRows.length, led.hardware.mapped.length,
    "the header carries exactly the ledger's resolvable hardware");
  assert.match(h, /figure_for_hardware/, "the exact lookup is exposed");
  assert.match(h, /CANARY_FIGURE_HARDWARE/, "a build can ask what it itself is");
  for (const [, hardware, figureId, rev] of hwRows) {
    const f = byId.get(figureId);
    assert.ok(f, `${hardware} points at unknown figure ${figureId}`);
    assert.strictEqual(f.rev, rev, `${hardware}'s rev matches the ledger`);
  }
  for (const [, deviceType, figureId, rev, confidence] of rows) {
    const f = byId.get(figureId);
    assert.ok(f, `${deviceType} points at unknown figure ${figureId}`);
    assert.strictEqual(f.rev, rev, `${deviceType}'s rev matches the ledger`);
    assert.strictEqual(f.confidence, confidence, `${deviceType}'s confidence matches the ledger`);
    assert.strictEqual(f.role, "device",
      `${deviceType} must point at a whole device, not a ${f.role}`);
  }
  // No Arduino, no JSON, no allocation — same rules fleet_model.h follows,
  // so this stays host-testable.
  assert.ok(!/#include <Arduino|ArduinoJson|malloc|new /.test(h),
    "the header stays dependency-free");
});

test("the Swift copy carries the same figures, from the same plan", () => {
  const sw = readFileSync(join(REPO, "ios/Shared/FleetFigures.swift"), "utf8");
  assert.match(sw, /GENERATED by/, "says it is generated");
  const ids = [...sw.matchAll(/^ {2}"([^"]+)": FleetFigure\($/gm)].map((m) => m[1]);
  assert.deepStrictEqual(new Set(ids), new Set(led.figures.map((f) => f.id)),
    "the phone and the wrist know exactly the figures the ledger does");
  for (const f of led.figures) {
    assert.ok(sw.includes(`rev: "${f.rev}"`), `${f.id}'s rev crossed over`);
  }
  // The ghost rule has to hold on the wrist too, or an idea would render
  // solid on one surface and dashed on another.
  const ideas = led.figures.filter((f) => f.confidence === "idea");
  assert.ok(ideas.length > 0, "there are ideas to check");
  for (const f of ideas) {
    const block = sw.slice(sw.indexOf(`"${f.id}": FleetFigure(`));
    const end = block.indexOf("]),");
    assert.ok(!/kind: \.face/.test(block.slice(0, end)),
      `${f.id} is an idea but ships filled faces to SwiftUI`);
  }
});

test("the Swift massing file carries the same fleet, ready to turn", () => {
  // FleetSolids.swift is the third Swift artifact: the mm solids behind each
  // figure, which the phone's turntable re-projects at any yaw. Its contract
  // with the ledger is the same as FleetFigures.swift's — same ids, same
  // revs — plus two of its own: every solid names a material the palette
  // defines, and the ghost verdict crosses over exactly (the honesty
  // invariant must hold at every angle, so it rides the data, not the view).
  const sw = readFileSync(join(REPO, "ios/Shared/FleetSolids.swift"), "utf8");
  assert.match(sw, /GENERATED by/, "says it is generated");

  const ids = [...sw.matchAll(/^ {2}"([^"]+)": FleetMassing\($/gm)].map((m) => m[1]);
  assert.deepStrictEqual(new Set(ids), new Set(led.figures.map((f) => f.id)),
    "the massing file knows exactly the figures the ledger does");

  const palette = new Set(
    [...sw.matchAll(/^ {4}"([a-z0-9]+)": \[[\d.]+, [\d.]+, [\d.]+\],$/gm)].map((m) => m[1]));
  assert.ok(palette.size >= 8, "the palette crossed over");
  for (const m of sw.matchAll(/material: "([a-z0-9]+)"/g)) {
    assert.ok(palette.has(m[1]), `solid names unknown material "${m[1]}"`);
  }

  for (const f of led.figures) {
    const block = sw.slice(sw.indexOf(`"${f.id}": FleetMassing(`));
    const head = block.slice(0, block.indexOf("solids:"));
    assert.ok(head.includes(`rev: "${f.rev}"`), `${f.id}'s rev crossed over`);
    assert.ok(head.includes(`ghost: ${f.confidence === "idea"}`),
      `${f.id}'s ghost verdict must match its rung`);
  }
});

test("the iPhone/Watch bridge only names figures that exist", () => {
  // FleetFigureBridge.swift is the ONE hand-written piece on the Apple side —
  // the judgment that maps a decoded DeviceType onto a figure. Swift compiles
  // on the mac runners, but a bad figure id there is a runtime nil, not a
  // build error, so it gets checked here too where it costs nothing.
  const bridge = readFileSync(join(REPO, "ios/Shared/FleetFigureBridge.swift"), "utf8");
  const named = [...bridge.matchAll(/return "(device\.[^"]+)"/g)].map((m) => m[1]);
  assert.ok(named.length > 0, "the bridge names at least one figure");
  for (const id of named) {
    assert.ok(byId.get(id), `the Apple bridge names "${id}", which is not a figure`);
    assert.strictEqual(byId.get(id).role, "device", `${id} is a whole device`);
  }
  // The display family collapses four products into one enum case, so it must
  // stay nil — the same rule the firmware table keeps for canary-dash. (The
  // nightlight once rode the same nil; its figure — the C3 pocket case — now
  // comes through the pipeline, so its case names it above.)
  assert.match(bridge, /case \.display, \.unknown: return nil/,
    "the display family must not be given a figure it would have to guess at");
  assert.match(bridge, /case \.nightlight: return "device\.canary-nightlight"/,
    "the nightlight resolves to its own figure, not a borrowed sibling shape");

  // And the rows actually draw it, or none of this reaches a user.
  const fleetView = readFileSync(join(REPO, "ios/Sources/SecuraCV/Views/FleetView.swift"), "utf8");
  assert.match(fleetView, /DeviceFigureIcon\(witness\.deviceType/,
    "the witness roster draws the device's figure");
  assert.match(fleetView, /DeviceFigureIcon\(canary\.deviceType/,
    "the discovered-device row draws it too");
});

test("the flasher picker draws a board only when it can prove which one", () => {
  // The picker is where a wrong picture costs the most: somebody is holding a
  // board and matching it against the row. So a figure appears only when the
  // catalog can point at WHY — either the pins header the build compiles (the
  // same load-bearing declaration the firmware lookup uses) or an explicit
  // declaration in the product table, checked against the ledger.
  const flash = JSON.parse(readFileSync(join(ROOT, "devices/flash.json"), "utf8"));
  const picker = JSON.parse(readFileSync(join(ROOT, "devices/figures.picker.json"), "utf8"));
  let drawn = 0;
  for (const p of flash.products) {
    const f = p.figure;
    if (!f) continue;                       // placeholder — always allowed
    drawn++;
    const led = byId.get(f.id);
    assert.ok(led, `${p.id} draws "${f.id}", which is not a figure`);
    assert.strictEqual(led.role, "device", `${p.id} draws a whole device`);
    assert.strictEqual(f.title, led.title, `${p.id}'s caption matches the ledger`);
    assert.ok(f.via, `${p.id} records how its figure was resolved`);
    assert.strictEqual(f.svg, picker.figures[f.id],
      `${p.id} carries the generated picker SVG verbatim`);
    if (f.hardware) {
      const hw = led2hw.get(f.hardware);
      assert.ok(hw, `${p.id} names hardware "${f.hardware}" that has no figure`);
      assert.strictEqual(hw.figure, f.id, `${p.id}'s hardware and figure agree`);
      assert.strictEqual(!!f.shared, !!hw.shared, `${p.id} carries the shared flag through`);
    } else {
      assert.match(f.via, /declared/, `${p.id} has no hardware, so it must say it was declared`);
    }
  }
  assert.ok(drawn > 0, "some rows draw a figure");
});

test("both flashers render the slot, and neither invents a product", () => {
  // The two flashers share no UI code (AGENTS.md rule 7), so this is the only
  // thing standing between them and drift. Both must render the slot, and
  // both must fall back to the SAME neutral placeholder — a plausible generic
  // board would be worse than nothing, because it is matchable.
  const browser = readFileSync(join(ROOT, "assets/flash.js"), "utf8");
  const desktop = readFileSync(join(REPO, "desktop/src/app.js"), "utf8");
  for (const [name, src] of [["browser", browser], ["desktop", desktop]]) {
    assert.match(src, /figureSlot\(/, `the ${name} flasher builds a figure slot`);
    assert.match(src, /placeholder/, `the ${name} flasher has a placeholder state`);
    assert.match(src, /is also (built|sold) as another product/,
      `the ${name} flasher says when one board is two products`);
  }
  for (const [name, css] of [
    ["browser", readFileSync(join(ROOT, "assets/flash.css"), "utf8")],
    ["desktop", readFileSync(join(REPO, "desktop/src/styles.css"), "utf8")],
  ]) {
    // Same fixed size in both, which is what makes the list stop reflowing as
    // figures arrive.
    assert.match(css, /width: 46px;\s*\n?\s*height: 46px|width: 46px; height: 46px/,
      `the ${name} flasher's slot is a fixed 46px`);
  }
});

test("the ledger counts what it says it counts", () => {
  for (const rung of led.ladder.order) {
    const n = led.figures.filter((f) => f.confidence === rung).length;
    assert.strictEqual(led.counts[rung], n, `counts.${rung} is right`);
  }
});

test("every concept in the registry has a figure — ideas are visible, not hidden", () => {
  // The point of the ladder is that an idea sits in the same catalog as the
  // shipping devices, drawn from the same camera, honestly marked. A concept
  // with no figure is one that quietly fell off the roadmap.
  const concepts = registry.devices.filter((d) => d.kind === "concept");
  for (const d of concepts) {
    const f = byId.get(`device.${d.id}`);
    assert.ok(f, `${d.id} is a concept with no figure — add it to CONCEPT_MASSING`);
    assert.strictEqual(f.confidence, "idea", `${d.id} renders on the idea rung`);
    assert.ok(f.sketch_note, `${d.id}'s sketch says what shape it is guessing at`);
  }
});

test("the on-glass art tier covers every id the firmware can resolve, at the same rev", () => {
  // fleet_figures_art.h is the display firmware's copy of the glyph tier —
  // pre-triangulated so an ESP32 never carries a tessellator. Its contract
  // (also pinned host-side by firmware/tests_host/test_fleet_figures_art.cpp,
  // but THIS suite is the gate canary-local.yml actually runs on a figures
  // change): every id the kFigures/kHardware lookups can return has art, at
  // the exact rev the lookup carries — a device that names itself must never
  // draw nothing, or stale art.
  const lookups = readFileSync(join(REPO, "firmware/common/core/fleet_figures.h"), "utf8");
  const art = readFileSync(join(REPO, "firmware/common/core/fleet_figures_art.h"), "utf8");

  const artRows = new Map(
    [...art.matchAll(/\{ "((?:device|part|board|tool)\.[^"]+)", "([0-9a-f]{8})", (\d+), kArt_\w+_faces \}/g)]
      .map((m) => [m[1], { rev: m[2], faces: Number(m[3]) }]),
  );
  assert.ok(artRows.size > 0, "the art table parses and is non-empty");

  const resolvable = [...lookups.matchAll(/\{ "[^"]+", "((?:device|part|board|tool)\.[^"]+)", "([0-9a-f]{8})", "(\w+)"/g)];
  assert.ok(resolvable.length > 0, "the lookup tables parse and are non-empty");
  for (const [, id, rev, confidence] of resolvable) {
    const row = artRows.get(id);
    assert.ok(row, `${id} is resolvable by the firmware but has no on-glass art`);
    assert.strictEqual(row.rev, rev, `${id}'s art rev matches its lookup rev`);
    assert.ok(row.faces > 0, `${id}'s art has faces to draw`);
    assert.notStrictEqual(confidence, "idea",
      `${id}: an idea must never be resolvable on-glass — ghosts are not drawn there`);
    // And the ledger agrees the drawing is current — three copies, one rev.
    const fig = byId.get(id);
    assert.ok(fig, `${id} exists in the ledger`);
    assert.strictEqual(fig.rev, rev, `${id}'s ledger rev matches the firmware's`);
  }

  // Geometry stays inside the declared box: coordinates are quarter-units of
  // the 64-unit glyph, so every value sits in [0, 256]. A vertex outside the
  // box would draw over a neighboring row on the glass.
  const scale = art.match(/kFigureArtScale = (\d+)/);
  assert.ok(scale && Number(scale[1]) === 256, "the art scale is the glyph's 64 * 4");
  for (const m of art.matchAll(/inline constexpr int16_t kArt_\w+_t\d+\[\] = \{([-\d,]+)\};/g)) {
    for (const v of m[1].split(",").map(Number)) {
      assert.ok(v >= 0 && v <= 256, `art coordinate ${v} escapes the 64-unit glyph box`);
    }
  }
});
