// canary-local/tests/voice_nav_probe.mjs — rot guard for the Canary Voice
// sound board's place in the site.
//
// The board (canary-local/voice/index.html) is generated from the firmware and
// content-gated by gen_voice_preview.mjs --check. THIS probe guards the other
// way it could rot: silently losing its spot in the navigation. It asserts the
// page exists, that it is the generated (not a hand-edited) artifact, and that
// it is registered in the ONE manifest every nav surface reads
// (build-line.json → htmlDocumentation), so the sitemap/room/app never miss it.
// Dependency-free (node stdlib) — no browser needed.
//
//   node canary-local/tests/voice_nav_probe.mjs

import { readFileSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const LOCAL = join(ROOT, "canary-local");
const HREF = "voice/index.html";

let fail = 0;
const check = (cond, msg) => { if (!cond) { console.error(`  FAIL: ${msg}`); fail++; } };

// 1) The page exists and is the GENERATED artifact (so nav points at the
//    rot-proof page, not a stale hand-copy).
let page = "";
try { page = readFileSync(join(LOCAL, "voice", "index.html"), "utf8"); }
catch { console.error("  FAIL: canary-local/voice/index.html is missing"); fail++; }
check(page.includes("GENERATED by canary-local/tools/gen_voice_preview.mjs"),
      "voice/index.html is the generated artifact (has the generator banner)");
check(page.includes("window.VOICE_DATA"),
      "voice/index.html carries the firmware-rendered VOICE_DATA");

// 2) It is registered in the nav manifest that feeds every surface.
const manifest = JSON.parse(readFileSync(join(LOCAL, "build-line.json"), "utf8"));
const listed = (manifest.htmlDocumentation?.groups || [])
  .flatMap((g) => g.items || [])
  .some((i) => i.href === HREF);
check(listed,
      `build-line.json htmlDocumentation must list "${HREF}" — add it back so the ` +
      `sitemap and every nav surface keep the sound board reachable`);

if (fail) {
  console.error(`voice_nav_probe: ${fail} problem(s).`);
  process.exit(1);
}
console.log("voice_nav_probe: OK — sound board present, generated, and navigable.");
