// BirthCertificateTests.swift
//
// One Canary, one name, on every surface. These tests exist because that
// promise is only as good as two independent implementations agreeing — the
// Swift below and the JavaScript in canary-local/tools/hatchery/derive.mjs
// that the browser Lab and the Mac Flasher run.
//
// The vectors are generated BY the JavaScript (gen_hatch_swift.mjs) and
// committed. If someone "cleans up" the arithmetic here, these fail, and the
// failure names the real consequence: the same bird would answer to two names
// depending on which app you asked.

import XCTest
@testable import SecuraCV

final class BirthCertificateTests: XCTestCase {

    // MARK: - the two languages agree

    func testEveryVectorFromTheJavaScriptReproducesHere() throws {
        XCTAssertFalse(HatchSpec.vectors.isEmpty, "the generator emitted no proof vectors")
        for vector in HatchSpec.vectors {
            let cert = try XCTUnwrap(
                BirthCertificateDerivation.certificate(fingerprint: vector.fingerprint),
                "no certificate for \(vector.fingerprint)")
            XCTAssertEqual(cert.name, vector.name,
                           "Swift and JavaScript disagree on the name for \(vector.fingerprint)")
            XCTAssertEqual(cert.lineage, vector.lineage, vector.fingerprint)
            XCTAssertEqual(cert.motto, vector.motto, vector.fingerprint)
        }
    }

    // MARK: - derived means stable

    func testTheSameKeyAlwaysGivesTheSameName() {
        let first = BirthCertificateDerivation.certificate(fingerprint: "a3f7c1d2e4b58690")
        let again = BirthCertificateDerivation.certificate(fingerprint: "A3F7C1D2E4B58690")
        XCTAssertEqual(first?.name, again?.name,
                       "case is presentation, not identity — the key is the same key")
        XCTAssertNotNil(first?.name)
    }

    func testDifferentKeysGiveDifferentNames() {
        // Not a uniqueness proof — a word list is finite and collisions are
        // fine — but a spreader that returned one name for everything would
        // pass every other test in this file.
        let names = Set(HatchSpec.vectors.map(\.name))
        XCTAssertGreaterThan(names.count, 1, "the seed isn't reaching the picks")
    }

    func testNoFingerprintMeansNoCertificate() {
        XCTAssertNil(BirthCertificateDerivation.certificate(fingerprint: ""),
                     "a Canary we haven't pinned a key for has no identity to render — "
                     + "inventing one is the nickname this design replaces")
        XCTAssertNil(BirthCertificateDerivation.certificate(fingerprint: "   "))
    }

    // MARK: - the parts of the certificate

    func testTheRingIdPrefersTheDevicesOwnSlug() throws {
        let withSlug = try XCTUnwrap(BirthCertificateDerivation.certificate(
            fingerprint: "a3f7c1d2e4b58690", deviceID: "canary-a3f7"))
        XCTAssertEqual(withSlug.ringId, "canary-a3f7")

        let without = try XCTUnwrap(BirthCertificateDerivation.certificate(
            fingerprint: "a3f7c1d2e4b58690"))
        XCTAssertEqual(without.ringId, "A3F7C1D2E4B58690",
                       "with no slug the fingerprint IS the identity — don't invent a code")
    }

    func testTheSpeciesIsWhatTheDeviceSaidItIs() throws {
        let cert = try XCTUnwrap(BirthCertificateDerivation.certificate(
            fingerprint: "deadbeefcafef00d", species: "Canary Watch Station"))
        XCTAssertEqual(cert.species, "Canary Watch Station")
    }

    func testTheLineageNamesTheHouseWithoutStuttering() throws {
        // "the Ever-Watchful" becomes ", Ever-Watchful" — never ", the
        // Ever-Watchful of its name, the Ever-Watchful".
        for vector in HatchSpec.vectors where vector.lineage.contains(",") {
            XCTAssertFalse(vector.lineage.contains(", the "),
                           "house article leaked into the lineage: \(vector.lineage)")
        }
    }

    // MARK: - a claimed name is checked, not believed

    func testAClaimedNameIsVerifiedAgainstTheKey() throws {
        let vector = try XCTUnwrap(HatchSpec.vectors.first)
        XCTAssertTrue(BirthCertificateDerivation.verify(claimed: vector.name,
                                                        fingerprint: vector.fingerprint))
        XCTAssertTrue(BirthCertificateDerivation.verify(claimed: "  " + vector.name.uppercased(),
                                                        fingerprint: vector.fingerprint),
                      "whitespace and case are presentation")
    }

    func testANameTheKeyDoesNotProduceFailsVerification() throws {
        let vector = try XCTUnwrap(HatchSpec.vectors.first)
        XCTAssertFalse(BirthCertificateDerivation.verify(claimed: "Sir Impostor of Nowhere",
                                                         fingerprint: vector.fingerprint),
                       "the name is a function of the key; two answers mean the thing "
                       + "answering is not the thing whose key we pinned")
        XCTAssertFalse(BirthCertificateDerivation.verify(claimed: vector.name, fingerprint: ""))
    }

    // MARK: - the generator's arithmetic

    func testTheSeedIsTheDocumentedFNVConstant() {
        // Pinned independently: FNV-1a/32 of "" is the offset basis, and of
        // "a" is the basis times the prime.
        XCTAssertEqual(BirthCertificateDerivation.fnv1a(""), 0x811c_9dc5)
        XCTAssertEqual(BirthCertificateDerivation.fnv1a("a"), 0xe40c_292c)
        XCTAssertEqual(BirthCertificateDerivation.fnv1a("foobar"), 0xbf9c_f968)
    }

    func testTheStreamStaysInRange() {
        var rng = BirthCertificateDerivation.SeededRNG(seed: "0000000000000000")
        for _ in 0..<500 {
            let value = rng.next()
            XCTAssertGreaterThanOrEqual(value, 0)
            XCTAssertLessThan(value, 1, "a value of exactly 1 would index off the end of a list")
        }
    }
}
