#!/usr/bin/env node
// canary-local/tools/gen_voice_preview.mjs
//
// Generate the Canary Voice sound preview (canary-local/voice/index.html) from
// the FIRMWARE, so it can't rot. The signature data is not transcribed by
// hand: this compiles and runs tests_host/dump_voice_score.cpp, which renders
// every signature and the volume model straight from
// firmware/.../include/canary/hal/voice_score.h, then injects that JSON into
// the hand-written UI template (canary-local/voice/template.html).
//
//   node canary-local/tools/gen_voice_preview.mjs         # write index.html
//   node canary-local/tools/gen_voice_preview.mjs --check # verify up-to-date
//
// A CI drift gate (canary-local.yml) runs this and `git diff --exit-code` on
// index.html, so any change to voice_score.h that isn't reflected fails the
// build — the same mechanism that guards the emulator dist and workshop.json.
// Output is deterministic (no timestamps / host paths), so the bytes compare.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..", "..");                       // repo root
const PROJ = join(ROOT, "firmware", "projects", "canary-display");
const INCLUDE = join(PROJ, "include");
const DUMPER = join(PROJ, "tests_host", "dump_voice_score.cpp");
const TEMPLATE = join(ROOT, "canary-local", "voice", "template.html");
const OUT = join(ROOT, "canary-local", "voice", "index.html");
const MARKER = "/* __VOICE_DATA__ */";

function build() {
  const tmp = mkdtempSync(join(tmpdir(), "voicegen-"));
  const bin = join(tmp, "dump_voice_score");
  const cxx = process.env.CXX || "g++";
  // Same flags the host tests use; -Werror so a warning in the header is caught.
  execFileSync(cxx, ["-std=c++17", "-O2", "-Wall", "-Wextra", "-Werror",
                     "-I", INCLUDE, DUMPER, "-o", bin], { stdio: ["ignore", "ignore", "inherit"] });
  const json = execFileSync(bin, { encoding: "utf8" });
  JSON.parse(json);                       // fail loud on malformed output
  const template = readFileSync(TEMPLATE, "utf8");
  if (!template.includes(MARKER)) {
    console.error(`gen_voice_preview: marker "${MARKER}" missing from template.html`);
    process.exit(2);
  }
  const injected = `window.VOICE_DATA = ${json.trim()};`;
  // Fixed banner (deterministic): no timestamp, so the drift gate compares bytes.
  const banner = "<!-- GENERATED by canary-local/tools/gen_voice_preview.mjs from "
    + "firmware/projects/canary-display/include/canary/hal/voice_score.h — do NOT edit; "
    + "edit template.html and regenerate. A CI drift gate enforces this. -->\n";
  return banner + template.replace(MARKER, injected);
}

const out = build();
const check = process.argv.includes("--check");
if (check) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* missing = stale */ }
  if (current !== out) {
    console.error("gen_voice_preview: canary-local/voice/index.html is STALE — run "
      + "`node canary-local/tools/gen_voice_preview.mjs` and commit.");
    process.exit(1);
  }
  console.log("gen_voice_preview: index.html is up to date.");
} else {
  writeFileSync(OUT, out);
  console.log(`gen_voice_preview: wrote ${OUT} (${out.length} bytes).`);
}
