// GENERATED by canary-local/tools/figures/gen_figures.mjs — do not edit.
// Spec: docs/design/FLEET_FIGURES.md
//
// The MASSING behind each fleet figure: the same mm solids iso.mjs projects
// into FleetFigures.swift, carried across so the phone can turn a figure on
// its vertical axis (FleetIsoProjector.swift) instead of being pinned to the
// one committed camera. Thumbnails keep drawing the committed faces — the
// canonical camera is the fleet's shared picture — and the turntable is
// pinned to them: FleetIsoProjectorTests re-projects these solids at the
// canonical yaw and requires the committed polygons, to the hundredth.
//
// Same vocabulary as iso.mjs: a solid is a closed outline extruded along an
// axis. `axis` "z" stands the outline up in plan; "y" faces it toward the
// viewer (a screen, a lens, a wall plate). `at` is the min corner for a
// box and the base-cap center for a cyl/disc, in mm, +X right / +Y front /
// +Z up.
//
// SecuraCV-Parity: every Apple surface that shows a device compiles this.
// (The marker lives in gen_figures.mjs's template — a marker hand-added to
// generated output survives exactly one regen.)

import Foundation

public struct FleetSolid: Sendable {
  public enum Kind: String, Sendable { case box, cyl, disc }
  public let kind: Kind
  public let material: String
  public let axis: String
  public let at: [Double]
  public let size: [Double]   // box: [w, d, h]; cyl/disc: empty (see r, h)
  public let r: Double        // box: corner radius; cyl/disc: radius
  public let h: Double        // cyl/disc: extrusion length (boxes carry size)
  public let fullDetailOnly: Bool  // dropped from glyph-size renders

  public init(kind: Kind, material: String, axis: String, at: [Double],
              size: [Double], r: Double, h: Double, fullDetailOnly: Bool) {
    self.kind = kind
    self.material = material
    self.axis = axis
    self.at = at
    self.size = size
    self.r = r
    self.h = h
    self.fullDetailOnly = fullDetailOnly
  }
}

public struct FleetMassing: Sendable {
  public let id: String
  public let rev: String      // the same content hash the figure carries
  public let ghost: Bool      // an idea renders as a dashed wireframe, always
  public let envelope: [Double]  // [w, d, h] mm, computed from the solids
  public let solids: [FleetSolid]

  public init(id: String, rev: String, ghost: Bool, envelope: [Double], solids: [FleetSolid]) {
    self.id = id
    self.rev = rev
    self.ghost = ghost
    self.envelope = envelope
    self.solids = solids
  }

  /// The named material palette, base sRGB 0–255 — the physical object's
  /// colors, deliberately not the UI theme's (a case is off-white in dark
  /// mode too). Same values as iso.mjs MATERIALS.
  public static let materials: [String: [Double]] = [
    "shell": [232, 230, 224],
    "shell2": [154, 157, 164],
    "dark": [58, 61, 68],
    "gasket": [74, 64, 82],
    "glass": [27, 31, 42],
    "lit": [61, 111, 168],
    "board": [31, 74, 56],
    "lens": [20, 24, 34],
    "metal": [184, 188, 196],
    "accent": [240, 180, 0],
    "radome": [216, 212, 200],
  ]

  /// The one light rig, normalized, with its ambient/diffuse split — carried
  /// as data so a Swift render shades with these exact numbers.
  public static let light: [Double] = [0.5008521736595763, -0.3505965215617034, 0.7913464343821306]
  public static let ambient: Double = 0.42
  public static let diffuse: Double = 0.58

  public static let all: [String: FleetMassing] = [
  "board.grove-vision-ai-v2": FleetMassing(
    id: "board.grove-vision-ai-v2", rev: "8c924aa8", ghost: false,
    envelope: [22.48, 4.46, 17.78],
    solids: [
      FleetSolid(kind: .box, material: "board", axis: "y", at: [0, 0, 0], size: [22.48, 1.5164000000000002, 17.78], r: 1, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "dark", axis: "y", at: [6.744, 1.5164000000000002, 4.445], size: [8.992, 2.9436, 8.89], r: 0.4, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "metal", axis: "y", at: [2, 1.5164000000000002, 14.580000000000002], size: [18.48, 2.007, 3.2], r: 0.4, h: 0, fullDetailOnly: true),
  ]),
  "board.mr60bha2": FleetMassing(
    id: "board.mr60bha2", rev: "e0f22290", ghost: false,
    envelope: [24, 3.2, 24],
    solids: [
      FleetSolid(kind: .box, material: "board", axis: "y", at: [0, 0, 0], size: [24, 1.2800000000000002, 24], r: 1, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "metal", axis: "y", at: [4.32, 1.2800000000000002, 4.32], size: [15.36, 1.92, 15.36], r: 0.3, h: 0, fullDetailOnly: false),
  ]),
  "board.round-display": FleetMassing(
    id: "board.round-display", rev: "3e2f04e9", ghost: false,
    envelope: [43, 10, 43],
    solids: [
      FleetSolid(kind: .cyl, material: "board", axis: "y", at: [21.5, 0, 21.5], size: [], r: 21.5, h: 7, fullDetailOnly: false),
      FleetSolid(kind: .cyl, material: "glass", axis: "y", at: [21.5, 7, 21.5], size: [], r: 20.9, h: 2.6, fullDetailOnly: false),
      FleetSolid(kind: .cyl, material: "lit", axis: "y", at: [21.5, 9.6, 21.5], size: [], r: 19.1, h: 0.4, fullDetailOnly: false),
  ]),
  "board.xiao": FleetMassing(
    id: "board.xiao", rev: "987b6a44", ghost: false,
    envelope: [22.64, 4.42, 17.78],
    solids: [
      FleetSolid(kind: .box, material: "board", axis: "y", at: [0, 0, 0], size: [22.64, 1.5028000000000001, 17.78], r: 1, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "metal", axis: "y", at: [6.339200000000001, 1.5028000000000001, 3.5560000000000005], size: [9.9616, 2.9172000000000002, 10.668000000000001], r: 0.4, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "metal", axis: "y", at: [6.92, 1.5028000000000001, 0], size: [8.8, 1.989, 3.2], r: 0.6, h: 0, fullDetailOnly: true),
  ]),
  "device.canary-chore": FleetMassing(
    id: "device.canary-chore", rev: "9ac17b93", ghost: true,
    envelope: [34, 14, 34],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [34, 14, 34], r: 6.12, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-clime": FleetMassing(
    id: "device.canary-clime", rev: "a3438690", ghost: true,
    envelope: [56, 26, 56],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [56, 26, 56], r: 10.08, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-curbwatch": FleetMassing(
    id: "device.canary-curbwatch", rev: "58cf33d3", ghost: true,
    envelope: [96, 52, 120],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [96, 52, 120], r: 17.28, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-amoled241": FleetMassing(
    id: "device.canary-display-amoled241", rev: "8c939c25", ghost: false,
    envelope: [46, 13, 62],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [46, 10.6, 62], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [2, 10.6, 3.2], size: [42, 2, 55.6], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [4.65, 12.6, 6.5], size: [36.7, 0.4, 49], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-dash": FleetMassing(
    id: "device.canary-display-dash", rev: "9bb5e13f", ghost: false,
    envelope: [118, 38.9, 79],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [118, 27.229999999999997, 79], r: 4, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [3, 27.229999999999997, 3], size: [112, 11.27, 73], r: 2.5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [6.5, 38.5, 6.5], size: [105, 0.4, 66], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-dash7": FleetMassing(
    id: "device.canary-display-dash7", rev: "cdff74a9", ghost: false,
    envelope: [204.96, 22, 122.76],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [204.96, 19, 122.76], r: 5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [6, 19, 6], size: [192.96, 2.6, 110.76], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [25, 21.6, 18], size: [154.88, 0.4, 86.72], r: 2, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-nightstand": FleetMassing(
    id: "device.canary-display-nightstand", rev: "c361481b", ghost: false,
    envelope: [24.92, 9.2, 53.17],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [24.92, 8.2, 40.97], r: 3.2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "dark", axis: "y", at: [6.460000000000001, 1.4999999999999991, -12.2], size: [12, 4.5, 12.25], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [2.7650000000000006, 8.2, 2.344999999999999], size: [19.39, 0.9, 36.28], r: 1.5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [3.7650000000000006, 8.799999999999999, 4.309999999999999], size: [17.39, 0.4, 32.35], r: 1, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-touch169": FleetMassing(
    id: "device.canary-display-touch169", rev: "72fa8cf1", ghost: false,
    envelope: [46.13, 17, 38.13],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [46.13, 14.4, 38.13], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [2.5, 14.4, 2.5], size: [41.13, 2.2, 33.13], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [5, 16.6, 5], size: [36.13, 0.4, 28.13], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-watch": FleetMassing(
    id: "device.canary-display-watch", rev: "17e158d1", ghost: false,
    envelope: [49, 23.2, 49],
    solids: [
      FleetSolid(kind: .cyl, material: "shell", axis: "y", at: [24.5, 0, 24.5], size: [], r: 24.5, h: 20.8, fullDetailOnly: false),
      FleetSolid(kind: .cyl, material: "glass", axis: "y", at: [24.5, 20.75, 24.5], size: [], r: 21, h: 2, fullDetailOnly: false),
      FleetSolid(kind: .cyl, material: "lit", axis: "y", at: [24.5, 22.8, 24.5], size: [], r: 17.5, h: 0.4, fullDetailOnly: false),
  ]),
  "device.canary-feeder": FleetMassing(
    id: "device.canary-feeder", rev: "bc53a17d", ghost: true,
    envelope: [120, 90, 150],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [120, 90, 150], r: 21.599999999999998, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-fence-guard": FleetMassing(
    id: "device.canary-fence-guard", rev: "d543b8dc", ghost: true,
    envelope: [44, 30, 96],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [44, 30, 96], r: 7.92, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-gatekeeper": FleetMassing(
    id: "device.canary-gatekeeper", rev: "119d2f3a", ghost: true,
    envelope: [38, 18, 62],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [38, 18, 62], r: 6.84, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-guardian": FleetMassing(
    id: "device.canary-guardian", rev: "69cf6bf8", ghost: true,
    envelope: [40, 28, 78],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [40, 28, 78], r: 7.199999999999999, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-hearth": FleetMassing(
    id: "device.canary-hearth", rev: "0741b92d", ghost: true,
    envelope: [46, 34, 46],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [46, 34, 46], r: 8.28, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-litter": FleetMassing(
    id: "device.canary-litter", rev: "4632de04", ghost: true,
    envelope: [300, 220, 40],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [300, 220, 40], r: 7.199999999999999, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-nightlight": FleetMassing(
    id: "device.canary-nightlight", rev: "27f621f7", ghost: false,
    envelope: [26.22, 14.25, 41.72],
    solids: [
      FleetSolid(kind: .box, material: "accent", axis: "y", at: [0, 0, 0], size: [25.12, 12.95, 41.17], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [-0.55, 9.85, 3], size: [0.6000000000000001, 2.8, 38.120000000000005], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [25.07, 9.85, 3], size: [0.6000000000000001, 2.8, 38.120000000000005], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [-0.55, 9.85, 41.120000000000005], size: [26.220000000000002, 2.8, 0.6000000000000001], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [2.860000000000001, 12.95, 3.770000000000003], size: [19.4, 0.9, 34.4], r: 1.5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [3.860000000000001, 13.85, 4.770000000000003], size: [17.4, 0.4, 32.4], r: 1, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-paw": FleetMassing(
    id: "device.canary-paw", rev: "89526725", ghost: true,
    envelope: [70, 26, 70],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [70, 26, 70], r: 12.6, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-poolwatch": FleetMassing(
    id: "device.canary-poolwatch", rev: "17f634f1", ghost: true,
    envelope: [62, 40, 96],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [62, 40, 96], r: 11.16, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-ranger": FleetMassing(
    id: "device.canary-ranger", rev: "f03bd7ee", ghost: true,
    envelope: [52, 34, 84],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [52, 34, 84], r: 9.36, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-sense": FleetMassing(
    id: "device.canary-sense", rev: "423b3305", ghost: false,
    envelope: [57.2, 21.5, 78.697],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [57.199981689453125, 19.5, 78.69733428955078], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 19.45, 20.497018310546878], size: [57.199981689453125, 2.05, 58.199981689453125], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "radome", axis: "y", at: [16.6, 21.45, 37.59700915527344], size: [24, 0.9, 24], r: 1.5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [28.6, 22.349999999999998, 26.497018310546878], size: [], r: 2, h: 0.6, fullDetailOnly: true),
  ]),
  "device.canary-vehicle": FleetMassing(
    id: "device.canary-vehicle", rev: "389ea1ca", ghost: false,
    envelope: [92, 62, 30],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [92, 62, 30], r: 5.3999999999999995, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-vehicle-guard": FleetMassing(
    id: "device.canary-vehicle-guard", rev: "962a8770", ghost: true,
    envelope: [44, 22, 66],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [44, 22, 66], r: 7.92, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-vision": FleetMassing(
    id: "device.canary-vision", rev: "0d4ba02d", ghost: false,
    envelope: [43.2, 23.38, 95.097],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [43.199981689453125, 21.38, 95.09732818603516], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 21.33, 20.497024414062494], size: [43.199981689453125, 2.05, 74.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [21.6, 23.33, 81.097], size: [], r: 5.5, h: 1.4, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [21.6, 23.33, 28.497024414062494], size: [], r: 1.8, h: 0.5, fullDetailOnly: true),
  ]),
  "device.canary-vision-devkit": FleetMassing(
    id: "device.canary-vision-devkit", rev: "36ad7de9", ghost: false,
    envelope: [74.8, 18.5, 96.497],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [74.79998779296875, 16.5, 96.49734115600586], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 16.45, 20.497], size: [74.79998779296875, 2.05, 76], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [37.4, 18.45, 82.497], size: [], r: 5.5, h: 1.4, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [37.4, 18.45, 28.497], size: [], r: 1.8, h: 0.5, fullDetailOnly: true),
  ]),
  "device.canary-vision-doorbell": FleetMassing(
    id: "device.canary-vision-doorbell", rev: "3eb0f713", ghost: false,
    envelope: [38.2, 30.2, 122.1],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [2.000009155273439, 0, 0], size: [34.199981689453125, 4, 119.5999870300293], r: 8, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [2.000009155273439, 3.95, 3.250012207031247], size: [34.199981689453125, 24.05, 115.5999755859375], r: 12, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "dark", axis: "y", at: [0.000009155273438921085, 27.95, 1.2500122070312472], size: [38.199981689453125, 2.249999999999999, 119.5999755859375], r: 12, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [19.1, 30.15, 98.1], size: [], r: 6, h: 1.4, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [19.1, 30.15, 24], size: [], r: 6, h: 1.6, fullDetailOnly: false),
  ]),
  "device.canary-vision-lite": FleetMassing(
    id: "device.canary-vision-lite", rev: "e1732477", ghost: true,
    envelope: [40, 40, 52],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [40, 40, 52], r: 7.199999999999999, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-vision-pro": FleetMassing(
    id: "device.canary-vision-pro", rev: "c0e230a6", ghost: true,
    envelope: [46, 46, 62],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [46, 46, 62], r: 8.28, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-wap": FleetMassing(
    id: "device.canary-wap", rev: "85a6140a", ghost: false,
    envelope: [33.7, 15.05, 36.6],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [33.699981689453125, 13.05, 36.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 13, 0], size: [33.699981689453125, 2.05, 36.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [16.85, 15, 18.3], size: [], r: 2.2, h: 0.6, fullDetailOnly: true),
  ]),
  "part.doorbell.body": FleetMassing(
    id: "part.doorbell.body", rev: "ba87f0bb", ghost: false,
    envelope: [34.2, 24, 115.6],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [34.199981689453125, 24, 115.5999755859375], r: 12, h: 0, fullDetailOnly: false),
  ]),
  "part.doorbell.face": FleetMassing(
    id: "part.doorbell.face", rev: "15907b73", ghost: false,
    envelope: [38.2, 9.45, 119.6],
    solids: [
      FleetSolid(kind: .box, material: "dark", axis: "y", at: [0, 0, 0], size: [38.199981689453125, 7.999999809265134, 119.5999755859375], r: 12, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [19.099990844726562, 8.049999809265135, 97.5999755859375], size: [], r: 6, h: 1.2, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [19.099990844726562, 8.049999809265135, 22], size: [], r: 6, h: 1.4, fullDetailOnly: false),
  ]),
  "part.doorbell.gasket": FleetMassing(
    id: "part.doorbell.gasket", rev: "da9d1172", ghost: false,
    envelope: [31.3, 1.5, 112.7],
    solids: [
      FleetSolid(kind: .box, material: "gasket", axis: "y", at: [0, 0, 0], size: [31.29998779296875, 1.5, 112.69998168945312], r: 11, h: 0, fullDetailOnly: false),
  ]),
  "part.doorbell.plate": FleetMassing(
    id: "part.doorbell.plate", rev: "11d233bb", ghost: false,
    envelope: [34.2, 14, 119.6],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [34.199981689453125, 14, 119.5999870300293], r: 8, h: 0, fullDetailOnly: false),
  ]),
  "part.sense.back": FleetMassing(
    id: "part.sense.back", rev: "53262d61", ghost: false,
    envelope: [57.2, 20.15, 78.697],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [57.199981689453125, 19.5, 78.69733428955078], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "dark", axis: "y", at: [28.599990844726562, 19.55, 71.69733428955078], size: [], r: 3.2, h: 0.6, fullDetailOnly: true),
  ]),
  "part.sense.front": FleetMassing(
    id: "part.sense.front", rev: "512c1cf5", ghost: false,
    envelope: [57.2, 6.95, 58.2],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [57.199981689453125, 6, 58.199981689453125], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "radome", axis: "y", at: [16.599990844726562, 6.05, 17.099990844726562], size: [24, 0.9, 24], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  "part.vision.back": FleetMassing(
    id: "part.vision.back", rev: "2162bb83", ghost: false,
    envelope: [43.2, 21.38, 95.097],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [43.199981689453125, 21.3799991607666, 95.09732818603516], r: 2, h: 0, fullDetailOnly: false),
  ]),
  "part.vision.bracket": FleetMassing(
    id: "part.vision.bracket", rev: "3b17d115", ghost: false,
    envelope: [46, 24.5, 33.95],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [46, 24.5, 14.28], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [14.72, 0, 14.229999999999999], size: [16.56, 24.5, 19.72], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.vision.front": FleetMassing(
    id: "part.vision.front", rev: "891013ab", ghost: false,
    envelope: [43.2, 9.05, 74.6],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [43.199981689453125, 7.800000190734863, 74.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [21.599990844726562, 7.850000190734863, 60.5999755859375], size: [], r: 5.5, h: 1.2, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [21.599990844726562, 7.850000190734863, 8], size: [], r: 1.8, h: 0.5, fullDetailOnly: true),
  ]),
  "part.vision.gasket": FleetMassing(
    id: "part.vision.gasket", rev: "f4e12258", ghost: false,
    envelope: [44.3, 1.5, 75.7],
    solids: [
      FleetSolid(kind: .box, material: "gasket", axis: "y", at: [0, 0, 0], size: [44.29998779296875, 1.5, 75.69998168945312], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.vision.knob": FleetMassing(
    id: "part.vision.knob", rev: "10526bcd", ghost: false,
    envelope: [21.705, 8, 21.705],
    solids: [
      FleetSolid(kind: .cyl, material: "dark", axis: "y", at: [10.852633476257324, 0, 10.852633476257324], size: [], r: 10.852633476257324, h: 8, fullDetailOnly: false),
  ]),
  "part.wap.base": FleetMassing(
    id: "part.wap.base", rev: "a8045876", ghost: false,
    envelope: [33.7, 13.05, 36.6],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [33.699981689453125, 13.049999237060547, 36.5999755859375], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.wap.battery-base": FleetMassing(
    id: "part.wap.battery-base", rev: "5fe9b81b", ghost: false,
    envelope: [104.5, 15.9, 39],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [104.5, 15.899999618530273, 39], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.wap.gasket": FleetMassing(
    id: "part.wap.gasket", rev: "b101ba12", ghost: false,
    envelope: [105.6, 1.5, 40.1],
    solids: [
      FleetSolid(kind: .box, material: "gasket", axis: "y", at: [0, 0, 0], size: [105.60000610351562, 1.5, 40.100006103515625], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.wap.lid": FleetMassing(
    id: "part.wap.lid", rev: "01ef2e35", ghost: false,
    envelope: [33.7, 6.55, 36.6],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [33.699981689453125, 6, 36.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [16.849990844726562, 6.05, 18.29998779296875], size: [], r: 2.2, h: 0.5, fullDetailOnly: true),
  ]),
  "part.wap.tray": FleetMassing(
    id: "part.wap.tray", rev: "4b6848fe", ghost: false,
    envelope: [24, 8, 18],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [24, 8, 18], r: 1, h: 0, fullDetailOnly: false),
  ]),
  "part.wap.weather-shield": FleetMassing(
    id: "part.wap.weather-shield", rev: "de6d1547", ghost: false,
    envelope: [120.5, 7.6, 55],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [120.5, 7.59999942779541, 55], r: 5, h: 0, fullDetailOnly: false),
  ]),
  "tool.fit-coupon": FleetMassing(
    id: "tool.fit-coupon", rev: "8b3335bd", ghost: false,
    envelope: [26, 7.9, 26],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [26, 4.344996643066406, 26], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "accent", axis: "y", at: [5.2, 4.294996643066407, 6.5], size: [15.6, 3.604997253417969, 13], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  ]
}
