// GENERATED by canary-local/tools/figures/gen_figures.mjs — do not edit.
// Spec: docs/design/FLEET_FIGURES.md
//
// The MASSING behind each fleet figure: the same mm solids iso.mjs projects
// into FleetFigures.swift, carried across so the phone can turn a figure on
// its vertical axis (FleetIsoProjector.swift) instead of being pinned to the
// one committed camera. Thumbnails keep drawing the committed faces — the
// canonical camera is the fleet's shared picture — and the turntable is
// pinned to them: FleetIsoProjectorTests re-projects these solids at the
// canonical yaw and requires the committed polygons, to the hundredth.
//
// Same vocabulary as iso.mjs: a solid is a closed outline extruded along an
// axis. `axis` "z" stands the outline up in plan; "y" faces it toward the
// viewer (a screen, a lens, a wall plate). `at` is the min corner for a
// box and the base-cap center for a cyl/disc, in mm, +X right / +Y front /
// +Z up.
//
// SecuraCV-Parity: every Apple surface that shows a device compiles this.
// (The marker lives in gen_figures.mjs's template — a marker hand-added to
// generated output survives exactly one regen.)

import Foundation

public struct FleetSolid: Sendable {
  public enum Kind: String, Sendable { case box, cyl, disc }
  public let kind: Kind
  public let material: String
  public let axis: String
  public let at: [Double]
  public let size: [Double]   // box: [w, d, h]; cyl/disc: empty (see r, h)
  public let r: Double        // box: corner radius; cyl/disc: radius
  public let h: Double        // cyl/disc: extrusion length (boxes carry size)
  public let fullDetailOnly: Bool  // dropped from glyph-size renders

  public init(kind: Kind, material: String, axis: String, at: [Double],
              size: [Double], r: Double, h: Double, fullDetailOnly: Bool) {
    self.kind = kind
    self.material = material
    self.axis = axis
    self.at = at
    self.size = size
    self.r = r
    self.h = h
    self.fullDetailOnly = fullDetailOnly
  }
}

public struct FleetMassing: Sendable {
  public let id: String
  public let rev: String      // the same content hash the figure carries
  public let ghost: Bool      // an idea renders as a dashed wireframe, always
  public let envelope: [Double]  // [w, d, h] mm, computed from the solids
  public let solids: [FleetSolid]

  public init(id: String, rev: String, ghost: Bool, envelope: [Double], solids: [FleetSolid]) {
    self.id = id
    self.rev = rev
    self.ghost = ghost
    self.envelope = envelope
    self.solids = solids
  }

  /// The named material palette, base sRGB 0–255 — the physical object's
  /// colors, deliberately not the UI theme's (a case is off-white in dark
  /// mode too). Same values as iso.mjs MATERIALS.
  public static let materials: [String: [Double]] = [
    "shell": [232, 230, 224],
    "shell2": [154, 157, 164],
    "dark": [58, 61, 68],
    "gasket": [74, 64, 82],
    "glass": [27, 31, 42],
    "lit": [61, 111, 168],
    "board": [31, 74, 56],
    "lens": [20, 24, 34],
    "metal": [184, 188, 196],
    "accent": [240, 180, 0],
    "radome": [216, 212, 200],
  ]

  /// The one light rig, normalized, with its ambient/diffuse split — carried
  /// as data so a Swift render shades with these exact numbers.
  public static let light: [Double] = [0.5008521736595763, -0.3505965215617034, 0.7913464343821306]
  public static let ambient: Double = 0.42
  public static let diffuse: Double = 0.58

  public static let all: [String: FleetMassing] = [
  "board.grove-vision-ai-v2": FleetMassing(
    id: "board.grove-vision-ai-v2", rev: "8c924aa8", ghost: false,
    envelope: [22.48, 4.46, 17.78],
    solids: [
      FleetSolid(kind: .box, material: "board", axis: "y", at: [0, 0, 0], size: [22.48, 1.5164000000000002, 17.78], r: 1, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "dark", axis: "y", at: [6.744, 1.5164000000000002, 4.445], size: [8.992, 2.9436, 8.89], r: 0.4, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "metal", axis: "y", at: [2, 1.5164000000000002, 14.580000000000002], size: [18.48, 2.007, 3.2], r: 0.4, h: 0, fullDetailOnly: true),
  ]),
  "board.mr60bha2": FleetMassing(
    id: "board.mr60bha2", rev: "e0f22290", ghost: false,
    envelope: [24, 3.2, 24],
    solids: [
      FleetSolid(kind: .box, material: "board", axis: "y", at: [0, 0, 0], size: [24, 1.2800000000000002, 24], r: 1, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "metal", axis: "y", at: [4.32, 1.2800000000000002, 4.32], size: [15.36, 1.92, 15.36], r: 0.3, h: 0, fullDetailOnly: false),
  ]),
  "board.round-display": FleetMassing(
    id: "board.round-display", rev: "3e2f04e9", ghost: false,
    envelope: [43, 10, 43],
    solids: [
      FleetSolid(kind: .cyl, material: "board", axis: "y", at: [21.5, 0, 21.5], size: [], r: 21.5, h: 7, fullDetailOnly: false),
      FleetSolid(kind: .cyl, material: "glass", axis: "y", at: [21.5, 7, 21.5], size: [], r: 20.9, h: 2.6, fullDetailOnly: false),
      FleetSolid(kind: .cyl, material: "lit", axis: "y", at: [21.5, 9.6, 21.5], size: [], r: 19.1, h: 0.4, fullDetailOnly: false),
  ]),
  "board.xiao": FleetMassing(
    id: "board.xiao", rev: "987b6a44", ghost: false,
    envelope: [22.64, 4.42, 17.78],
    solids: [
      FleetSolid(kind: .box, material: "board", axis: "y", at: [0, 0, 0], size: [22.64, 1.5028000000000001, 17.78], r: 1, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "metal", axis: "y", at: [6.339200000000001, 1.5028000000000001, 3.5560000000000005], size: [9.9616, 2.9172000000000002, 10.668000000000001], r: 0.4, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "metal", axis: "y", at: [6.92, 1.5028000000000001, 0], size: [8.8, 1.989, 3.2], r: 0.6, h: 0, fullDetailOnly: true),
  ]),
  "device.canary-chore": FleetMassing(
    id: "device.canary-chore", rev: "9ac17b93", ghost: true,
    envelope: [34, 14, 34],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [34, 14, 34], r: 6.12, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-clime": FleetMassing(
    id: "device.canary-clime", rev: "a3438690", ghost: true,
    envelope: [56, 26, 56],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [56, 26, 56], r: 10.08, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-curbwatch": FleetMassing(
    id: "device.canary-curbwatch", rev: "58cf33d3", ghost: true,
    envelope: [96, 52, 120],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [96, 52, 120], r: 17.28, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-dash": FleetMassing(
    id: "device.canary-display-dash", rev: "9bb5e13f", ghost: false,
    envelope: [118, 38.9, 79],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [118, 27.229999999999997, 79], r: 4, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [3, 27.229999999999997, 3], size: [112, 11.27, 73], r: 2.5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [6.5, 38.5, 6.5], size: [105, 0.4, 66], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-dash7": FleetMassing(
    id: "device.canary-display-dash7", rev: "cdff74a9", ghost: false,
    envelope: [204.96, 22, 122.76],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [204.96, 19, 122.76], r: 5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [6, 19, 6], size: [192.96, 2.6, 110.76], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [25, 21.6, 18], size: [154.88, 0.4, 86.72], r: 2, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-nightstand": FleetMassing(
    id: "device.canary-display-nightstand", rev: "c361481b", ghost: false,
    envelope: [24.92, 9.2, 53.17],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [24.92, 8.2, 40.97], r: 3.2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "dark", axis: "y", at: [6.460000000000001, 1.4999999999999991, -12.2], size: [12, 4.5, 12.25], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [2.7650000000000006, 8.2, 2.344999999999999], size: [19.39, 0.9, 36.28], r: 1.5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [3.7650000000000006, 8.799999999999999, 4.309999999999999], size: [17.39, 0.4, 32.35], r: 1, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-touch169": FleetMassing(
    id: "device.canary-display-touch169", rev: "72fa8cf1", ghost: false,
    envelope: [46.13, 17, 38.13],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [46.13, 14.4, 38.13], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [2.5, 14.4, 2.5], size: [41.13, 2.2, 33.13], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [5, 16.6, 5], size: [36.13, 0.4, 28.13], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-display-watch": FleetMassing(
    id: "device.canary-display-watch", rev: "64d11931", ghost: false,
    envelope: [52, 21.8, 52],
    solids: [
      FleetSolid(kind: .cyl, material: "shell", axis: "y", at: [26, 0, 26], size: [], r: 26, h: 19.400000000000002, fullDetailOnly: false),
      FleetSolid(kind: .cyl, material: "glass", axis: "y", at: [26, 19.35, 26], size: [], r: 22.5, h: 2, fullDetailOnly: false),
      FleetSolid(kind: .cyl, material: "lit", axis: "y", at: [26, 21.400000000000002, 26], size: [], r: 19, h: 0.4, fullDetailOnly: false),
  ]),
  "device.canary-feeder": FleetMassing(
    id: "device.canary-feeder", rev: "bc53a17d", ghost: true,
    envelope: [120, 90, 150],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [120, 90, 150], r: 21.599999999999998, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-fence-guard": FleetMassing(
    id: "device.canary-fence-guard", rev: "d543b8dc", ghost: true,
    envelope: [44, 30, 96],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [44, 30, 96], r: 7.92, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-gatekeeper": FleetMassing(
    id: "device.canary-gatekeeper", rev: "119d2f3a", ghost: true,
    envelope: [38, 18, 62],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [38, 18, 62], r: 6.84, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-guardian": FleetMassing(
    id: "device.canary-guardian", rev: "69cf6bf8", ghost: true,
    envelope: [40, 28, 78],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [40, 28, 78], r: 7.199999999999999, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-hearth": FleetMassing(
    id: "device.canary-hearth", rev: "0741b92d", ghost: true,
    envelope: [46, 34, 46],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [46, 34, 46], r: 8.28, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-litter": FleetMassing(
    id: "device.canary-litter", rev: "4632de04", ghost: true,
    envelope: [300, 220, 40],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [300, 220, 40], r: 7.199999999999999, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-nightlight": FleetMassing(
    id: "device.canary-nightlight", rev: "27f621f7", ghost: false,
    envelope: [26.22, 14.25, 41.72],
    solids: [
      FleetSolid(kind: .box, material: "accent", axis: "y", at: [0, 0, 0], size: [25.12, 12.95, 41.17], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [-0.55, 9.85, 3], size: [0.6000000000000001, 2.8, 38.120000000000005], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [25.07, 9.85, 3], size: [0.6000000000000001, 2.8, 38.120000000000005], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [-0.55, 9.85, 41.120000000000005], size: [26.220000000000002, 2.8, 0.6000000000000001], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "glass", axis: "y", at: [2.860000000000001, 12.95, 3.770000000000003], size: [19.4, 0.9, 34.4], r: 1.5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "lit", axis: "y", at: [3.860000000000001, 13.85, 4.770000000000003], size: [17.4, 0.4, 32.4], r: 1, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-paw": FleetMassing(
    id: "device.canary-paw", rev: "89526725", ghost: true,
    envelope: [70, 26, 70],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [70, 26, 70], r: 12.6, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-poolwatch": FleetMassing(
    id: "device.canary-poolwatch", rev: "17f634f1", ghost: true,
    envelope: [62, 40, 96],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [62, 40, 96], r: 11.16, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-ranger": FleetMassing(
    id: "device.canary-ranger", rev: "f03bd7ee", ghost: true,
    envelope: [52, 34, 84],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [52, 34, 84], r: 9.36, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-sense": FleetMassing(
    id: "device.canary-sense", rev: "112abb6d", ghost: false,
    envelope: [57.2, 27.95, 77.097],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [57.199981689453125, 20.5, 77.09732818603516], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 20.45, 20.497352600097656], size: [57.199981689453125, 6.05, 56.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "radome", axis: "y", at: [16.599990844726562, 26.45, 36.797340393066406], size: [24, 0.9, 24], r: 1.5, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [28.599990844726562, 27.349999999999998, 26.497352600097656], size: [], r: 2, h: 0.6, fullDetailOnly: true),
  ]),
  "device.canary-vehicle": FleetMassing(
    id: "device.canary-vehicle", rev: "389ea1ca", ghost: false,
    envelope: [92, 62, 30],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [92, 62, 30], r: 5.3999999999999995, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-vehicle-guard": FleetMassing(
    id: "device.canary-vehicle-guard", rev: "962a8770", ghost: true,
    envelope: [44, 22, 66],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [44, 22, 66], r: 7.92, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-vision": FleetMassing(
    id: "device.canary-vision", rev: "421d34f1", ghost: false,
    envelope: [43.2, 29.35, 94.097],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [43.199981689453125, 22, 94.09732818603516], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 21.95, 20.497352600097656], size: [43.199981689453125, 6.05, 73.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [21.599990844726562, 27.95, 80.09732818603516], size: [], r: 5.5, h: 1.4, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [21.599990844726562, 27.95, 28.497352600097656], size: [], r: 1.8, h: 0.5, fullDetailOnly: true),
  ]),
  "device.canary-vision-devkit": FleetMassing(
    id: "device.canary-vision-devkit", rev: "996e322d", ghost: false,
    envelope: [74.8, 23.35, 96.497],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [74.79998779296875, 16, 96.49734115600586], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 15.95, 20.49734115600586], size: [74.79998779296875, 6.05, 76], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [37.399993896484375, 21.95, 82.49734115600586], size: [], r: 5.5, h: 1.4, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [37.399993896484375, 21.95, 28.49734115600586], size: [], r: 1.8, h: 0.5, fullDetailOnly: true),
  ]),
  "device.canary-vision-doorbell": FleetMassing(
    id: "device.canary-vision-doorbell", rev: "bb33e209", ghost: false,
    envelope: [36.6, 43.55, 118],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [2, 0, 0], size: [32.5999755859375, 14, 118], r: 8, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [2, 13.95, 2], size: [32.5999755859375, 21.849999237060548, 114], r: 12, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "dark", axis: "y", at: [0, 35.74999923706055, 0], size: [36.5999755859375, 6.24999961853027, 118], r: 12, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [18.29998779296875, 41.94999885559082, 94], size: [], r: 6, h: 1.4, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [18.29998779296875, 41.94999885559082, 24], size: [], r: 6, h: 1.6, fullDetailOnly: false),
  ]),
  "device.canary-vision-lite": FleetMassing(
    id: "device.canary-vision-lite", rev: "e1732477", ghost: true,
    envelope: [40, 40, 52],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [40, 40, 52], r: 7.199999999999999, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-vision-pro": FleetMassing(
    id: "device.canary-vision-pro", rev: "c0e230a6", ghost: true,
    envelope: [46, 46, 62],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [46, 46, 62], r: 8.28, h: 0, fullDetailOnly: false),
  ]),
  "device.canary-wap": FleetMassing(
    id: "device.canary-wap", rev: "5fab1e20", ghost: false,
    envelope: [33.7, 18.25, 36.6],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [33.699981689453125, 11.699999809265137, 36.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 11.649999809265136, 0], size: [33.699981689453125, 6.05, 36.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [16.849990844726562, 17.649999809265136, 18.29998779296875], size: [], r: 2.2, h: 0.6, fullDetailOnly: true),
  ]),
  "part.doorbell.body": FleetMassing(
    id: "part.doorbell.body", rev: "af045762", ghost: false,
    envelope: [32.6, 21.8, 114],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [32.5999755859375, 21.799999237060547, 114], r: 12, h: 0, fullDetailOnly: false),
  ]),
  "part.doorbell.face": FleetMassing(
    id: "part.doorbell.face", rev: "5a3db2a0", ghost: false,
    envelope: [36.6, 7.65, 118],
    solids: [
      FleetSolid(kind: .box, material: "dark", axis: "y", at: [0, 0, 0], size: [36.5999755859375, 6.199999618530271, 118], r: 12, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [18.29998779296875, 6.24999961853027, 96], size: [], r: 6, h: 1.2, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [18.29998779296875, 6.24999961853027, 22], size: [], r: 6, h: 1.4, fullDetailOnly: false),
  ]),
  "part.doorbell.gasket": FleetMassing(
    id: "part.doorbell.gasket", rev: "15c22622", ghost: false,
    envelope: [30.5, 1.5, 111.9],
    solids: [
      FleetSolid(kind: .box, material: "gasket", axis: "y", at: [0, 0, 0], size: [30.5, 1.5, 111.89999389648438], r: 11, h: 0, fullDetailOnly: false),
  ]),
  "part.doorbell.plate": FleetMassing(
    id: "part.doorbell.plate", rev: "612f9087", ghost: false,
    envelope: [32.6, 14, 118],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [32.5999755859375, 14, 118], r: 8, h: 0, fullDetailOnly: false),
  ]),
  "part.sense.back": FleetMassing(
    id: "part.sense.back", rev: "244879b1", ghost: false,
    envelope: [57.2, 21.15, 77.097],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [57.199981689453125, 20.5, 77.09732818603516], r: 0, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "dark", axis: "y", at: [28.599990844726562, 20.55, 70.09732818603516], size: [], r: 3.2, h: 0.6, fullDetailOnly: true),
  ]),
  "part.sense.front": FleetMassing(
    id: "part.sense.front", rev: "56bc7c4f", ghost: false,
    envelope: [57.2, 6.95, 56.6],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [57.199981689453125, 6, 56.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "radome", axis: "y", at: [16.599990844726562, 6.05, 16.29998779296875], size: [24, 0.9, 24], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  "part.vision.back": FleetMassing(
    id: "part.vision.back", rev: "1d1de5d2", ghost: false,
    envelope: [43.2, 22, 94.097],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [43.199981689453125, 22, 94.09732818603516], r: 2, h: 0, fullDetailOnly: false),
  ]),
  "part.vision.bracket": FleetMassing(
    id: "part.vision.bracket", rev: "3b17d115", ghost: false,
    envelope: [46, 24.5, 33.95],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [46, 24.5, 14.28], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [14.72, 0, 14.229999999999999], size: [16.56, 24.5, 19.72], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.vision.front": FleetMassing(
    id: "part.vision.front", rev: "8fe07ad7", ghost: false,
    envelope: [43.2, 7.25, 73.6],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [43.199981689453125, 6, 73.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "lens", axis: "y", at: [21.599990844726562, 6.05, 59.5999755859375], size: [], r: 5.5, h: 1.2, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [21.599990844726562, 6.05, 8], size: [], r: 1.8, h: 0.5, fullDetailOnly: true),
  ]),
  "part.vision.gasket": FleetMassing(
    id: "part.vision.gasket", rev: "d444bc47", ghost: false,
    envelope: [43.5, 1.5, 73.9],
    solids: [
      FleetSolid(kind: .box, material: "gasket", axis: "y", at: [0, 0, 0], size: [43.5, 1.5, 73.89999389648438], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.vision.knob": FleetMassing(
    id: "part.vision.knob", rev: "10526bcd", ghost: false,
    envelope: [21.705, 8, 21.705],
    solids: [
      FleetSolid(kind: .cyl, material: "dark", axis: "y", at: [10.852633476257324, 0, 10.852633476257324], size: [], r: 10.852633476257324, h: 8, fullDetailOnly: false),
  ]),
  "part.wap.base": FleetMassing(
    id: "part.wap.base", rev: "d64c230c", ghost: false,
    envelope: [33.7, 11.7, 36.6],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [33.699981689453125, 11.699999809265137, 36.5999755859375], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.wap.battery-base": FleetMassing(
    id: "part.wap.battery-base", rev: "022b743d", ghost: false,
    envelope: [104.7, 15.2, 39],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [104.69998168945312, 15.199999809265137, 39], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.wap.gasket": FleetMassing(
    id: "part.wap.gasket", rev: "782b3c29", ghost: false,
    envelope: [105, 1.5, 39.3],
    solids: [
      FleetSolid(kind: .box, material: "gasket", axis: "y", at: [0, 0, 0], size: [105, 1.5, 39.29998779296875], r: 3, h: 0, fullDetailOnly: false),
  ]),
  "part.wap.lid": FleetMassing(
    id: "part.wap.lid", rev: "01ef2e35", ghost: false,
    envelope: [33.7, 6.55, 36.6],
    solids: [
      FleetSolid(kind: .box, material: "shell", axis: "y", at: [0, 0, 0], size: [33.699981689453125, 6, 36.5999755859375], r: 3, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .disc, material: "accent", axis: "y", at: [16.849990844726562, 6.05, 18.29998779296875], size: [], r: 2.2, h: 0.5, fullDetailOnly: true),
  ]),
  "part.wap.tray": FleetMassing(
    id: "part.wap.tray", rev: "4b6848fe", ghost: false,
    envelope: [24, 8, 18],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [24, 8, 18], r: 1, h: 0, fullDetailOnly: false),
  ]),
  "part.wap.weather-shield": FleetMassing(
    id: "part.wap.weather-shield", rev: "105d8bc6", ghost: false,
    envelope: [119.1, 7.6, 53.4],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [119.0999755859375, 7.59999942779541, 53.399993896484375], r: 5, h: 0, fullDetailOnly: false),
  ]),
  "tool.fit-coupon": FleetMassing(
    id: "tool.fit-coupon", rev: "de8f6d15", ghost: false,
    envelope: [26, 7.4, 26],
    solids: [
      FleetSolid(kind: .box, material: "shell2", axis: "y", at: [0, 0, 0], size: [26, 4.069996643066407, 26], r: 2, h: 0, fullDetailOnly: false),
      FleetSolid(kind: .box, material: "accent", axis: "y", at: [5.2, 4.019996643066407, 6.5], size: [15.6, 3.3799972534179688, 13], r: 1.5, h: 0, fullDetailOnly: false),
  ]),
  ]
}
