// GENERATED by canary-local/tools/hatchery/gen_hatch_swift.mjs — do not edit.
// Source of truth: canary-local/devices/hatch.json
//
// The Hatchery's word lists, as Swift, plus proof vectors that pin this app's
// derivation to the JavaScript one the browser Lab and the desktop Flasher
// run. A Canary has ONE name on every surface because all three compute it
// from the same key with the same algorithm — see BirthCertificate.swift and
// canary-local/tools/hatchery/derive.mjs.

import Foundation

public enum HatchSpec {
    public static let ringPrefix = "CNRY"
    public static let titleChance = 0.6

    public static let titles: [String] = [
        "Sir",
        "Lady",
        "Captain",
        "Professor",
        "Baron",
        "Dame",
        "Admiral",
        "Chief",
        "Saint",
        "Major",
        "Little",
        "Old",
        "Madam",
        "Count",
    ]

    public static let first: [String] = [
        "Pip",
        "Chirp",
        "Beaky",
        "Cluck",
        "Nib",
        "Quill",
        "Gizmo",
        "Pixel",
        "Byte",
        "Radar",
        "Perch",
        "Warble",
        "Trill",
        "Cheep",
        "Wren",
        "Robin",
        "Finch",
        "Sparrow",
        "Kestrel",
        "Merlin",
        "Hawkeye",
        "Aria",
        "Echo",
        "Vigil",
        "Sable",
        "Featherton",
        "Waddles",
        "Sprocket",
        "Biscuit",
        "Noodle",
        "Waffles",
        "Peck",
    ]

    public static let house: [String] = [
        "of Perchwood",
        "the Vigilant",
        "the Unblinking",
        "von Watchbird",
        "McSentinel",
        "of the Nest Eternal",
        "the Ever-Watchful",
        "Featherwatch",
        "of House Chirpington",
        "the Keen-Eyed",
        "Nightwarden",
        "of Roost Hall",
        "the Tamper-Evident",
        "of the Signed Ledger",
        "Quillsworth",
        "the Unbribable",
        "of Coop Hollow",
        "the Wide-Awake",
    ]

    public static let mottoes: [String] = [
        "Records what happened — never who.",
        "Watches the door, forgets the face.",
        "Sees all, tells only you.",
        "On duty, never online.",
        "Sworn to witness, never to surveil.",
        "Small bird. Long memory. Sealed lips.",
        "Trusts the math, not the masters.",
        "Every claim signed, every secret kept.",
        "A witness you can check, not one you must believe.",
    ]

    public static let ordinals: [String] = [
        "",
        "the First",
        "the Second",
        "the Third",
        "the Fourth",
        "the Fifth",
        "the Sixth",
        "the Seventh",
        "the Eighth",
        "the Ninth",
        "the Tenth",
        "the Eleventh",
        "the Twelfth",
    ]

    /// The certificate's fixed words — the kicker, the vow, the craft line.
    public static let kicker = "Certificate of Hatching"
    public static let intro = "Be it known that on this day there hatched a witness true —"
    public static let craft = "shell pressed in the workshop · spirit woken in the hatchery"
    public static let foot = "Witnessed & sealed · records what happened, never who · Errer Labs"

    /// Fingerprint → what the JavaScript derives from it. If a Swift change
    /// breaks one of these, the same Canary would answer to two names
    /// depending on which app you asked, which is the one thing a certificate
    /// may not do.
    public struct Vector: Sendable {
        public let fingerprint: String
        public let name: String
        public let lineage: String
        public let motto: String
    }

    public static let vectors: [Vector] = [
        Vector(fingerprint: "0000000000000000",
               name: "Biscuit of Perchwood",
               lineage: "the Sixth of its name, of Perchwood",
               motto: "On duty, never online."),
        Vector(fingerprint: "a3f7c1d2e4b58690",
               name: "Radar the Ever-Watchful",
               lineage: "the Eleventh of its name, Ever-Watchful",
               motto: "Sworn to witness, never to surveil."),
        Vector(fingerprint: "ffffffffffffffff",
               name: "Madam Gizmo of Roost Hall",
               lineage: "the Fifth of its name, of Roost Hall",
               motto: "Every claim signed, every secret kept."),
        Vector(fingerprint: "1234567890abcdef",
               name: "Little Cheep Featherwatch",
               lineage: "the Eleventh of its name, Featherwatch",
               motto: "Trusts the math, not the masters."),
        Vector(fingerprint: "deadbeefcafef00d",
               name: "Professor Biscuit the Ever-Watchful",
               lineage: "the Sixth of its name, Ever-Watchful",
               motto: "Sworn to witness, never to surveil."),
        Vector(fingerprint: "0f1e2d3c4b5a6978",
               name: "Madam Sparrow of Coop Hollow",
               lineage: "the Tenth of its name, of Coop Hollow",
               motto: "Watches the door, forgets the face."),
    ]
}
