// TimelineScrub.swift  (SHARED — one timeline model on every Apple surface)
//
// The Swift port of viewer/timeline_core.js: the model behind the "day shape"
// timeline — a Sublime-Text-style minimap of the sealed record, where every
// alert is one greeked stroke, quiet hours fold into pleats, and a declared
// gap can never be folded out of sight.
//
// WHY A PORT AND NOT A REWRITE. The same window of the same log has to look
// like the same day on the phone, on the TV, in the Lab, and in the offline
// evidence viewer — otherwise two surfaces disagree about what a day WAS, and
// the record stops being a record. So this file is a line-for-line port, and
// the two are pinned to ONE shared fixture:
//
//     viewer/fixtures/timeline/scrub_parity.json
//
// generated by `node viewer/tools/gen_timeline_parity.mjs`, asserted by
// viewer/timeline_core.test.js (JS) and TimelineScrubTests.swift (Swift).
// Change the folding or layout rules and BOTH sides must move together, or
// the fixture fails on whichever side lagged.
//
// Deliberately Foundation-only — no SwiftUI, no Theme, no Severity — so it
// compiles unchanged into the app, the widgets, the watch and the watch
// widgets, which take ios/Shared wholesale. Color and layout live in the
// views; this file only decides what a day is shaped like.
//
// The tvOS Witness Wall does NOT compile this yet, and that is deliberate:
// it lists its shared sources one by one, this file deliberately omits the
// opt-in marker that scripts/lint_apple_parity.py looks for (do not name that
// marker here — the lint greps for the bare string and would enroll this file
// by describing it), and the Wall has no time-bearing event data to draw:
// sealed entries carry no timestamp, and while the kernel now serves
// /api/sealed-log (token-gated), the TV holds no token to read it yet.
// Adding the marker plus one project.yml entry is the whole port on the day
// that data reaches the TV. See docs/design/witness_log_viewer.md.

import Foundation

// MARK: - Vocabulary presentation

/// Presentation-only grouping used by the timeline's minimap so kinds are
/// separable at a glance. NOT a vocabulary: the meaning of an event is its
/// `WitnessEvent` label, and on surfaces that carry a real `Severity` the
/// view colors by severity instead. `tamper` and `gap` always ride a status
/// role and always carry a glyph plus a label — never color alone.
enum TimelineFamily: String, Codable, CaseIterable, Sendable {
    case move, touch, sound, tamper, gap, other

    var label: String {
        switch self {
        case .move: return "Crossings & movement"
        case .touch: return "Presence & touch"
        case .sound: return "Sound"
        case .tamper: return "Tamper"
        case .gap: return "Gaps"
        case .other: return "System records"
        }
    }
}

/// What a row IS, which decides whether it can anchor the layout. `event` and
/// `gap` and `system` are anchors; `heartbeat` is not, so a night of hourly
/// heartbeats still folds — and the fold reports how many were sealed inside
/// it ("quiet, with proof of watching").
enum TimelineKind: String, Codable, Sendable {
    case event, gap, system, heartbeat
}

enum TimelineScrub {
    static let defaultBucketSeconds = 600
    static let foldMinQuietSeconds = 3600
    static let foldPadSeconds = 600
    static let daySeconds = 86_400

    /// The presentation family for a dictionary event type. Mirrors
    /// EVENT_TYPE_META in viewer/timeline_core.js; the labels themselves come
    /// from `WitnessEvent.label` (the dictionary mirror), never from here, so
    /// there is only one place a label can drift.
    static func family(for event: WitnessEvent) -> TimelineFamily {
        switch event {
        case .boundaryCrossingObjectLarge, .boundaryCrossingObjectSmall, .vehicleArrivalDeparture:
            return .move
        case .presenceInRestrictedZone, .vehiclePresenceAfterHours,
             .contactStateChange, .objectRemovedFromZone:
            return .touch
        case .acousticImpulseInZone:
            return .sound
        case .tamperDetected:
            return .tamper
        }
    }

    /// "StorageFull" / "storage_full" -> "Storage full". Generic on purpose:
    /// failure types carry no display metadata in the dictionary, so there is
    /// no table here that could fall out of sync with one.
    static func humanize(_ raw: String) -> String {
        let snake = EventVocabulary.snakeCase(raw)
        let words = snake.split(separator: "_").filter { !$0.isEmpty }
        guard let first = words.first else { return "Unknown" }
        let rest = words.dropFirst().joined(separator: " ")
        let head = first.prefix(1).uppercased() + first.dropFirst()
        return rest.isEmpty ? head : head + " " + rest
    }
}

// MARK: - Records

/// One row of the timeline. Time is ALWAYS a coarse bucket (Invariant III):
/// `t0` is the bucket start in epoch seconds and `size` its width, so nothing
/// downstream can invent a precision the log never recorded.
struct TimelineRecord: Codable, Hashable, Sendable {
    var t0: Int
    var size: Int
    var kind: TimelineKind
    var label: String
    var family: TimelineFamily
    var zone: String
    var confidence: Double?
    var details: String
    /// Present only on surfaces that carry a real severity (the app's
    /// `AlertRecord`); nil in the evidence viewer's sealed events, which have
    /// no severity field at all. Views color by this when it exists.
    var severityRaw: UInt8?

    init(t0: Int, size: Int = TimelineScrub.defaultBucketSeconds,
                kind: TimelineKind, label: String, family: TimelineFamily,
                zone: String = "", confidence: Double? = nil,
                details: String = "", severityRaw: UInt8? = nil) {
        self.t0 = t0
        self.size = size
        self.kind = kind
        self.label = label
        self.family = family
        self.zone = zone
        self.confidence = confidence
        self.details = details
        self.severityRaw = severityRaw
    }

    var endsAt: Int { t0 + size }
}

// MARK: - Segments (Sublime's code folding, for quiet time)

struct TimelineSegment: Hashable, Sendable {
    enum Kind: String, Sendable { case span, fold }
    var kind: Kind
    var t0: Int
    var t1: Int
    /// Heartbeats sealed inside a fold — quiet, with proof of watching.
    var heartbeats: Int = 0

    var duration: Int { t1 - t0 }
}

/// A segment placed on screen. `span` height is proportional to its duration;
/// `fold` is a fixed pleat, so a week of nothing costs 18 points, not a
/// scrollbar's worth of emptiness.
struct TimelineLayoutSegment: Hashable, Sendable {
    var kind: TimelineSegment.Kind
    var t0: Int
    var t1: Int
    var y0: Double
    var y1: Double
    var heartbeats: Int
}

struct TimelineGridLine: Hashable, Sendable {
    var t: Int
    var y: Double
    var isMajor: Bool
}

// MARK: - Days (the sticky headers and their density strips)

struct TimelineDayCell: Hashable, Sendable {
    var index: Int
    var count: Int
    var family: TimelineFamily
    var hasGap: Bool
    /// Worst-first: a cell reports the most serious thing in it, never an
    /// average. Nil where the records carry no severity at all (the evidence
    /// viewer's sealed events have no severity field).
    var worstSeverityRaw: UInt8?
}

struct TimelineDay: Hashable, Sendable, Identifiable {
    var dayT0: Int
    var label: String
    var count: Int
    var gapCount: Int
    var tamperCount: Int
    /// The worst severity anywhere in this day, for a worst-first header.
    var worstSeverityRaw: UInt8?
    var cellsPerDay: Int
    var firstIndex: Int
    /// The DECLARED covered slice of this day as fractions 0...1 of the
    /// strip, or nil when the source declares no window at all. Hours the
    /// export does not cover render as ABSENT, never as "quiet" — and a
    /// source that says nothing about coverage gets no track drawn, because
    /// a timeline may not guess history it was not given.
    var coverageFrom: Double?
    var coverageTo: Double?
    var cells: [TimelineDayCell]

    var id: Int { dayT0 }
}

// MARK: - The reading-pane item stream

enum TimelineItem: Hashable, Sendable, Identifiable {
    case day(TimelineDay)
    case fold(t0: Int, t1: Int, heartbeats: Int)
    case record(TimelineRecord, index: Int)

    var id: String {
        switch self {
        case .day(let d): return "day-\(d.dayT0)"
        case .fold(let t0, let t1, _): return "fold-\(t0)-\(t1)"
        case .record(let r, let i): return "rec-\(i)-\(r.t0)"
        }
    }

    /// The time this item anchors to, for scrub sync. Day headers deliberately
    /// return nil: a header's midnight can sit outside the covered domain, and
    /// using it as an anchor collapses the viewport indicator.
    var anchorTime: Int? {
        switch self {
        case .day: return nil
        case .fold(let t0, _, _): return t0
        case .record(let r, _): return r.t0
        }
    }
}

// MARK: - The model

struct TimelineModel: Sendable {
    var records: [TimelineRecord] = []
    var segments: [TimelineSegment] = []
    var days: [TimelineDay] = []
    var items: [TimelineItem] = []
    var zones: [String] = []
    var counts: [TimelineFamily: Int] = [:]
    var heartbeats: Int = 0
    var bucketSeconds: Int = TimelineScrub.defaultBucketSeconds
    /// Ledger entries that could not be read. Counted, never silently dropped.
    var unparsed: Int = 0

    var isEmpty: Bool { records.isEmpty }

    /// Records that light the minimap and the density strips. Heartbeats are
    /// proof of life, not activity, so they never light a cell.
    var visibleRecords: [TimelineRecord] { records.filter { $0.kind != .heartbeat } }
}

extension TimelineScrub {

    /// Stable by (t0, original position). Swift's `sort` is NOT guaranteed
    /// stable and JS's IS, so ordering within one bucket would drift between
    /// the two implementations without this — the parity fixture catches it.
    static func sorted(_ records: [TimelineRecord]) -> [TimelineRecord] {
        records.enumerated()
            .sorted { a, b in a.element.t0 == b.element.t0 ? a.offset < b.offset : a.element.t0 < b.element.t0 }
            .map(\.element)
    }

    /// Split the covered window into drawn spans and folded pleats. Only time
    /// with NO anchor at all can fold, so a declared gap (a failure record) is
    /// always visible — the one thing a witness log must never hide.
    static func segments(for records: [TimelineRecord],
                                coverageT0: Int? = nil,
                                coverageT1: Int? = nil,
                                minQuiet: Int = foldMinQuietSeconds,
                                pad: Int = foldPadSeconds) -> [TimelineSegment] {
        let anchors = records.filter { $0.kind != .heartbeat }
        let beats = records.filter { $0.kind == .heartbeat }
        let base = anchors.isEmpty ? beats : anchors
        guard let first = base.first else { return [] }

        // The DOMAIN spans every record; only the FOLD anchors exclude
        // heartbeats. Deriving the domain from anchors alone put heartbeats
        // recorded after the last event outside the timeline entirely.
        let firstT0 = min(records.first?.t0 ?? first.t0, first.t0)
        let lastEnd = records.reduce(0) { max($0, $1.endsAt) }
        let cov0 = min(coverageT0 ?? firstT0, firstT0)
        let cov1 = max(coverageT1 ?? lastEnd, lastEnd)

        var out: [TimelineSegment] = []
        var cursor = cov0
        var prevEnd = cov0

        for i in 0...base.count {
            let nextStart = i < base.count ? base[i].t0 : cov1
            let leadingEdge = prevEnd == cov0 && cursor == cov0
            let trailingEdge = i == base.count
            // No breathing room needed against the window's own edge.
            let padL = leadingEdge ? 0 : pad
            let padR = trailingEdge ? 0 : pad
            let quiet = nextStart - prevEnd
            if quiet >= minQuiet + padL + padR {
                if prevEnd + padL > cursor {
                    out.append(TimelineSegment(kind: .span, t0: cursor, t1: prevEnd + padL))
                }
                out.append(TimelineSegment(kind: .fold, t0: prevEnd + padL, t1: nextStart - padR))
                cursor = nextStart - padR
            }
            if i < base.count { prevEnd = max(prevEnd, base[i].endsAt) }
        }
        if cursor < cov1 || out.isEmpty {
            out.append(TimelineSegment(kind: .span, t0: cursor, t1: max(cov1, cursor + 1)))
        }

        for i in out.indices where out[i].kind == .fold {
            let s = out[i]
            out[i].heartbeats = beats.filter { $0.t0 >= s.t0 && $0.t0 < s.t1 }.count
        }
        return out
    }

    static let foldPoints: Double = 18
    static let minSpanPoints: Double = 6

    /// Distribute `height` over the segments: folds take a fixed pleat, spans
    /// share the rest in proportion to their duration.
    static func layout(_ segments: [TimelineSegment], height: Double,
                              foldPx: Double = foldPoints,
                              minSpanPx: Double = minSpanPoints) -> [TimelineLayoutSegment] {
        let foldCount = segments.filter { $0.kind == .fold }.count
        let spans = segments.filter { $0.kind == .span }
        let spanDuration = Double(spans.reduce(0) { $0 + $1.duration })
        let denom = spanDuration > 0 ? spanDuration : 1
        let available = max(height - Double(foldCount) * foldPx - Double(spans.count) * minSpanPx, 0)
        var y: Double = 0
        return segments.map { s in
            let h = s.kind == .fold ? foldPx : minSpanPx + (Double(s.duration) / denom) * available
            defer { y += h }
            return TimelineLayoutSegment(kind: s.kind, t0: s.t0, t1: s.t1,
                                         y0: y, y1: y + h, heartbeats: s.heartbeats)
        }
    }

    /// Time to offset through the folded coordinate space. Clamps to the domain.
    static func y(of t: Int, in layout: [TimelineLayoutSegment]) -> Double {
        guard let firstSeg = layout.first, let lastSeg = layout.last else { return 0 }
        if t <= firstSeg.t0 { return firstSeg.y0 }
        for s in layout where t <= s.t1 {
            let f = Double(t - s.t0) / Double(max(s.t1 - s.t0, 1))
            return s.y0 + f * (s.y1 - s.y0)
        }
        return lastSeg.y1
    }

    /// Offset back to time — the inverse of `y(of:in:)`, same clamping.
    static func time(atY y: Double, in layout: [TimelineLayoutSegment]) -> Int {
        guard let firstSeg = layout.first, let lastSeg = layout.last else { return 0 }
        if y <= firstSeg.y0 { return firstSeg.t0 }
        for s in layout where y <= s.y1 {
            let f = (y - s.y0) / max(s.y1 - s.y0, 1e-9)
            return s.t0 + Int((Double(s.t1 - s.t0) * f).rounded(.down))
        }
        return lastSeg.t1
    }

    static let gridStepsSeconds = [600, 1800, 3600, 3 * 3600, 6 * 3600, 12 * 3600, 86_400]
    /// A ruler denser than this is not a ruler. Without the cap, a multi-year
    /// export falls past every candidate step and emits one line per day.
    static let maxGridLines = 240

    /// Ruler lines: the smallest interval whose lines stay `minGap` apart
    /// inside every span. Day boundaries are drawn major.
    static func gridLines(_ layout: [TimelineLayoutSegment], minGap: Double) -> [TimelineGridLine] {
        let spans = layout.filter { $0.kind == .span }
        guard !spans.isEmpty else { return [] }
        var step = gridStepsSeconds[gridStepsSeconds.count - 1]
        for candidate in gridStepsSeconds {
            let ok = spans.allSatisfy { s in
                let pxPerSecond = (s.y1 - s.y0) / Double(max(s.t1 - s.t0, 1))
                return Double(candidate) * pxPerSecond >= minGap || (s.t1 - s.t0) < candidate
            }
            if ok { step = candidate; break }
        }
        // Past the largest candidate the only way to stay readable is a
        // coarser step, so keep doubling until the ruler fits under the cap.
        let spanTotal = spans.reduce(0) { $0 + $1.t1 - $1.t0 }
        while step > 0 && spanTotal / step > maxGridLines { step *= 2 }
        var lines: [TimelineGridLine] = []
        guard step > 0 else { return lines }
        for s in spans {
            var t = Int((Double(s.t0) / Double(step)).rounded(.up)) * step
            while t <= s.t1 {
                lines.append(TimelineGridLine(t: t, y: y(of: t, in: layout), isMajor: t % daySeconds == 0))
                // Belt, matching the JS side: never unbounded, whatever the span.
                if lines.count >= maxGridLines { return lines }
                t += step
            }
        }
        return lines
    }

    /// Group into days, each with the density strip that makes a day readable
    /// without reading. Reserved statuses win a cell outright (gap, then
    /// tamper) so trouble is never averaged away by a busy hour.
    ///
    /// `calendar` decides where a day STARTS, and the two callers genuinely
    /// want different answers. The evidence viewer works in UTC — the record's
    /// own frame, captioned as such, because a court reads the log and not the
    /// reader's location — and that is the parity-tested default. The phone
    /// must pass `.current`: the Alerts list groups its sections with
    /// `Calendar.current`, so a UTC-grouped ribbon put a Sunday 17:00 Pacific
    /// alert under a "Monday" heading directly above the Sunday rows it
    /// scrolls to.
    ///
    /// A 23- or 25-hour day (a DST transition) still measures its coverage
    /// fractions against a 24-hour span, so the strip's shading is off by an
    /// hour's width on exactly those two days a year. Grouping and labels stay
    /// correct, which is the part that could actually mislead.
    static func days(for records: [TimelineRecord],
                            bucketSeconds: Int = defaultBucketSeconds,
                            coverageT0: Int? = nil,
                            coverageT1: Int? = nil,
                            calendar: Calendar = utcCalendar) -> [TimelineDay] {
        let perDay = max(1, Int((Double(daySeconds) / Double(bucketSeconds)).rounded()))
        let visible = records.filter { $0.kind != .heartbeat }
        func startOfDay(_ t: Int) -> Int {
            Int(calendar.startOfDay(for: Date(timeIntervalSince1970: TimeInterval(t))).timeIntervalSince1970)
        }

        struct Bucket {
            var count = 0
            var families: [TimelineFamily: Int] = [:]
            var hasGap = false
            var worstSeverityRaw: UInt8?
        }
        struct Day {
            var count = 0
            var gapCount = 0
            var tamperCount = 0
            var worstSeverityRaw: UInt8?
            var firstIndex: Int
            var buckets: [Int: Bucket] = [:]
        }

        var days: [Int: Day] = [:]
        var order: [Int] = []
        for (index, r) in visible.enumerated() {
            let dayT0 = startOfDay(r.t0)
            if days[dayT0] == nil {
                days[dayT0] = Day(firstIndex: index)
                order.append(dayT0)
            }
            days[dayT0]!.count += 1
            if r.kind == .gap { days[dayT0]!.gapCount += 1 }
            if r.family == .tamper { days[dayT0]!.tamperCount += 1 }
            if let sev = r.severityRaw {
                days[dayT0]!.worstSeverityRaw = max(days[dayT0]!.worstSeverityRaw ?? 0, sev)
            }
            let i = min((r.t0 - dayT0) / bucketSeconds, perDay - 1)
            var cell = days[dayT0]!.buckets[i] ?? Bucket()
            cell.count += 1
            cell.families[r.family, default: 0] += 1
            if r.kind == .gap { cell.hasGap = true }
            if let sev = r.severityRaw { cell.worstSeverityRaw = max(cell.worstSeverityRaw ?? 0, sev) }
            days[dayT0]!.buckets[i] = cell
        }

        // COVERAGE IS DECLARED, NEVER INFERRED. Defaulting the window to the
        // span of the records themselves invented the one fact this strip
        // exists to be careful about. With no declared window both bounds
        // stay nil and the ribbon omits its track.
        //
        // When a window IS declared, clamp it to the BUCKET GRID the cells
        // are drawn on, so the covered region always contains every cell the
        // strip lights — a cell spans its whole bucket, so clamping to the
        // record's own instant would still leave its leading edge outside.
        var cov0: Int?
        var cov1: Int?
        if coverageT0 != nil || coverageT1 != nil {
            let firstT0 = visible.first?.t0 ?? 0
            let lastEnd = visible.reduce(firstT0) { max($0, $1.endsAt) }
            let gridFloor = Int((Double(firstT0) / Double(bucketSeconds)).rounded(.down)) * bucketSeconds
            let gridCeil = Int((Double(lastEnd) / Double(bucketSeconds)).rounded(.up)) * bucketSeconds
            cov0 = min(coverageT0 ?? gridFloor, gridFloor)
            cov1 = max(coverageT1 ?? gridCeil, gridCeil)
        }

        return order.sorted().map { dayT0 in
            let d = days[dayT0]!
            let cells = d.buckets.keys.sorted().map { i -> TimelineDayCell in
                let b = d.buckets[i]!
                return TimelineDayCell(index: i, count: b.count,
                                       family: dominantFamily(b.families, hasGap: b.hasGap),
                                       hasGap: b.hasGap,
                                       worstSeverityRaw: b.worstSeverityRaw)
            }
            return TimelineDay(
                dayT0: dayT0,
                label: dayLabel(dayT0, calendar: calendar),
                count: d.count,
                gapCount: d.gapCount,
                tamperCount: d.tamperCount,
                worstSeverityRaw: d.worstSeverityRaw,
                cellsPerDay: perDay,
                firstIndex: d.firstIndex,
                coverageFrom: cov0.map { min(max(Double($0 - dayT0) / Double(daySeconds), 0), 1) },
                coverageTo: cov1.map { min(max(Double($0 - dayT0) / Double(daySeconds), 0), 1) },
                cells: cells)
        }
    }

    static func dominantFamily(_ families: [TimelineFamily: Int], hasGap: Bool) -> TimelineFamily {
        if hasGap { return .gap }
        if families[.tamper] != nil { return .tamper }
        var best = TimelineFamily.other
        var n = 0
        // Iterate in a fixed order: dictionary order is not deterministic, and
        // a tie must resolve the same way here as it does in JS (first wins).
        for family in TimelineFamily.allCases {
            if let c = families[family], c > n { n = c; best = family }
        }
        return best
    }

    /// Interleave day headers and fold pleats with the records, in reading
    /// order. A fold that crosses midnight is emitted BEFORE the new day's
    /// header, so an overnight quiet reads: last event, pleat, new day, first
    /// event. Heartbeats inside a fold are summarized by it, not listed.
    static func items(records: [TimelineRecord],
                             segments: [TimelineSegment],
                             days: [TimelineDay]) -> [TimelineItem] {
        var out: [TimelineItem] = []
        var dayByT0: [Int: TimelineDay] = [:]
        for d in days { dayByT0[d.dayT0] = d }
        let folds = segments.filter { $0.kind == .fold }
        var foldIndex = 0
        var currentDay: Int?

        for (index, r) in records.enumerated() {
            if r.kind == .heartbeat, folds.contains(where: { r.t0 >= $0.t0 && r.t0 < $0.t1 }) { continue }
            while foldIndex < folds.count, folds[foldIndex].t0 <= r.t0 {
                let f = folds[foldIndex]
                foldIndex += 1
                out.append(.fold(t0: f.t0, t1: f.t1, heartbeats: f.heartbeats))
            }
            let dayT0 = Int((Double(r.t0) / Double(daySeconds)).rounded(.down)) * daySeconds
            if dayT0 != currentDay, let day = dayByT0[dayT0] {
                // Advance the cursor only when a header is actually emitted, so
                // a heartbeat-only stretch cannot swallow the header belonging
                // to the visible record that follows it on the same day.
                out.append(.day(day))
                currentDay = dayT0
            }
            out.append(.record(r, index: index))
        }
        while foldIndex < folds.count {
            let f = folds[foldIndex]
            foldIndex += 1
            out.append(.fold(t0: f.t0, t1: f.t1, heartbeats: f.heartbeats))
        }
        return out
    }

    /// Build the whole model in one call.
    static func model(for input: [TimelineRecord],
                             unparsed: Int = 0,
                             coverageT0: Int? = nil,
                             coverageT1: Int? = nil,
                             bucketSeconds: Int? = nil,
                             calendar: Calendar = utcCalendar) -> TimelineModel {
        let records = sorted(input)
        let bucket = bucketSeconds ?? mostCommonSize(records) ?? defaultBucketSeconds
        var m = TimelineModel()
        m.records = records
        m.bucketSeconds = bucket
        m.unparsed = unparsed
        m.segments = segments(for: records, coverageT0: coverageT0, coverageT1: coverageT1)
        m.days = days(for: records, bucketSeconds: bucket,
                      coverageT0: coverageT0, coverageT1: coverageT1, calendar: calendar)
        m.items = items(records: records, segments: m.segments, days: m.days)
        var zones: [String] = []
        for r in records where r.kind == .event && !r.zone.isEmpty && !zones.contains(r.zone) {
            zones.append(r.zone)
        }
        m.zones = zones
        for r in records where r.kind != .heartbeat {
            m.counts[r.family, default: 0] += 1
        }
        m.heartbeats = records.filter { $0.kind == .heartbeat }.count
        return m
    }

    static func mostCommonSize(_ records: [TimelineRecord]) -> Int? {
        var freq: [Int: Int] = [:]
        for r in records { freq[r.size, default: 0] += 1 }
        var best: Int?
        var n = 0
        // Ascending key order so ties resolve deterministically across runs.
        for size in freq.keys.sorted() where freq[size]! > n {
            n = freq[size]!
            best = size
        }
        return best
    }

    // MARK: - Greeked text (the Sublime minimap trick)

    /// A stroke's width comes from its label's length: the alert is drawn as
    /// an unreadable-but-recognizable line of "text", so a day of alerts has
    /// the shape of a page. Clamped so the minimap column stays composed.
    static func greekWidth(_ label: String) -> Double {
        Double(max(12, min(46, Int((10.0 + Double(label.count) * 1.3).rounded()))))
    }

    /// Same zone, same indent, in order of first appearance — recurring places
    /// line up into columns the way indentation shapes code in a minimap.
    static func zoneIndent(_ zones: [String], _ zone: String) -> Double {
        guard let i = zones.firstIndex(of: zone) else { return 0 }
        return Double(min(i, 4) * 6)
    }

    // MARK: - Bridges from the app's own feeds

    /// The alert ledger, as timeline records.
    ///
    /// `AlertRecord` carries a severity but no event type, zone, or
    /// confidence, so the family is left at `.other` except for tamper — on
    /// this surface the categorical axis IS severity (the established
    /// vocabulary: `Severity.role` -> `Theme.Role`), and the view colors by
    /// it. Inventing a per-event hue here would put a second color language
    /// beside the one the rest of the app already speaks.
    ///
    /// A collapsed row is placed at `lastBucket` — the most recent occurrence
    /// is what "when" means for a row that stands for several.
    static func records(from alerts: [AlertRecord]) -> [TimelineRecord] {
        alerts.map { a in
            let severity = a.severity
            return TimelineRecord(
                t0: Int(a.lastBucket.timeIntervalSince1970),
                size: defaultBucketSeconds,
                kind: .event,
                label: a.headline,
                family: severity == .tamper ? .tamper : .other,
                zone: "",
                confidence: nil,
                details: a.count > 1 ? "\(a.count)×" : "",
                severityRaw: a.severityRaw)
        }
    }

    // The witness-chain feed (`TimelineEvent`) gets its own bridge in the app
    // target, NOT here: that type lives in Sources/SecuraCV, which the widgets
    // and the watch do not compile, and this file must stay buildable by every
    // target that takes `Shared` wholesale.

    // MARK: - Deterministic UTC formatting

    /// UTC, fixed-format, locale-independent — the same strings the web
    /// timeline prints, so a screenshot from one surface matches the other.
    /// (User-facing surfaces that prefer local time format from `t0` on their
    /// own; these are the parity-checked canonical forms.)
    static let utc = TimeZone(secondsFromGMT: 0)!

    /// The parity default. The evidence viewer reads the log in the record's
    /// own frame, so day boundaries are UTC there; the phone passes
    /// `Calendar.current` instead (see `days(for:…:calendar:)`).
    static let utcCalendar: Calendar = {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = utc
        return cal
    }()

    static let monthNames = ["January", "February", "March", "April", "May", "June", "July",
                             "August", "September", "October", "November", "December"]
    static let weekdayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

    static func utcComponents(_ epochSeconds: Int, calendar: Calendar = utcCalendar) -> DateComponents {
        calendar.dateComponents([.year, .month, .day, .hour, .minute, .weekday],
                                from: Date(timeIntervalSince1970: TimeInterval(epochSeconds)))
    }

    static func hourMinute(_ epochSeconds: Int) -> String {
        let c = utcComponents(epochSeconds)
        return String(format: "%02d:%02d", c.hour ?? 0, c.minute ?? 0)
    }

    /// "06:40 – 06:50" — the honest range a bucket is, never a fake instant.
    static func bucketRange(_ t0: Int, _ size: Int = defaultBucketSeconds) -> String {
        hourMinute(t0) + " – " + hourMinute(t0 + size)
    }

    /// Formatted in the SAME calendar the day was grouped by, or the header
    /// would name a different day than the rows beneath it.
    static func dayLabel(_ dayT0: Int, calendar: Calendar = utcCalendar) -> String {
        let c = utcComponents(dayT0, calendar: calendar)
        let weekday = weekdayNames[max(0, (c.weekday ?? 1) - 1)]
        let month = monthNames[max(0, (c.month ?? 1) - 1)]
        return "\(weekday), \(month) \(c.day ?? 1), \(c.year ?? 1970)"
    }

    static func duration(_ seconds: Int) -> String {
        if seconds >= daySeconds {
            let d = seconds / daySeconds
            let h = Int((Double(seconds % daySeconds) / 3600.0).rounded())
            return h > 0 ? "\(d) d \(h) h" : "\(d) d"
        }
        if seconds >= 3600 {
            let h = seconds / 3600
            let m = Int((Double(seconds % 3600) / 60.0).rounded())
            return m > 0 ? "\(h) h \(m) m" : "\(h) h"
        }
        return "\(max(1, Int((Double(seconds) / 60.0).rounded()))) m"
    }
}
