export_chain:
  target:
    entity:
      integration: securacv
  fields:
    format:
      required: false
      default: json
      example: json
      selector:
        select:
          options:
            - json
            - pwk_bundle

verify_chain:
  target:
    entity:
      integration: securacv
