#!/usr/bin/env python3
"""Generate tools/hub_voice_setup.sh — the hub voice wizard.

The wizard installs the local voice stack on a Home Assistant OS hub and
teaches it the fleet sentences. Those sentences have ONE source of truth —
docs/voice_sentences_en.yaml, the same file docs/voice_control.md links —
and this generator embeds them verbatim, so the wizard can never install a
different grammar than the one the docs promise. CI regenerates and
byte-diffs (--check), the same drift gate every generator in this repo
lives behind.

Usage:
  python3 scripts/gen_hub_voice_setup.py           # write the script
  python3 scripts/gen_hub_voice_setup.py --check   # CI: fail if stale
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SENTENCES_SRC = REPO / "docs" / "voice_sentences_en.yaml"
OUTPUT = REPO / "tools" / "hub_voice_setup.sh"

TEMPLATE = """#!/usr/bin/env bash
# GENERATED by scripts/gen_hub_voice_setup.py — do not edit by hand.
# The embedded sentences come verbatim from docs/voice_sentences_en.yaml;
# CI byte-checks this file against the generator, so it cannot drift.
#
# SecuraCV — give your hub a voice.
#
#   bash hub_voice_setup.sh           install everything (idempotent)
#   bash hub_voice_setup.sh verify    report state, change nothing
#
# Runs ON the hub (Home Assistant OS), from the Terminal or SSH add-on.
# Everything it sets up runs locally on this machine: no account, no
# cloud service, no audio or transcript ever stored or sent anywhere.
# Every step checks before it acts, so re-running is always safe.

set -u

SENTENCES_DEST=/config/custom_sentences/en/securacv.yaml
WAKE_DIR=/share/openwakeword
WAKE_MODEL=hey_canary.tflite
OHF_APPS_REPO=https://github.com/OHF-Voice/apps

MODE="${{1:-install}}"
FAILS=0

say()  {{ printf '%s\\n' "$*"; }}
head_() {{ printf '\\n%s\\n' "$*"; }}
ok()   {{ printf '   [ok] %s\\n' "$*"; }}
todo() {{ printf ' [todo] %s\\n' "$*"; }}
warn() {{ printf ' [warn] %s\\n' "$*"; FAILS=$((FAILS+1)); }}

have_ha() {{ command -v ha >/dev/null 2>&1; }}

# Home Assistant renamed add-ons to "apps", and the CLI noun moved with
# it (`ha apps ...`). Older installs still only answer to `ha addons`.
# Detect once, then use whichever this hub actually has — a script that
# hard-codes either one breaks on half the world's hubs.
ADDON_NOUN=""
detect_noun() {{
  if [ -n "$ADDON_NOUN" ]; then return 0; fi
  if ha apps list >/dev/null 2>&1 || ha apps --help >/dev/null 2>&1; then
    ADDON_NOUN=apps
  else
    ADDON_NOUN=addons
  fi
}}

ha_addon() {{ detect_noun; ha "$ADDON_NOUN" "$@"; }}

# `ha addons info` also answers for store-only (not-installed) add-ons, so
# success alone proves nothing. An installed add-on reports a non-null
# "version" string; a store-only one reports "version": null.
addon_installed() {{
  ha_addon info "$1" --raw-json 2>/dev/null | grep -Eq '"version": *"'
}}

addon_started() {{
  ha_addon info "$1" --raw-json 2>/dev/null | grep -Eq '"state": *"started"'
}}

ensure_addon() {{
  local slug="$1" label="$2"
  if ! addon_installed "$slug"; then
    if [ "$MODE" = verify ]; then warn "$label is not installed"; return; fi
    say "   installing $label..."
    if ! ha_addon install "$slug" >/dev/null; then
      warn "$label ($slug) failed to install — open Settings -> Apps (older hubs: Add-ons) and install it by name"
      return
    fi
  fi
  if addon_started "$slug"; then
    ok "$label is installed and running"
  else
    if [ "$MODE" = verify ]; then warn "$label is installed but not running"; return; fi
    if ha_addon start "$slug" >/dev/null 2>&1; then
      ok "$label started"
    else
      warn "$label installed but would not start — check its log under Settings -> Apps"
    fi
  fi
}}

find_satellite_slug() {{
  ha store --raw-json 2>/dev/null \\
    | grep -Eo '"[a-z0-9_]+assist_satellite"' | head -1 | tr -d '"'
}}

say "SecuraCV hub voice setup ($MODE)"
say "Everything below happens on this hub. Nothing leaves it."

if ! have_ha; then
  say ""
  say "The 'ha' command is not available here. Run this from the hub itself,"
  say "in the Terminal & SSH add-on (Settings -> Add-ons -> Terminal & SSH)."
  exit 1
fi

detect_noun
say "   (this hub's CLI calls them '$ADDON_NOUN')"

head_ "1. The three local voice engines"
ensure_addon core_whisper      "Whisper (speech-to-text)"
ensure_addon core_piper        "Piper (text-to-speech)"
ensure_addon core_openwakeword "openWakeWord (wake word)"

head_ "2. The satellite runtime (Assist Satellite)"
SAT_SLUG="$(find_satellite_slug || true)"
if [ -z "$SAT_SLUG" ] && [ "$MODE" != verify ]; then
  say "   adding the OHF-Voice apps repository..."
  # The HA CLI command is `ha store add <repository>` (store_repositories_add.go).
  if ! ha store add "$OHF_APPS_REPO" >/dev/null; then
    warn "could not add $OHF_APPS_REPO to the store — add it under Settings -> Add-ons -> Store -> (top-right menu) Repositories"
  fi
  ha store reload >/dev/null 2>&1 || true
  SAT_SLUG="$(find_satellite_slug || true)"
fi
if [ -n "$SAT_SLUG" ]; then
  ensure_addon "$SAT_SLUG" "Assist Satellite"
else
  warn "Assist Satellite not found in the store — add $OHF_APPS_REPO under Settings -> Add-ons -> Store -> (top-right menu) Repositories, then re-run"
fi

head_ "3. The fleet sentences"
TMP_SENTENCES="$(mktemp)"
cat > "$TMP_SENTENCES" <<'SECURACV_SENTENCES'
{sentences}SECURACV_SENTENCES
if [ -f "$SENTENCES_DEST" ] && cmp -s "$TMP_SENTENCES" "$SENTENCES_DEST"; then
  ok "sentences already current ($SENTENCES_DEST)"
elif [ "$MODE" = verify ]; then
  warn "sentences missing or out of date at $SENTENCES_DEST"
else
  mkdir -p "$(dirname "$SENTENCES_DEST")"
  cp "$TMP_SENTENCES" "$SENTENCES_DEST"
  ok "sentences installed ($SENTENCES_DEST)"
  todo "restart Home Assistant when convenient so it reads them: ha core restart"
fi
rm -f "$TMP_SENTENCES"

head_ "4. The wake word"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$WAKE_DIR/$WAKE_MODEL" ]; then
  ok "'Hey Canary' model present — pick 'hey_canary' in your assistant's wake word menu"
elif [ -f "$SCRIPT_DIR/$WAKE_MODEL" ] && [ "$MODE" != verify ]; then
  mkdir -p "$WAKE_DIR"
  cp "$SCRIPT_DIR/$WAKE_MODEL" "$WAKE_DIR/$WAKE_MODEL"
  ok "'Hey Canary' model installed to $WAKE_DIR"
else
  say "   no custom model yet — the built-in wake words (e.g. 'Okay Nabu') work today."
  say "   To mint 'Hey Canary', see docs/voice_control.md, 'Your wake word'."
fi

head_ "Done. Two clicks remain (they need your eyes, not a script):"
say "   1. Settings -> Voice assistants -> Add assistant:"
say "      speech-to-text Whisper, text-to-speech Piper, and your wake word."
say "   2. A USB microphone is NOT usable by Assist on its own — install"
say "      the Assist Satellite app and point it at your mic and speaker."
say ""
say "Hello world, in this order — each step proves the one before it:"
say "   a. Type 'what's up' into the Assist box (no mic needed at all)."
say "   b. Press the mic button in that box and say it."
say "   c. Say it to the room, once the satellite has your USB devices."
say ""
say "What this never does: no sentence can arm, disarm, or unseal anything,"
say "no audio or transcript is kept, and nothing leaves this hub."

[ "$FAILS" -eq 0 ] || exit 1
"""


def render() -> str:
    sentences = SENTENCES_SRC.read_text(encoding="utf-8")
    if not sentences.endswith("\n"):
        sentences += "\n"
    return TEMPLATE.format(sentences=sentences)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print(
                "gen_hub_voice_setup.py --check: tools/hub_voice_setup.sh is "
                "stale — re-run scripts/gen_hub_voice_setup.py and commit."
            )
            return 1
        print("gen_hub_voice_setup.py --check: OK")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    OUTPUT.chmod(0o755)
    print(f"  wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
