#!/usr/bin/env bash
set -euo pipefail
#
# Re-vendor the Witness Wall emulator from the securacv_website checkout into
# EVERY app surface that embeds it — one command, all copies, byte-identical.
#
#   desktop/src/witness/       — the Flasher's "Your Fleet" tab (iframe)
#   canary-local/witness/      — the Lab (desktop app + browser Lab + Pages)
#
# The website is the CANONICAL emulator (witness-wall.html + js/tv-emulator.js
# + js/highlight.js + demo-fleet.json). The app copies differ from the site
# page by ONE deterministic transform, applied here (never by hand):
#
#   - drop the site chrome: favicon links, Google Fonts, css/site.css,
#     <header class="site">…</header>, <footer class="site">…</footer>, js/site.js
#   - flatten the script path (js/tv-emulator.js → tv-emulator.js)
#   - absolutize root-relative links (href="/…" → https://securacv.com/…) so a
#     link tapped inside an app webview opens the real site instead of 404ing
#     against the app origin
#
# Usage (from the securaCV repo root, with a sibling website checkout):
#   scripts/vendor_witness_emulator.sh [path-to-securacv_website]
#
# After running: commit the refreshed copies. CI keeps the in-repo copies
# honest via scripts/check_witness_emulator_sync.sh (byte-compare between the
# two app copies — cross-repo drift is caught by the sha256s this script
# records in each PROVENANCE.txt).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SRC="${1:-${REPO_ROOT}/../securacv_website}"

for f in witness-wall.html js/tv-emulator.js js/highlight.js demo-fleet.json; do
  [ -f "${SRC}/${f}" ] || { echo "::error::missing ${SRC}/${f} — pass the website checkout path"; exit 1; }
done

DESTS=(
  "${REPO_ROOT}/desktop/src/witness"
  "${REPO_ROOT}/canary-local/witness"
)

# ── the one transform: site page → embedded page ──────────────────────────────
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
# Asset references may carry a ?v= cache-buster on the site (the site's
# unfingerprinted-asset policy), so match up to the closing quote instead of
# demanding the bare filename — anchoring on `.js"` silently stopped matching
# the day the site added `?v=`, and the vendored pages shipped pointing at a
# js/ directory that doesn't exist beside them.
sed -E \
  -e '/rel="icon"/d' \
  -e '/rel="apple-touch-icon"/d' \
  -e '/fonts\.googleapis\.com/d' \
  -e '/href="css\/site\.css[^"]*"/d' \
  -e '/<header class="site">/,/<\/header>/d' \
  -e '/<footer class="site">/,/<\/footer>/d' \
  -e '/src="js\/site\.js[^"]*"/d' \
  -e 's|src="js/tv-emulator\.js[^"]*"|src="tv-emulator.js"|' \
  -e 's|href="/([^"]*)"|href="https://securacv.com/\1"|g' \
  "${SRC}/witness-wall.html" > "$TMP"

sum() { sha256sum "$1" | cut -d' ' -f1; }
SRC_HTML_SHA="$(sum "${SRC}/witness-wall.html")"
SRC_JS_SHA="$(sum "${SRC}/js/tv-emulator.js")"
SRC_HL_SHA="$(sum "${SRC}/js/highlight.js")"
SRC_DEMO_SHA="$(sum "${SRC}/demo-fleet.json")"

for dest in "${DESTS[@]}"; do
  mkdir -p "$dest"
  cp "$TMP"                      "${dest}/witness.html"
  cp "${SRC}/js/tv-emulator.js"  "${dest}/tv-emulator.js"
  cp "${SRC}/js/highlight.js"    "${dest}/highlight.js"
  cp "${SRC}/demo-fleet.json"    "${dest}/demo-fleet.json"
  cat > "${dest}/PROVENANCE.txt" <<EOF
Vendored from the securacv_website repo — the canonical Witness Wall emulator.
Generated by scripts/vendor_witness_emulator.sh — DO NOT EDIT THESE FILES BY
HAND; change the website emulator, then re-run the script (it refreshes every
app copy in one pass, so the Flasher and the Lab can never drift apart —
scripts/check_witness_emulator_sync.sh enforces that in CI).

  witness.html      <- witness-wall.html, one deterministic transform: site
                       chrome removed (header/footer/fonts/site.css/site.js),
                       script path flattened, root-relative links absolutized.
  tv-emulator.js    <- js/tv-emulator.js  (byte-identical; window.witnessWall +
                       the witness:appear/connect/fleet/skin/profile API)
  highlight.js      <- js/highlight.js    (byte-identical)
  demo-fleet.json   <- demo-fleet.json    (byte-identical)

Source sha256 at vendoring time:
  witness-wall.html  ${SRC_HTML_SHA}
  js/tv-emulator.js  ${SRC_JS_SHA}
  js/highlight.js    ${SRC_HL_SHA}
  demo-fleet.json    ${SRC_DEMO_SHA}

The host app drives the wall over postMessage (see tvos/EMBED_IN_APPS.md):
witness:appear after a flash, witness:fleet with a LAN-discovered fleet from
the native witness_discover command, witness:skin / witness:profile to match
the surface's use case (?profile=home|business|apartment works too).
EOF
done

echo "vendored → ${DESTS[*]}"
echo "source witness-wall.html ${SRC_HTML_SHA}"
