#!/usr/bin/env bash
set -euo pipefail
#
# Re-vendor the evidence-envelope verifier core into the securacv_website TV
# app — one command, byte-identical, with a recorded upstream provenance.
#
# The CANONICAL verifier is this repo's viewer/verify_core.js (shared by the
# offline HTML viewer and the Node parity tests, and pinned byte-for-byte to
# the Rust verifier). The TV Witness Wall (securacv_website tv/) ships a
# vendored copy so its "verified" badge runs the SAME code — tv/index.html
# says exactly that. This script keeps that copy honest: it re-copies the
# verifier + the fixtures the website's tv-wall.test.mjs checks it against, and
# records the upstream sha256 of each in tv/vendor/PROVENANCE.txt so a human
# (and a reviewer) can see which revision the copy was cut from.
#
# The website's tv-wall.test.mjs guards BEHAVIOR (it verifies real fixtures and
# rejects tampered ones, incl. the export-bundle + rotated-key paths), which is
# a stronger guarantee than a byte-compare — but it can only catch a stale copy
# if the fixtures it exercises travel with the verifier, which is what this
# script carries.
#
# Usage (from the securaCV repo root, with a sibling website checkout):
#   scripts/vendor_tv_verifier.sh [path-to-securacv_website]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SITE="${1:-${REPO_ROOT}/../securacv_website}"

SRC_VERIFIER="${REPO_ROOT}/viewer/verify_core.js"
SRC_ENVELOPE="${REPO_ROOT}/tests/fixtures/envelope"
SRC_BUNDLE="${REPO_ROOT}/tests/fixtures/export_bundle"

# The fixtures the TV app's test suite verifies against (the valid envelopes
# for every auth mode + the rotated-key lineage, the tamper cases, and the
# self-attested export bundle).
ENVELOPE_FIXTURES=(
  valid_envelope.json
  valid_envelope_legacy.json
  valid_envelope_self_export.json
  valid_envelope_rotated.json
  tampered_payload.json
  tampered_digest.json
)
BUNDLE_FIXTURES=(valid_bundle.json)

[ -f "$SRC_VERIFIER" ] || { echo "::error::missing $SRC_VERIFIER"; exit 1; }
[ -d "${SITE}/tv/vendor" ] || { echo "::error::${SITE} does not look like the website checkout (no tv/vendor)"; exit 1; }
for f in "${ENVELOPE_FIXTURES[@]}"; do
  [ -f "${SRC_ENVELOPE}/${f}" ] || { echo "::error::missing ${SRC_ENVELOPE}/${f}"; exit 1; }
done
for f in "${BUNDLE_FIXTURES[@]}"; do
  [ -f "${SRC_BUNDLE}/${f}" ] || { echo "::error::missing ${SRC_BUNDLE}/${f}"; exit 1; }
done

sum() { sha256sum "$1" | cut -d' ' -f1; }

DEST_VENDOR="${SITE}/tv/vendor"
DEST_ENVELOPE="${SITE}/tests/fixtures/envelope"
DEST_BUNDLE="${SITE}/tests/fixtures/export_bundle"
mkdir -p "$DEST_VENDOR" "$DEST_ENVELOPE" "$DEST_BUNDLE"

cp "$SRC_VERIFIER" "${DEST_VENDOR}/verify_core.js"
for f in "${ENVELOPE_FIXTURES[@]}"; do cp "${SRC_ENVELOPE}/${f}" "${DEST_ENVELOPE}/${f}"; done
for f in "${BUNDLE_FIXTURES[@]}"; do cp "${SRC_BUNDLE}/${f}"   "${DEST_BUNDLE}/${f}"; done

{
  echo "Vendored from the securaCV repo — the canonical evidence-envelope verifier."
  echo "Generated by scripts/vendor_tv_verifier.sh — DO NOT EDIT verify_core.js or"
  echo "the carried fixtures by hand; change viewer/verify_core.js in securaCV, then"
  echo "re-run the script. The website's tests/tv-wall.test.mjs verifies BEHAVIOR"
  echo "against these fixtures (a stronger guarantee than a byte-compare)."
  echo ""
  echo "upstream: securaCV viewer/verify_core.js"
  echo "  verify_core.js  sha256:$(sum "$SRC_VERIFIER")"
  echo ""
  echo "upstream fixtures: securaCV tests/fixtures/"
  for f in "${ENVELOPE_FIXTURES[@]}"; do
    echo "  envelope/${f}  sha256:$(sum "${SRC_ENVELOPE}/${f}")"
  done
  for f in "${BUNDLE_FIXTURES[@]}"; do
    echo "  export_bundle/${f}  sha256:$(sum "${SRC_BUNDLE}/${f}")"
  done
} > "${DEST_VENDOR}/PROVENANCE.txt"

echo "OK: vendored verify_core.js + $(( ${#ENVELOPE_FIXTURES[@]} + ${#BUNDLE_FIXTURES[@]} )) fixtures into ${SITE}"
echo "    wrote ${DEST_VENDOR}/PROVENANCE.txt"
