//  WallSurfaceTests.swift — the Wall's second parity round, pinned.
//
//  Round one made the Wall DESCRIBE devices the way the phone does (names,
//  figures, chain honesty — DeviceParityTests). This suite pins round two:
//  the Wall now also SHOWS devices the way the phone does (the 3D turntable
//  behind every card) and dresses the way the Mac's Witness Wall view does
//  (the same six skins, by name, in the same order). Each test states a
//  cross-surface promise, so breaking one names the surface that drifted.

import XCTest
@testable import WitnessWall

final class WallSurfaceTests: XCTestCase {

    /// Every figure in the catalog has its massing — so the detail view can
    /// never show the generic fallback for a device the phone can spin. The
    /// two are generated by the same run of gen_figures.mjs, and this is the
    /// Wall-side assertion that neither half arrived without the other.
    func testEveryFigureHasItsMassing() {
        XCTAssertFalse(FleetFigure.all.isEmpty)
        for id in FleetFigure.all.keys {
            XCTAssertNotNil(FleetMassing.all[id],
                            "figure \(id) has no massing — the detail view would show "
                            + "the generic marker where the phone shows the part")
        }
    }

    /// The shared projector plans real polygons for the display line at a
    /// non-canonical yaw — the exact call the tvOS turntable makes every
    /// frame while it turns.
    func testTheTurntablePlansTheDisplayLine() throws {
        let massing = try XCTUnwrap(FleetMassing.all["device.canary-display-dash7"])
        let ops = FleetIsoProjector.plan(massing, size: 256, yaw: 0.7, frame: .turntable)
        XCTAssertFalse(ops.isEmpty, "a massing that plans no polygons draws nothing")
    }

    /// Six skins, the Mac view's names, the Mac view's order — "set it to
    /// Sunset" must mean one thing on every surface.
    func testTheSkinsMatchTheMacViewsSix() {
        XCTAssertEqual(WallSkin.allCases.map(\.rawValue),
                       ["midnight", "daylight", "noir", "sunset", "terminal", "paper"])
    }

    /// Every room can introduce itself in the settings panel, and no blurb
    /// uses the forbidden group noun.
    func testEveryProfileIntroducesItselfHonestly() {
        for profile in WallProfile.allCases {
            XCTAssertFalse(profile.blurb.isEmpty, profile.rawValue)
            XCTAssertFalse(profile.blurb.lowercased().contains("flock"), profile.rawValue)
        }
    }
}
